import * as XLSX from "xlsx";
import type { FinancialModelInputs } from "@/lib/financialModellingEngine";
import type { LoanScheduleYear, StatementYear } from "@/lib/phase1FinancialEngine";

export function downloadFinancialModelWorkbook(args: { company: string; currency: string; inputs: FinancialModelInputs; statements: StatementYear[]; loan: LoanScheduleYear[] }) {
  const { company, currency, inputs, statements, loan } = args;
  const workbook = XLSX.utils.book_new();
  const years = statements.map(row => `Year ${row.year}`);
  const add = (name: string, rows: (string | number)[][]) => { const sheet = XLSX.utils.aoa_to_sheet(rows); XLSX.utils.book_append_sheet(workbook, sheet, name); return sheet; };
  const formula = (sheet: XLSX.WorkSheet, row: number, col: number, f: string) => { const address=XLSX.utils.encode_cell({r:row,c:col}); sheet[address] = { ...(sheet[address] ?? { t:"n", v:0 }), f }; };
  const styleWidths = (sheet: XLSX.WorkSheet, count: number) => { sheet["!cols"]=[{wch:28},...Array.from({length:count},()=>({wch:16}))]; };

  add("Cover", [[company], ["Investment-grade financial model"], ["Currency", currency], ["Generated", new Date().toLocaleDateString()], ["Instructions", "Blue input sheets contain model assumptions. Financial statements and ratios contain live formulas linked to the model forecast and loan schedule."]]);
  const assumptions = add("Assumptions", [["Assumption","Value","Unit"], ["Projection period",inputs.years,"years"], ["Starting customers",inputs.startingCustomers,"customers / units"], ["Annual growth",inputs.annualCustomerGrowth,"%"], ["Annual price",inputs.annualPrice,currency], ["Gross margin",inputs.grossMargin,"%"], ["Payroll",inputs.annualPayroll,currency], ["Overheads",inputs.annualOverheads,currency], ["Capex",inputs.capex,currency], ["Funding required",inputs.fundingRequired,currency], ["Debt share",inputs.debtShare,"%"], ["Interest rate",inputs.interestRate,"%"], ["Loan term",inputs.loanTerm,"years"], ["Repayment method",inputs.repaymentMethod ?? "equal-principal",""], ["Principal grace period",inputs.gracePeriod ?? 0,"years"], ["Balloon at maturity",inputs.balloonPercent ?? 0,"%"], ["Tax rate",inputs.taxRate,"%"], ["Receivable days",inputs.receivableDays,"days"], ["Inventory days",inputs.inventoryDays ?? 0,"days"], ["Payable days",inputs.payableDays,"days"]]);
  assumptions["!cols"]=[{wch:28},{wch:18},{wch:18}];
  const forecast = add("Model Forecast", [[`Operating forecast (${currency})`,...years], ["Revenue",...statements.map(r=>r.revenue)], ["Cost of sales",...statements.map(r=>r.costOfSales)], ["Operating expenses",...statements.map(r=>r.operatingExpenses)], ["Depreciation",...statements.map(r=>r.depreciation)]]);
  styleWidths(forecast, statements.length);
  const loanSheet = add("Loan Schedule", [[`Loan schedule (${currency})`,...years], ["Opening balance",...loan.map(r=>r.openingBalance)], ["Principal",...loan.map(r=>r.principal)], ["Interest",...loan.map(r=>r.interest)], ["Debt service",...loan.map(r=>r.debtService)], ["Closing balance",...loan.map(r=>r.closingBalance)]]);
  styleWidths(loanSheet, statements.length);

  const income = add("Income Statement", [[`Income Statement (${currency})`,...years], ["Revenue",...statements.map(r=>r.revenue)], ["Cost of sales",...statements.map(r=>r.costOfSales)], ["Gross profit",...statements.map(r=>r.grossProfit)], ["Operating expenses",...statements.map(r=>r.operatingExpenses)], ["EBITDA",...statements.map(r=>r.ebitda)], ["Depreciation",...statements.map(r=>r.depreciation)], ["EBIT",...statements.map(r=>r.ebit)], ["Interest",...statements.map(r=>r.interest)], ["Tax",...statements.map(r=>r.tax)], ["Net profit",...statements.map(r=>r.netProfit)]]);
  statements.forEach((_,i)=>{ const c=i+1,L=XLSX.utils.encode_col(c); formula(income,1,c,`'Model Forecast'!${L}2`); formula(income,2,c,`'Model Forecast'!${L}3`); formula(income,3,c,`${L}2-${L}3`); formula(income,4,c,`'Model Forecast'!${L}4`); formula(income,5,c,`${L}4-${L}5`); formula(income,6,c,`'Model Forecast'!${L}5`); formula(income,7,c,`${L}6-${L}7`); formula(income,8,c,`'Loan Schedule'!${L}4`); formula(income,9,c,`MAX(0,(${L}8-${L}9)*Assumptions!$B$17/100)`); formula(income,10,c,`${L}8-${L}9-${L}10`); }); styleWidths(income,statements.length);

  const cashFlow = add("Cash Flow", [[`Cash Flow (${currency})`,...years], ["Operating cash flow",...statements.map(r=>r.operatingCashFlow)], ["Investing cash flow",...statements.map(r=>r.investingCashFlow)], ["Financing cash flow",...statements.map(r=>r.financingCashFlow)], ["Net cash movement",...statements.map(r=>r.netCashMovement)], ["Opening cash",...statements.map(r=>r.openingCash)], ["Closing cash",...statements.map(r=>r.closingCash)]]);
  statements.forEach((_,i)=>{const c=i+1,L=XLSX.utils.encode_col(c),P=i?XLSX.utils.encode_col(c-1):""; const wc=`('Income Statement'!${L}2*Assumptions!$B$18/365+'Income Statement'!${L}3*Assumptions!$B$19/365-'Income Statement'!${L}3*Assumptions!$B$20/365)`; const prev=i?`-('Income Statement'!${P}2*Assumptions!$B$18/365+'Income Statement'!${P}3*Assumptions!$B$19/365-'Income Statement'!${P}3*Assumptions!$B$20/365)`:""; formula(cashFlow,1,c,`'Income Statement'!${L}11+'Income Statement'!${L}7-${wc}${prev}`); formula(cashFlow,2,c,i===0?`-Assumptions!$B$9`:"0"); formula(cashFlow,3,c,i===0?`Assumptions!$B$10-'Loan Schedule'!${L}3`:`-'Loan Schedule'!${L}3`); formula(cashFlow,4,c,`${L}2+${L}3+${L}4`); formula(cashFlow,5,c,i===0?"0":`${P}7`); formula(cashFlow,6,c,`${L}6+${L}5`);}); styleWidths(cashFlow,statements.length);

  const balance = add("Balance Sheet", [[`Balance Sheet (${currency})`,...years], ["Cash",...statements.map(r=>r.cash)], ["Receivables",...statements.map(r=>r.receivables)], ["Inventory",...statements.map(r=>r.inventory)], ["Net PPE",...statements.map(r=>r.netPpe)], ["Total assets",...statements.map(r=>r.totalAssets)], ["Payables",...statements.map(r=>r.payables)], ["Debt",...statements.map(r=>r.debt)], ["Total liabilities",...statements.map(r=>r.totalLiabilities)], ["Equity",...statements.map(r=>r.equity)], ["Liabilities and equity",...statements.map(r=>r.totalLiabilitiesAndEquity)], ["Balance check",...statements.map(r=>r.balanceCheck)]]);
  statements.forEach((_,i)=>{const c=i+1,L=XLSX.utils.encode_col(c); formula(balance,1,c,`'Cash Flow'!${L}7`); formula(balance,2,c,`'Income Statement'!${L}2*Assumptions!$B$18/365`); formula(balance,3,c,`'Income Statement'!${L}3*Assumptions!$B$19/365`); formula(balance,4,c,`MAX(0,Assumptions!$B$9-'Income Statement'!${L}7*${i+1})`); formula(balance,5,c,`SUM(${L}2:${L}5)`); formula(balance,6,c,`'Income Statement'!${L}3*Assumptions!$B$20/365`); formula(balance,7,c,`'Loan Schedule'!${L}6`); formula(balance,8,c,`${L}7+${L}8`); formula(balance,9,c,`${L}6-${L}9`); formula(balance,10,c,`${L}9+${L}10`); formula(balance,11,c,`${L}6-${L}11`);}); styleWidths(balance,statements.length);

  const ratioLines: [string,keyof StatementYear][] = [["Current ratio","currentRatio"],["Quick ratio","quickRatio"],["Cash ratio","cashRatio"],["Gross margin","grossMargin"],["EBITDA margin","ebitdaMargin"],["Operating margin","operatingMargin"],["Net margin","netMargin"],["Return on assets","returnOnAssets"],["Return on equity","returnOnEquity"],["ROCE","returnOnCapitalEmployed"],["Asset turnover","assetTurnover"],["Debt / equity","debtToEquity"],["Debt / EBITDA","debtToEbitda"],["Debt ratio","debtRatio"],["Gearing","gearing"],["Interest cover","interestCover"],["DSCR","dscr"]];
  const ratios=add("Financial Ratios",[["Ratio",...years],...ratioLines.map(([label,key])=>[label,...statements.map(r=>Number(r[key]))])]);
  statements.forEach((_,i)=>{const c=i+1,L=XLSX.utils.encode_col(c); const formulas=[`('Balance Sheet'!${L}2+'Balance Sheet'!${L}3+'Balance Sheet'!${L}4)/('Balance Sheet'!${L}7+'Loan Schedule'!${L}3)`,`('Balance Sheet'!${L}2+'Balance Sheet'!${L}3)/('Balance Sheet'!${L}7+'Loan Schedule'!${L}3)`,`'Balance Sheet'!${L}2/('Balance Sheet'!${L}7+'Loan Schedule'!${L}3)`,`'Income Statement'!${L}4/'Income Statement'!${L}2`,`'Income Statement'!${L}6/'Income Statement'!${L}2`,`'Income Statement'!${L}8/'Income Statement'!${L}2`,`'Income Statement'!${L}11/'Income Statement'!${L}2`,`'Income Statement'!${L}11/'Balance Sheet'!${L}6`,`'Income Statement'!${L}11/'Balance Sheet'!${L}10`,`'Income Statement'!${L}8/('Balance Sheet'!${L}6-'Balance Sheet'!${L}7-'Loan Schedule'!${L}3)`,`'Income Statement'!${L}2/'Balance Sheet'!${L}6`,`'Balance Sheet'!${L}8/'Balance Sheet'!${L}10`,`'Balance Sheet'!${L}8/'Income Statement'!${L}6`,`'Balance Sheet'!${L}8/'Balance Sheet'!${L}6`,`'Balance Sheet'!${L}8/('Balance Sheet'!${L}8+'Balance Sheet'!${L}10)`,`'Income Statement'!${L}8/'Income Statement'!${L}9`,`('Income Statement'!${L}6-'Income Statement'!${L}10)/'Loan Schedule'!${L}5`]; formulas.forEach((f,r)=>formula(ratios,r+1,c,`IFERROR(${f},0)`));}); styleWidths(ratios,statements.length);

  XLSX.writeFile(workbook, `${company.replace(/\W+/g,"-").toLowerCase() || "boat"}-financial-model.xlsx`);
}
