import type { FinancialModelInputs } from "@/lib/financialModellingEngine";

export type FinancialIndustryTemplate = {
  name: string;
  description: string;
  customerLabel: string;
  priceLabel: string;
  revenueStreams: string[];
  costDrivers: string[];
  guidance: string;
  benchmark: { grossMargin: [number, number]; growth: [number, number] };
  defaults: FinancialModelInputs;
};

const common: FinancialModelInputs = {
  years: 5, startingCustomers: 500, annualCustomerGrowth: 20, annualPrice: 120,
  churnRate: 5, grossMargin: 45, annualPayroll: 60000, annualOverheads: 36000,
  opexInflation: 6, capex: 80000, fundingRequired: 300000, debtShare: 35,
  interestRate: 16, loanTerm: 5, taxRate: 30, receivableDays: 30, payableDays: 30,
};
const d = (values: Partial<FinancialModelInputs>): FinancialModelInputs => ({ ...common, ...values });

export const FINANCIAL_MODEL_TEMPLATES: FinancialIndustryTemplate[] = [
  { name: "Education Technology", description: "Learner-led subscriptions, devices and institutional licensing.", customerLabel: "Starting learners", priceLabel: "Annual revenue / learner", revenueStreams: ["Learner subscriptions", "Tablet sales", "School licences", "Teacher licences", "Government contracts"], costDrivers: ["Hardware", "Cloud hosting", "Content licensing", "Customer support", "Learning module development"], guidance: "Separate recurring learner and school licences from lower-margin hardware. Model renewals, churn and school acquisition independently.", benchmark: { grossMargin: [55, 80], growth: [25, 60] }, defaults: d({ startingCustomers: 2400, annualCustomerGrowth: 38, annualPrice: 120, churnRate: 8, grossMargin: 72, annualPayroll: 96000, annualOverheads: 42000, capex: 85000, fundingRequired: 500000 }) },
  { name: "Software as a Service", description: "Recurring subscriptions with acquisition, retention and cloud economics.", customerLabel: "Starting accounts", priceLabel: "Annual revenue / account", revenueStreams: ["Monthly subscriptions", "Annual plans", "Enterprise licences", "Implementation", "API usage"], costDrivers: ["Cloud infrastructure", "Customer success", "Engineering", "Sales commissions", "Cybersecurity"], guidance: "Track monthly recurring revenue, customer acquisition cost, churn and expansion revenue. Keep implementation revenue separate from subscriptions.", benchmark: { grossMargin: [70, 90], growth: [30, 80] }, defaults: d({ startingCustomers: 320, annualCustomerGrowth: 52, annualPrice: 960, churnRate: 10, grossMargin: 82, annualPayroll: 145000, annualOverheads: 50000, capex: 45000, fundingRequired: 650000, debtShare: 15 }) },
  { name: "Manufacturing", description: "Capacity-driven production, inventory and distributor sales.", customerLabel: "Annual units", priceLabel: "Average selling price / unit", revenueStreams: ["Finished goods", "Private label", "Contract manufacturing", "By-products", "Maintenance services"], costDrivers: ["Raw materials", "Direct labour", "Factory overhead", "Power and fuel", "Distribution"], guidance: "Link sales to production capacity and utilization. Include raw-material inflation, wastage, inventory days and maintenance capex.", benchmark: { grossMargin: [25, 45], growth: [10, 30] }, defaults: d({ startingCustomers: 18000, annualCustomerGrowth: 18, annualPrice: 28, churnRate: 2, grossMargin: 36, annualPayroll: 110000, annualOverheads: 85000, capex: 420000, fundingRequired: 750000, debtShare: 55, receivableDays: 45, payableDays: 40 }) },
  { name: "Agriculture", description: "Seasonal yields, farm-gate pricing and production-cycle funding.", customerLabel: "Saleable units / kg", priceLabel: "Average price / unit", revenueStreams: ["Crop sales", "Livestock", "Processed products", "Outgrower services", "By-products"], costDrivers: ["Seed and inputs", "Feed", "Farm labour", "Irrigation", "Storage and transport"], guidance: "Model yield, acreage, season timing and post-harvest losses explicitly. Stress-test weather, commodity prices and input costs.", benchmark: { grossMargin: [20, 50], growth: [8, 25] }, defaults: d({ startingCustomers: 90000, annualCustomerGrowth: 14, annualPrice: 2.8, churnRate: 1, grossMargin: 39, annualPayroll: 48000, annualOverheads: 40000, capex: 180000, fundingRequired: 400000, debtShare: 45, receivableDays: 14, payableDays: 35 }) },
  { name: "Hospitality", description: "Room inventory, occupancy and ancillary guest spend.", customerLabel: "Available room nights", priceLabel: "Average daily rate", revenueStreams: ["Room revenue", "Food and beverage", "Conferences", "Laundry", "Spa and activities"], costDrivers: ["Housekeeping", "Food and beverage", "Utilities", "Booking commissions", "Repairs and maintenance"], guidance: "Drive room revenue from available nights, occupancy and average daily rate. Model seasonality and departmental margins separately.", benchmark: { grossMargin: [55, 75], growth: [8, 22] }, defaults: d({ startingCustomers: 10950, annualCustomerGrowth: 12, annualPrice: 68, churnRate: 35, grossMargin: 64, annualPayroll: 135000, annualOverheads: 120000, capex: 300000, fundingRequired: 700000, debtShare: 50, receivableDays: 12, payableDays: 30 }) },
  { name: "Schools", description: "Enrollment, term fees and education support services.", customerLabel: "Enrolled students", priceLabel: "Annual fees / student", revenueStreams: ["Tuition fees", "Boarding", "Transport", "Meals", "Uniforms and activities"], costDrivers: ["Teaching payroll", "Meals", "Learning materials", "Utilities", "Campus maintenance"], guidance: "Model enrollment by class, fee collection rates and term timing. Separate tuition, boarding and optional services.", benchmark: { grossMargin: [35, 60], growth: [5, 18] }, defaults: d({ startingCustomers: 650, annualCustomerGrowth: 10, annualPrice: 780, churnRate: 6, grossMargin: 54, annualPayroll: 170000, annualOverheads: 70000, capex: 220000, fundingRequired: 450000, debtShare: 40, receivableDays: 50, payableDays: 25 }) },
  { name: "SACCOs", description: "Member growth, loan book yield and savings-funded lending.", customerLabel: "Active members", priceLabel: "Annual income / member", revenueStreams: ["Loan interest", "Loan fees", "Membership fees", "Investment income", "Digital transaction fees"], costDrivers: ["Interest on savings", "Credit losses", "Staff", "Core banking systems", "Branch operations"], guidance: "Link income to the average performing loan book, not only member count. Include portfolio-at-risk, provisions and liquidity reserves.", benchmark: { grossMargin: [45, 70], growth: [12, 35] }, defaults: d({ startingCustomers: 1800, annualCustomerGrowth: 24, annualPrice: 95, churnRate: 4, grossMargin: 58, annualPayroll: 90000, annualOverheads: 52000, capex: 65000, fundingRequired: 600000, debtShare: 65, receivableDays: 60, payableDays: 15 }) },
  { name: "Clinics", description: "Patient volumes, clinical services, diagnostics and pharmacy.", customerLabel: "Annual patient visits", priceLabel: "Average revenue / visit", revenueStreams: ["Consultations", "Laboratory", "Pharmacy", "Procedures", "Corporate and insurance contracts"], costDrivers: ["Clinical staff", "Medicines", "Lab reagents", "Medical consumables", "Equipment maintenance"], guidance: "Separate patient visits from unique patients and model service mix. Include insurer collection delays and medicine inventory.", benchmark: { grossMargin: [40, 65], growth: [12, 30] }, defaults: d({ startingCustomers: 7200, annualCustomerGrowth: 22, annualPrice: 42, churnRate: 3, grossMargin: 57, annualPayroll: 125000, annualOverheads: 62000, capex: 160000, fundingRequired: 420000, debtShare: 45, receivableDays: 55, payableDays: 30 }) },
  { name: "Retail", description: "Store traffic, basket size, inventory turns and channel expansion.", customerLabel: "Annual transactions", priceLabel: "Average basket value", revenueStreams: ["Store sales", "Wholesale", "Online sales", "Delivery fees", "Private-label products"], costDrivers: ["Merchandise purchases", "Store payroll", "Rent", "Payment fees", "Shrinkage and delivery"], guidance: "Drive sales from transactions and average basket size. Monitor stock turns, markdowns, shrinkage and supplier terms.", benchmark: { grossMargin: [18, 40], growth: [10, 35] }, defaults: d({ startingCustomers: 24000, annualCustomerGrowth: 20, annualPrice: 18, churnRate: 1, grossMargin: 31, annualPayroll: 65000, annualOverheads: 72000, capex: 90000, fundingRequired: 280000, debtShare: 45, receivableDays: 5, payableDays: 35 }) },
  { name: "Real Estate", description: "Property sales, rental occupancy and development phasing.", customerLabel: "Saleable / rentable units", priceLabel: "Annual revenue / unit", revenueStreams: ["Unit sales", "Rental income", "Service charges", "Property management", "Parking and amenities"], costDrivers: ["Land", "Construction", "Professional fees", "Sales commissions", "Property operations"], guidance: "Model projects in phases with construction drawdowns and sales collections. Keep rental assets separate from units held for sale.", benchmark: { grossMargin: [25, 50], growth: [8, 25] }, defaults: d({ startingCustomers: 48, annualCustomerGrowth: 15, annualPrice: 18000, churnRate: 5, grossMargin: 42, annualPayroll: 95000, annualOverheads: 75000, capex: 900000, fundingRequired: 1500000, debtShare: 60, receivableDays: 75, payableDays: 45 }) },
];

export const getFinancialModelTemplate = (name: string) => FINANCIAL_MODEL_TEMPLATES.find(t => t.name === name) ?? FINANCIAL_MODEL_TEMPLATES[0];
