import * as XLSX from "xlsx";
import type { FinancialModelInputs } from "@/lib/financialModellingEngine";
import type { LoanScheduleYear, StatementYear } from "@/lib/phase1FinancialEngine";
import { hasConfiguredProjects, type ModelProject } from "@/lib/projectPortfolioEngine";
import type { CountryTaxProfile } from "@/lib/countryTaxPacks";
import type { CapitalAsset } from "@/lib/capitalAssetSchedule";

type PersonnelRole={jobTitle:string;lowerSalary:number;upperSalary:number;annualSalaryGrowth:number;positions:Record<number,number>};
type FundingUse={name:string;value:number};
type MonthlyActuals=Record<string,{revenue:number;costOfSales:number;operatingExpenses:number}>;

export function downloadFinancialModelWorkbook(args: { company: string; currency: string; inputs: FinancialModelInputs; statements: StatementYear[]; loan: LoanScheduleYear[]; projects:ModelProject[]; personnelRoles:PersonnelRole[]; capitalAssets:CapitalAsset[]; uses:FundingUse[]; taxProfile:CountryTaxProfile;forecastStartYear:number;monthlyActuals:MonthlyActuals }) {
  const { company, currency, inputs, statements, loan, projects, personnelRoles, capitalAssets, uses, taxProfile,forecastStartYear,monthlyActuals } = args;
  const workbook = XLSX.utils.book_new();
  const years = statements.map(row => `Year ${row.year}`);
  const add = (name: string, rows: (string | number | Date)[][]) => { const sheet = XLSX.utils.aoa_to_sheet(rows); XLSX.utils.book_append_sheet(workbook, sheet, name); return sheet; };
  const formula = (sheet: XLSX.WorkSheet, row: number, col: number, f: string) => { const address=XLSX.utils.encode_cell({r:row,c:col}); sheet[address] = { ...(sheet[address] ?? { t:"n", v:0 }), f }; };
  const styleWidths = (sheet: XLSX.WorkSheet, count: number) => { sheet["!cols"]=[{wch:28},...Array.from({length:count},()=>({wch:16}))]; };

  add("Cover", [[company], ["Formula-driven financial model"], ["Currency", currency], ["Generated", new Date().toLocaleDateString()], ["Model flow", "Assumptions → Projects / Project Drivers / Personnel → Project Forecast → financial statements → ratios and checks"], ["Instructions", "Edit input cells on Assumptions, Projects, Project Drivers, Personnel, Funding Uses and Tax & Economics. Formula sheets recalculate in Excel."]]);
  const assumptions = add("Assumptions", [["Assumption","Value","Unit"], ["Projection period",inputs.years,"years"], ["Starting customers",inputs.startingCustomers,"customers / units"], ["Annual growth",inputs.annualCustomerGrowth,"%"], ["Annual price",inputs.annualPrice,currency], ["Gross margin",inputs.grossMargin,"%"], ["Payroll",inputs.annualPayroll,currency], ["Overheads",inputs.annualOverheads,currency], ["Capex",inputs.capex,currency], ["Funding required",inputs.fundingRequired,currency], ["Debt share",inputs.debtShare,"%"], ["Interest rate",inputs.interestRate,"%"], ["Loan term",inputs.loanTerm,"years"], ["Repayment method",inputs.repaymentMethod ?? "equal-principal",""], ["Principal grace period",inputs.gracePeriod ?? 0,"years"], ["Balloon at maturity",inputs.balloonPercent ?? 0,"%"], ["Tax rate",inputs.taxRate,"%"], ["Receivable days",inputs.receivableDays,"days"], ["Inventory days",inputs.inventoryDays ?? 0,"days"], ["Payable days",inputs.payableDays,"days"], ["Operating-cost inflation",inputs.opexInflation,"%"]]);
  assumptions["!cols"]=[{wch:28},{wch:18},{wch:18}];
  const projectSheet=add("Projects",[["Project ID","Project","Business type","Enabled","Start year","Starting units / new cohort","Unit / cohort growth %","Revenue / unit","Base direct cost %","Annual fixed costs","Subscription churn %","Import duty / freight %","Warranty %","Replacement / returns %","Government award probability %","Government retention %","Government payment delay days","Receivable days","Inventory days","Payable days","Procurement lead-time days"],...projects.map(project=>[project.id,project.name,project.businessType,project.enabled?1:0,project.startYear,project.startingUnits,project.annualGrowth,project.revenuePerUnit,project.directCostRate,project.annualFixedCosts,project.subscriptionChurnRate??0,project.importDutyRate??0,project.warrantyRate??0,project.replacementRate??0,project.governmentContractProbability??100,project.governmentRetentionRate??0,project.governmentPaymentDelayDays??0,project.receivableDays??0,project.inventoryDays??0,project.payableDays??0,project.procurementLeadTimeDays??0])]);
  projectSheet["!cols"]=[{wch:22},{wch:28},{wch:20},{wch:10},{wch:11},{wch:22},{wch:20},{wch:18},{wch:18},{wch:20},{wch:20},{wch:22},{wch:14},{wch:22},{wch:28},{wch:22},{wch:28},{wch:16},{wch:16},{wch:16},{wch:26}];
  const driverRows=projects.flatMap(project=>[...(project.revenueDrivers??[]).map(driver=>({project,driver,kind:"Revenue"})),...(project.costDrivers??[]).map(driver=>({project,driver,kind:"Cost"}))]);
  const driverSheet=add("Project Drivers",[["Driver ID","Project ID","Project","Kind","Driver","Frequency","Base quantity","Quantity growth %","Unit amount","Unit growth %","Start year","Enabled",...years],...driverRows.map(({project,driver,kind})=>[driver.id,project.id,project.name,kind,driver.name,driver.frequency??"annual",driver.quantity??0,driver.quantityGrowth??0,driver.unitAmount??driver.amount??0,driver.unitAmountGrowth??0,project.startYear,project.enabled?1:0,...statements.map(()=>0)])]);
  const driverLast=Math.max(2,driverRows.length+1);
  driverRows.forEach(({driver},index)=>statements.forEach((_,yearIndex)=>{const r=index+1,c=12+yearIndex,L=XLSX.utils.encode_col(c),year=yearIndex+1,multiplier=driver.frequency==="monthly"?12:driver.frequency==="quarterly"?4:1;const override=driver.yearlyOverrides?.[year];if(override?.quantity!=null||override?.unitAmount!=null){const q=override.quantity??driver.quantity??0,u=override.unitAmount??driver.unitAmount??driver.amount??0;formula(driverSheet,r,c,`IF($L${r+1}=0,0,${q}*${u}*${multiplier})`);}else formula(driverSheet,r,c,`IF(OR($L${r+1}=0,${year}<$K${r+1}),0,$G${r+1}*(1+$H${r+1}/100)^(${year}-$K${r+1})*$I${r+1}*(1+$J${r+1}/100)^(${year}-$K${r+1})*${multiplier})`);}));
  driverSheet["!cols"]=[{wch:22},{wch:22},{wch:26},{wch:11},{wch:30},{wch:12},{wch:15},{wch:17},{wch:16},{wch:16},{wch:11},{wch:10},...years.map(()=>({wch:16}))];
  const personnel=add("Personnel",[["Role","Lower annual salary","Upper annual salary","Salary growth %",...statements.flatMap(row=>[`Year ${row.year} headcount`,`Year ${row.year} cost`])],...personnelRoles.map(role=>[role.jobTitle,role.lowerSalary,role.upperSalary,role.annualSalaryGrowth,...statements.flatMap(row=>[role.positions[row.year]??0,0])]),["Total personnel cost","","","",...statements.flatMap(()=>["",0])]]);
  const personnelTotalRow=personnelRoles.length+2;
  personnelRoles.forEach((_,index)=>statements.forEach((__,yearIndex)=>{const row=index+2,costCol=5+yearIndex*2;formula(personnel,row-1,costCol,`(($B${row}+$C${row})/2)*(1+$D${row}/100)^${yearIndex}*${XLSX.utils.encode_col(costCol-1)}${row}`);}));
  statements.forEach((_,yearIndex)=>{const costCol=5+yearIndex*2,L=XLSX.utils.encode_col(costCol);formula(personnel,personnelTotalRow-1,costCol,personnelRoles.length?`SUM(${L}2:${L}${personnelRoles.length+1})`:`0`);});
  personnel["!cols"]=[{wch:28},{wch:20},{wch:20},{wch:16},...years.flatMap(()=>[{wch:14},{wch:18}])];
  const funding=add("Funding Uses",[["Use of funds","Amount"],...uses.map(item=>[item.name,item.value]),["Total allocated",0],["Funding required",0],["Unallocated / (overallocated)",0]]);
  const fundingTotalRow=uses.length+2;formula(funding,fundingTotalRow-1,1,`SUM(B2:B${uses.length+1})`);formula(funding,fundingTotalRow,1,`'Assumptions'!$B$10`);formula(funding,fundingTotalRow+1,1,`B${fundingTotalRow+1}-B${fundingTotalRow}`);funding["!cols"]=[{wch:30},{wch:20}];
  const tax=add("Tax & Economics",[["Assumption","Value","As of / source"],["Country",taxProfile.countryName,taxProfile.effectiveDate],["Corporate income tax %",taxProfile.corporateIncomeTaxRate,taxProfile.sourceUrl],["VAT %",taxProfile.vatRate,taxProfile.sourceUrl],["Withholding modelling rate %",taxProfile.withholdingTaxRate,taxProfile.sourceUrl],["Capital allowance %",taxProfile.capitalAllowanceRate,taxProfile.sourceUrl],["Inflation %",taxProfile.inflationRate,taxProfile.sourceUrl],["Planning note",taxProfile.note,""]]);tax["!cols"]=[{wch:32},{wch:20},{wch:55}];
  formula(assumptions,16,1,`'Tax & Economics'!B3`);formula(assumptions,20,1,`'Tax & Economics'!B7`);
  const capex=add("Capex Schedule",[["Asset ID","Asset","Class","Purchase year","Cost","Useful life","Residual value","Maintenance %","Capital allowance %",...years.flatMap(year=>[`${year} purchases`,`${year} depreciation`,`${year} maintenance`,`${year} allowance`,`${year} closing NBV`])],...capitalAssets.map(asset=>[asset.id,asset.name,asset.assetClass,asset.purchaseYear,asset.cost,asset.usefulLifeYears,asset.residualValue,asset.maintenanceRate,asset.capitalAllowanceRate,...statements.flatMap(()=>[0,0,0,0,0])]),["","TOTAL","","","","","","","",...statements.flatMap(()=>[0,0,0,0,0])]]);
  const capexTotalRow=capitalAssets.length+2;capitalAssets.forEach((_,assetIndex)=>statements.forEach((__,yearIndex)=>{const row=assetIndex+2,year=yearIndex+1,startCol=9+yearIndex*5,letters=Array.from({length:5},(_,offset)=>XLSX.utils.encode_col(startCol+offset));formula(capex,row-1,startCol,`IF($D${row}=${year},$E${row},0)`);formula(capex,row-1,startCol+1,`IF(AND(${year}>=$D${row},${year}<$D${row}+$F${row}),MAX(0,$E${row}-$G${row})/MAX(1,$F${row}),0)`);formula(capex,row-1,startCol+2,`IF(${year}>=$D${row},$E${row}*$H${row}/100,0)`);formula(capex,row-1,startCol+3,`IF(AND(${year}>=$D${row},${year}<$D${row}+$F${row}),$E${row}*$I${row}/100,0)`);formula(capex,row-1,startCol+4,`IF(${year}<$D${row},0,MAX($G${row},$E${row}-MAX(0,${year}-$D${row}+1)*MAX(0,$E${row}-$G${row})/MAX(1,$F${row})))`);void letters;}));statements.forEach((_,yearIndex)=>{const startCol=9+yearIndex*5;for(let offset=0;offset<5;offset++){const L=XLSX.utils.encode_col(startCol+offset);formula(capex,capexTotalRow-1,startCol+offset,capitalAssets.length?`SUM(${L}2:${L}${capitalAssets.length+1})`:`0`);}});capex["!cols"]=[{wch:20},{wch:25},{wch:20},{wch:14},{wch:18},{wch:14},{wch:18},{wch:16},{wch:20},...years.flatMap(()=>Array.from({length:5},()=>({wch:16})))];
  const configured=hasConfiguredProjects(projects);
  const projectForecastRows=projects.flatMap(project=>[[project.id,project.name,"Revenue",...statements.map(()=>0)],[project.id,project.name,"Direct costs",...statements.map(()=>0)],[project.id,project.name,"Fixed costs",...statements.map(()=>0)],[project.id,project.name,"EBITDA",...statements.map(()=>0)]]);
  const projectForecast=add("Project Forecast",[["Project ID","Project","Metric",...years],...projectForecastRows,["","Consolidated","Revenue",...statements.map(()=>0)],["","Consolidated","Direct costs",...statements.map(()=>0)],["","Consolidated","Fixed costs",...statements.map(()=>0)],["","Consolidated","EBITDA",...statements.map(()=>0)]]);
  projects.forEach((project,projectIndex)=>statements.forEach((__,yearIndex)=>{const base=projectIndex*4+2,c=3+yearIndex,L=XLSX.utils.encode_col(c),driverCol=XLSX.utils.encode_col(12+yearIndex),year=yearIndex+1,projectRow=projectIndex+2,activeYears=year-project.startYear;const standardUnits=`'Projects'!$F${projectRow}*(1+'Projects'!$G${projectRow}/100)^(${year}-'Projects'!$E${projectRow})`;const cohortTerms=activeYears<0?"0":Array.from({length:activeYears+1},(_,cohort)=>`'Projects'!$F${projectRow}*(1+'Projects'!$G${projectRow}/100)^${cohort}*(1-'Projects'!$K${projectRow}/100)^${activeYears-cohort}`).join("+");const units=project.businessType==="subscription"?`(${cohortTerms})`:standardUnits;const probability=project.businessType==="government"?`'Projects'!$O${projectRow}/100`:"1";formula(projectForecast,base-1,c,`(SUMIFS('Project Drivers'!$${driverCol}$2:$${driverCol}$${driverLast},'Project Drivers'!$B$2:$B$${driverLast},$A${base},'Project Drivers'!$D$2:$D$${driverLast},"Revenue")+IF(OR('Projects'!$D${projectRow}=0,${year}<'Projects'!$E${projectRow}),0,${units}*'Projects'!$H${projectRow}))*${probability}`);formula(projectForecast,base,c,`${L}${base}*('Projects'!$I${projectRow}+'Projects'!$L${projectRow}+'Projects'!$M${projectRow}+'Projects'!$N${projectRow})/100`);formula(projectForecast,base+1,c,`IF('Projects'!$D${projectRow}=0,0,'Projects'!$J${projectRow})+SUMIFS('Project Drivers'!$${driverCol}$2:$${driverCol}$${driverLast},'Project Drivers'!$B$2:$B$${driverLast},$A${base},'Project Drivers'!$D$2:$D$${driverLast},"Cost")*${probability}`);formula(projectForecast,base+2,c,`${L}${base}-${L}${base+1}-${L}${base+2}`);}));
  const consolidatedStart=projects.length*4+2;statements.forEach((_,yearIndex)=>{const c=3+yearIndex,L=XLSX.utils.encode_col(c);[0,1,2,3].forEach(metric=>{const rows=projects.map((__,index)=>index*4+2+metric);formula(projectForecast,consolidatedStart-1+metric,c,rows.length?rows.map(row=>`${L}${row}`).join("+"):"0");});});styleWidths(projectForecast,statements.length+2);
  const workingRows=projects.flatMap(project=>[[project.id,project.name,"Receivables",...statements.map(()=>0)],[project.id,project.name,"Inventory",...statements.map(()=>0)],[project.id,project.name,"Payables",...statements.map(()=>0)]]);
  const workingCapital=add("Project Working Capital",[["Project ID","Project","Metric",...years],...workingRows,["","Consolidated","Receivables",...statements.map(()=>0)],["","Consolidated","Inventory",...statements.map(()=>0)],["","Consolidated","Payables",...statements.map(()=>0)]]);
  projects.forEach((project,index)=>statements.forEach((_,yearIndex)=>{const row=index*3+2,c=3+yearIndex,L=XLSX.utils.encode_col(c),forecastRow=index*4+2,projectRow=index+2,forecastCol=XLSX.utils.encode_col(c);formula(workingCapital,row-1,c,`'Project Forecast'!${forecastCol}${forecastRow}*('Projects'!$R${projectRow}+IF('Projects'!$C${projectRow}="government",'Projects'!$Q${projectRow},0))/365+'Project Forecast'!${forecastCol}${forecastRow}*IF('Projects'!$C${projectRow}="government",'Projects'!$P${projectRow}/100,0)`);formula(workingCapital,row,c,`'Project Forecast'!${forecastCol}${forecastRow+1}*('Projects'!$S${projectRow}+IF('Projects'!$C${projectRow}="hardware",'Projects'!$U${projectRow},0))/365`);formula(workingCapital,row+1,c,`'Project Forecast'!${forecastCol}${forecastRow+1}*'Projects'!$T${projectRow}/365`);}));
  const workingCapitalStart=projects.length*3+2;statements.forEach((_,yearIndex)=>{const c=3+yearIndex,L=XLSX.utils.encode_col(c);[0,1,2].forEach(metric=>{const rows=projects.map((__,index)=>index*3+2+metric);formula(workingCapital,workingCapitalStart-1+metric,c,rows.length?rows.map(row=>`${L}${row}`).join("+"):"0");});});styleWidths(workingCapital,statements.length+2);
  const forecast = add("Model Forecast", [[`Operating forecast (${currency})`,...years], ["Revenue",...statements.map(r=>r.revenue)], ["Cost of sales",...statements.map(r=>r.costOfSales)], ["Operating expenses",...statements.map(r=>r.operatingExpenses)], ["Depreciation",...statements.map(r=>r.depreciation)]]);
  statements.forEach((_,yearIndex)=>{const c=yearIndex+1,L=XLSX.utils.encode_col(c),PF=XLSX.utils.encode_col(yearIndex+3),personnelCost=XLSX.utils.encode_col(5+yearIndex*2),capexMaintenance=XLSX.utils.encode_col(11+yearIndex*5),capexDepreciation=XLSX.utils.encode_col(10+yearIndex*5);formula(forecast,1,c,configured?`'Project Forecast'!${PF}${consolidatedStart}`:`Assumptions!$B$3*Assumptions!$B$5*(1+Assumptions!$B$4/100)^${yearIndex}`);formula(forecast,2,c,configured?`'Project Forecast'!${PF}${consolidatedStart+1}`:`${L}2*(1-Assumptions!$B$6/100)`);formula(forecast,3,c,(configured?`'Project Forecast'!${PF}${consolidatedStart+2}+'Personnel'!${personnelCost}${personnelTotalRow}+Assumptions!$B$8*(1+Assumptions!$B$21/100)^${yearIndex}`:`Assumptions!$B$7*(1+Assumptions!$B$21/100)^${yearIndex}+Assumptions!$B$8*(1+Assumptions!$B$21/100)^${yearIndex}`)+(capitalAssets.length?`+'Capex Schedule'!${capexMaintenance}${capexTotalRow}`:""));formula(forecast,4,c,capitalAssets.length?`'Capex Schedule'!${capexDepreciation}${capexTotalRow}`:`Assumptions!$B$9/MAX(Assumptions!$B$2,5)`);});
  styleWidths(forecast, statements.length);
  const loanSheet = add("Loan Schedule", [[`Loan schedule (${currency})`,...years], ["Opening balance",...loan.map(r=>r.openingBalance)], ["Principal",...loan.map(r=>r.principal)], ["Interest",...loan.map(r=>r.interest)], ["Debt service",...loan.map(r=>r.debtService)], ["Closing balance",...loan.map(r=>r.closingBalance)]]);
  statements.forEach((_,i)=>{const c=i+1,L=XLSX.utils.encode_col(c),P=i?XLSX.utils.encode_col(c-1):"",year=i+1;formula(loanSheet,1,c,i===0?`Assumptions!$B$10*Assumptions!$B$11/100`:`${P}6`);const equalPrincipal=`(Assumptions!$B$10*Assumptions!$B$11/100)/MAX(1,Assumptions!$B$13-Assumptions!$B$15)`;const annuity=`MAX(0,-PMT(Assumptions!$B$12/100,MAX(1,Assumptions!$B$13-Assumptions!$B$15),Assumptions!$B$10*Assumptions!$B$11/100)-${L}4)`;const principal=`IF(OR(${year}<=Assumptions!$B$15,${year}>Assumptions!$B$13),0,IF(Assumptions!$B$14="interest-only",IF(${year}=Assumptions!$B$13,${L}2,0),IF(Assumptions!$B$14="annuity",${annuity},IF(Assumptions!$B$14="balloon",${equalPrincipal}*(1-Assumptions!$B$16/100)+IF(${year}=Assumptions!$B$13,Assumptions!$B$10*Assumptions!$B$11/100*Assumptions!$B$16/100,0),${equalPrincipal}))))`;formula(loanSheet,2,c,`MIN(${L}2,${principal})`);formula(loanSheet,3,c,`${L}2*Assumptions!$B$12/100`);formula(loanSheet,4,c,`${L}3+${L}4`);formula(loanSheet,5,c,`MAX(0,${L}2-${L}3)`);});
  styleWidths(loanSheet, statements.length);

  const income = add("Income Statement", [[`Income Statement (${currency})`,...years], ["Revenue",...statements.map(r=>r.revenue)], ["Cost of sales",...statements.map(r=>r.costOfSales)], ["Gross profit",...statements.map(r=>r.grossProfit)], ["Operating expenses",...statements.map(r=>r.operatingExpenses)], ["EBITDA",...statements.map(r=>r.ebitda)], ["Depreciation",...statements.map(r=>r.depreciation)], ["EBIT",...statements.map(r=>r.ebit)], ["Interest",...statements.map(r=>r.interest)], ["Tax",...statements.map(r=>r.tax)], ["Net profit",...statements.map(r=>r.netProfit)]]);
  statements.forEach((_,i)=>{ const c=i+1,L=XLSX.utils.encode_col(c); formula(income,1,c,`'Model Forecast'!${L}2`); formula(income,2,c,`'Model Forecast'!${L}3`); formula(income,3,c,`${L}2-${L}3`); formula(income,4,c,`'Model Forecast'!${L}4`); formula(income,5,c,`${L}4-${L}5`); formula(income,6,c,`'Model Forecast'!${L}5`); formula(income,7,c,`${L}6-${L}7`); formula(income,8,c,`'Loan Schedule'!${L}4`); formula(income,9,c,`MAX(0,(${L}8-${L}9)*Assumptions!$B$17/100)`); formula(income,10,c,`${L}8-${L}9-${L}10`); }); styleWidths(income,statements.length);

  const cashFlow = add("Cash Flow", [[`Cash Flow (${currency})`,...years], ["Operating cash flow",...statements.map(r=>r.operatingCashFlow)], ["Investing cash flow",...statements.map(r=>r.investingCashFlow)], ["Financing cash flow",...statements.map(r=>r.financingCashFlow)], ["Net cash movement",...statements.map(r=>r.netCashMovement)], ["Opening cash",...statements.map(r=>r.openingCash)], ["Closing cash",...statements.map(r=>r.closingCash)]]);
  statements.forEach((_,i)=>{const c=i+1,L=XLSX.utils.encode_col(c),P=i?XLSX.utils.encode_col(c-1):"",W=XLSX.utils.encode_col(i+3),PW=i?XLSX.utils.encode_col(i+2):"",capexPurchases=XLSX.utils.encode_col(9+i*5); const wc=configured?`('Project Working Capital'!${W}${workingCapitalStart}+'Project Working Capital'!${W}${workingCapitalStart+1}-'Project Working Capital'!${W}${workingCapitalStart+2})`:`('Income Statement'!${L}2*Assumptions!$B$18/365+'Income Statement'!${L}3*Assumptions!$B$19/365-'Income Statement'!${L}3*Assumptions!$B$20/365)`; const prev=i?(configured?`-('Project Working Capital'!${PW}${workingCapitalStart}+'Project Working Capital'!${PW}${workingCapitalStart+1}-'Project Working Capital'!${PW}${workingCapitalStart+2})`:`-('Income Statement'!${P}2*Assumptions!$B$18/365+'Income Statement'!${P}3*Assumptions!$B$19/365-'Income Statement'!${P}3*Assumptions!$B$20/365)`):""; formula(cashFlow,1,c,`'Income Statement'!${L}11+'Income Statement'!${L}7-${wc}${prev}`); formula(cashFlow,2,c,capitalAssets.length?`-'Capex Schedule'!${capexPurchases}${capexTotalRow}`:i===0?`-Assumptions!$B$9`:"0"); formula(cashFlow,3,c,i===0?`Assumptions!$B$10-'Loan Schedule'!${L}3`:`-'Loan Schedule'!${L}3`); formula(cashFlow,4,c,`${L}2+${L}3+${L}4`); formula(cashFlow,5,c,i===0?"0":`${P}7`); formula(cashFlow,6,c,`${L}6+${L}5`);}); styleWidths(cashFlow,statements.length);

  const balance = add("Balance Sheet", [[`Balance Sheet (${currency})`,...years], ["Cash",...statements.map(r=>r.cash)], ["Receivables",...statements.map(r=>r.receivables)], ["Inventory",...statements.map(r=>r.inventory)], ["Net PPE",...statements.map(r=>r.netPpe)], ["Total assets",...statements.map(r=>r.totalAssets)], ["Payables",...statements.map(r=>r.payables)], ["Debt",...statements.map(r=>r.debt)], ["Total liabilities",...statements.map(r=>r.totalLiabilities)], ["Contributed capital",...statements.map(r=>r.contributedCapital)], ["Retained earnings",...statements.map(r=>r.retainedEarnings)], ["Total equity",...statements.map(r=>r.equity)], ["Liabilities and equity",...statements.map(r=>r.totalLiabilitiesAndEquity)], ["Balance check",...statements.map(r=>r.balanceCheck)]]);
  statements.forEach((_,i)=>{const c=i+1,L=XLSX.utils.encode_col(c),P=i?XLSX.utils.encode_col(c-1):"",W=XLSX.utils.encode_col(i+3),capexNbv=XLSX.utils.encode_col(13+i*5); formula(balance,1,c,`'Cash Flow'!${L}7`); formula(balance,2,c,configured?`'Project Working Capital'!${W}${workingCapitalStart}`:`'Income Statement'!${L}2*Assumptions!$B$18/365`); formula(balance,3,c,configured?`'Project Working Capital'!${W}${workingCapitalStart+1}`:`'Income Statement'!${L}3*Assumptions!$B$19/365`); formula(balance,4,c,capitalAssets.length?`'Capex Schedule'!${capexNbv}${capexTotalRow}`:`MAX(0,Assumptions!$B$9-'Income Statement'!${L}7*${i+1})`); formula(balance,5,c,`SUM(${L}2:${L}5)`); formula(balance,6,c,configured?`'Project Working Capital'!${W}${workingCapitalStart+2}`:`'Income Statement'!${L}3*Assumptions!$B$20/365`); formula(balance,7,c,`'Loan Schedule'!${L}6`); formula(balance,8,c,`${L}7+${L}8`); formula(balance,9,c,`Assumptions!$B$10*(1-Assumptions!$B$11/100)`); formula(balance,10,c,i===0?`'Income Statement'!${L}11`:`${P}11+'Income Statement'!${L}11`); formula(balance,11,c,`${L}10+${L}11`); formula(balance,12,c,`${L}9+${L}12`); formula(balance,13,c,`${L}6-${L}13`);}); styleWidths(balance,statements.length);

  const ratioLines: [string,keyof StatementYear][] = [["Current ratio","currentRatio"],["Quick ratio","quickRatio"],["Cash ratio","cashRatio"],["Gross margin","grossMargin"],["EBITDA margin","ebitdaMargin"],["Operating margin","operatingMargin"],["Net margin","netMargin"],["Return on assets","returnOnAssets"],["Return on equity","returnOnEquity"],["ROCE","returnOnCapitalEmployed"],["Asset turnover","assetTurnover"],["Debt / equity","debtToEquity"],["Debt / EBITDA","debtToEbitda"],["Debt ratio","debtRatio"],["Gearing","gearing"],["Interest cover","interestCover"],["DSCR","dscr"]];
  const ratios=add("Financial Ratios",[["Ratio",...years],...ratioLines.map(([label,key])=>[label,...statements.map(r=>Number(r[key]))])]);
  statements.forEach((_,i)=>{const c=i+1,L=XLSX.utils.encode_col(c); const formulas=[`('Balance Sheet'!${L}2+'Balance Sheet'!${L}3+'Balance Sheet'!${L}4)/('Balance Sheet'!${L}7+'Loan Schedule'!${L}3)`,`('Balance Sheet'!${L}2+'Balance Sheet'!${L}3)/('Balance Sheet'!${L}7+'Loan Schedule'!${L}3)`,`'Balance Sheet'!${L}2/('Balance Sheet'!${L}7+'Loan Schedule'!${L}3)`,`'Income Statement'!${L}4/'Income Statement'!${L}2`,`'Income Statement'!${L}6/'Income Statement'!${L}2`,`'Income Statement'!${L}8/'Income Statement'!${L}2`,`'Income Statement'!${L}11/'Income Statement'!${L}2`,`'Income Statement'!${L}11/'Balance Sheet'!${L}6`,`'Income Statement'!${L}11/'Balance Sheet'!${L}12`,`'Income Statement'!${L}8/('Balance Sheet'!${L}6-'Balance Sheet'!${L}7-'Loan Schedule'!${L}3)`,`'Income Statement'!${L}2/'Balance Sheet'!${L}6`,`'Balance Sheet'!${L}8/'Balance Sheet'!${L}12`,`'Balance Sheet'!${L}8/'Income Statement'!${L}6`,`'Balance Sheet'!${L}8/'Balance Sheet'!${L}6`,`'Balance Sheet'!${L}8/('Balance Sheet'!${L}8+'Balance Sheet'!${L}12)`,`'Income Statement'!${L}8/'Income Statement'!${L}9`,`('Income Statement'!${L}6-'Income Statement'!${L}10)/'Loan Schedule'!${L}5`]; formulas.forEach((f,r)=>formula(ratios,r+1,c,`IFERROR(${f},0)`));}); styleWidths(ratios,statements.length);

  const monthlyRows=statements.flatMap((statement,yearIndex)=>Array.from({length:12},(_,monthIndex)=>{const calendarYear=forecastStartYear+yearIndex,key=`${calendarYear}-${String(monthIndex+1).padStart(2,"0")}`,actual=monthlyActuals[key]??{revenue:0,costOfSales:0,operatingExpenses:0};return [new Date(calendarYear,monthIndex,1),statement.year,0,actual.revenue,0,0,actual.costOfSales,0,0,actual.operatingExpenses,0];}));
  const monthly=add("Monthly Actual vs Forecast",[["Month","Model year","Revenue forecast","Revenue actual","Revenue variance","Cost forecast","Cost actual","Cost variance","Opex forecast","Opex actual","Opex variance"],...monthlyRows]);
  monthlyRows.forEach((_,index)=>{const row=index+2,yearIndex=Math.floor(index/12),annualCol=XLSX.utils.encode_col(yearIndex+1);formula(monthly,row-1,2,`'Income Statement'!${annualCol}2/12`);formula(monthly,row-1,4,`D${row}-C${row}`);formula(monthly,row-1,5,`'Income Statement'!${annualCol}3/12`);formula(monthly,row-1,7,`G${row}-F${row}`);formula(monthly,row-1,8,`'Income Statement'!${annualCol}5/12`);formula(monthly,row-1,10,`J${row}-I${row}`);});monthly["!cols"]=[{wch:14},{wch:12},...Array.from({length:9},()=>({wch:18}))];monthly["!autofilter"]={ref:`A1:K${monthlyRows.length+1}`};

  const checkRows=statements.map((row,index)=>[`Balance sheet Year ${row.year}`,0,0,0,1,"",`Review Balance Sheet!${XLSX.utils.encode_col(index+1)}14`]);
  checkRows.push(["Funding uses reconcile",0,0,0,1,"","Review Funding Uses allocation"],["Debt repays by term",0,0,0,1,"","Review financing terms and forecast horizon"]);
  const checks=add("Checks",[["MODEL STATUS",""],["Check","Actual","Expected","Difference","Tolerance","Status","Where to fix"],...checkRows]);
  statements.forEach((_,index)=>{const row=index+3,L=XLSX.utils.encode_col(index+1);formula(checks,row-1,1,`'Balance Sheet'!${L}14`);formula(checks,row-1,3,`B${row}-C${row}`);formula(checks,row-1,5,`IF(ABS(D${row})<=E${row},"OK","FAIL")`);});
  const fundingCheckRow=statements.length+3;formula(checks,fundingCheckRow-1,1,`'Funding Uses'!B${fundingTotalRow+2}`);formula(checks,fundingCheckRow-1,3,`B${fundingCheckRow}-C${fundingCheckRow}`);formula(checks,fundingCheckRow-1,5,`IF(ABS(D${fundingCheckRow})<=E${fundingCheckRow},"OK","FAIL")`);
  const debtCheckRow=fundingCheckRow+1,lastLoanCol=XLSX.utils.encode_col(statements.length);formula(checks,debtCheckRow-1,1,`'Loan Schedule'!${lastLoanCol}6`);formula(checks,debtCheckRow-1,3,`B${debtCheckRow}-C${debtCheckRow}`);formula(checks,debtCheckRow-1,5,`IF(OR(Assumptions!$B$13>Assumptions!$B$2,ABS(D${debtCheckRow})<=E${debtCheckRow}),"OK","FAIL")`);formula(checks,0,1,`IF(COUNTIF(F3:F${debtCheckRow},"FAIL")=0,"PASS","FAIL")`);checks["!cols"]=[{wch:30},{wch:18},{wch:18},{wch:18},{wch:14},{wch:12},{wch:40}];
  add("Sources & Audit",[["Item","Value","Units","As of","Source","Reference","Notes"],["Country tax profile",taxProfile.countryName,"",taxProfile.effectiveDate,taxProfile.sourceLabel,taxProfile.sourceUrl,taxProfile.note],["Operating assumptions","See Assumptions","",new Date().toISOString().slice(0,10),"Management assumptions","Assumptions","Confirm inputs before external use"],["Project drivers","See Project Drivers","",new Date().toISOString().slice(0,10),"Management / imported workbook","Project Drivers","Formula-driven forecast inputs"]]);

  (workbook as XLSX.WorkBook & { Workbook?:{ CalcPr?:Record<string,unknown> } }).Workbook={CalcPr:{calcMode:"auto",fullCalcOnLoad:true,forceFullCalc:true}};
  XLSX.writeFile(workbook, `${company.replace(/\W+/g,"-").toLowerCase() || "boat"}-financial-model.xlsx`);
}
