import { jsPDF } from "jspdf";
import { APP_SHORT_NAME } from "@/constants/branding";

export type PayslipDetail = {
  organizationName: string;
  organizationAddress?: string | null;
  organizationLogoUrl?: string | null;
  periodLabel: string;
  periodStart: string;
  periodEnd: string;
  staffName: string;
  employeeCode?: string | null;
  fullGross?: number;
  daysAbsent?: number;
  absentDeduction?: number;
  grossPay: number;
  paye: number;
  nssfEmployee: number;
  nssfEmployer: number;
  loanDeduction: number;
  netPay: number;
};

const money = (value: number) => Number(value).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });

async function loadLogo(url?: string | null): Promise<string | null> {
  if (!url) return null;
  try {
    const response = await fetch(url);
    if (!response.ok) return null;
    const blob = await response.blob();
    return await new Promise((resolve) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => resolve(null); reader.readAsDataURL(blob); });
  } catch { return null; }
}

function drawRow(doc: jsPDF, label: string, value: number, y: number, x = 18, width = 78): number {
  doc.setFont("helvetica", "normal"); doc.setFontSize(9); doc.setTextColor(75, 85, 99); doc.text(label, x, y);
  doc.setFont("helvetica", "bold"); doc.setTextColor(15, 23, 42); doc.text(money(value), x + width, y, { align: "right" });
  return y + 7;
}

function drawPayslip(doc: jsPDF, d: PayslipDetail, logo: string | null): void {
  doc.setFillColor(15, 23, 42); doc.roundedRect(12, 12, 186, 35, 3, 3, "F");
  let textX = 20;
  if (logo) { try { doc.addImage(logo, 18, 17, 25, 25, undefined, "FAST"); textX = 49; } catch { /* text header remains */ } }
  doc.setTextColor(255, 255, 255); doc.setFont("helvetica", "bold"); doc.setFontSize(16); doc.text(d.organizationName || "Organization", textX, 26);
  doc.setFont("helvetica", "normal"); doc.setFontSize(8); doc.setTextColor(203, 213, 225);
  if (d.organizationAddress) doc.text(d.organizationAddress, textX, 32, { maxWidth: 135 });
  doc.text("OFFICIAL EMPLOYEE PAYSLIP", textX, 40);

  doc.setFillColor(248, 250, 252); doc.setDrawColor(226, 232, 240); doc.roundedRect(12, 52, 186, 26, 2, 2, "FD");
  doc.setTextColor(100, 116, 139); doc.setFontSize(7); doc.text("EMPLOYEE", 18, 60); doc.text("PAY PERIOD", 112, 60);
  doc.setTextColor(15, 23, 42); doc.setFont("helvetica", "bold"); doc.setFontSize(10); doc.text(d.staffName, 18, 67); doc.text(d.periodLabel, 112, 67);
  doc.setFont("helvetica", "normal"); doc.setFontSize(8); doc.setTextColor(100, 116, 139); if (d.employeeCode) doc.text(`Code: ${d.employeeCode}`, 18, 73); doc.text(`${d.periodStart} to ${d.periodEnd}`, 112, 73);

  doc.setTextColor(4, 120, 87); doc.setFont("helvetica", "bold"); doc.setFontSize(9); doc.text("EARNINGS", 18, 90);
  doc.setDrawColor(167, 243, 208); doc.line(18, 93, 96, 93);
  doc.setTextColor(190, 18, 60); doc.text("DEDUCTIONS", 112, 90); doc.setDrawColor(254, 205, 211); doc.line(112, 93, 190, 93);
  let earningsY = 102;
  if (d.fullGross != null && (d.daysAbsent ?? 0) > 0) { earningsY = drawRow(doc, "Full gross (contract)", d.fullGross, earningsY); earningsY = drawRow(doc, "Days absent", d.daysAbsent ?? 0, earningsY); earningsY = drawRow(doc, "Absent deduction", -(d.absentDeduction ?? 0), earningsY); }
  drawRow(doc, "Gross pay (taxable)", d.grossPay, earningsY);
  let deductionsY = 102; deductionsY = drawRow(doc, "PAYE", d.paye, deductionsY, 112); deductionsY = drawRow(doc, "NSSF (employee)", d.nssfEmployee, deductionsY, 112); drawRow(doc, "Loan / advance", d.loanDeduction, deductionsY, 112);

  doc.setFillColor(236, 253, 245); doc.setDrawColor(167, 243, 208); doc.roundedRect(12, 142, 186, 22, 2, 2, "FD");
  doc.setTextColor(6, 78, 59); doc.setFontSize(10); doc.setFont("helvetica", "bold"); doc.text("NET PAY", 18, 155); doc.setFontSize(16); doc.text(money(d.netPay), 190, 156, { align: "right" });
  doc.setFontSize(8); doc.setFont("helvetica", "normal"); doc.setTextColor(100, 116, 139); doc.text("Employer NSSF contribution", 18, 176); doc.setFont("helvetica", "bold"); doc.text(money(d.nssfEmployer), 190, 176, { align: "right" });
  doc.setDrawColor(226, 232, 240); doc.line(12, 188, 198, 188); doc.setFont("helvetica", "normal"); doc.setFontSize(7); doc.setTextColor(148, 163, 184); doc.text(`Computer-generated payslip · Generated by ${APP_SHORT_NAME}`, 12, 194);
}

export async function downloadPayslipPdf(d: PayslipDetail): Promise<void> {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  drawPayslip(doc, d, await loadLogo(d.organizationLogoUrl));
  const safe = `${d.staffName}-${d.periodLabel}`.replace(/[^\w.-]+/g, "_").slice(0, 80);
  doc.save(`payslip-${safe}.pdf`);
}

export async function downloadAllPayslipsPdf(payslips: PayslipDetail[]): Promise<void> {
  if (payslips.length === 0) return;
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const logo = await loadLogo(payslips[0].organizationLogoUrl);
  payslips.forEach((detail, index) => { if (index > 0) doc.addPage(); drawPayslip(doc, detail, logo); });
  doc.save("payslips-batch.pdf");
}
