import { jsPDF } from "jspdf";
import { APP_SHORT_NAME } from "@/constants/branding";

export type PayslipDetail = {
  organizationName: string;
  periodLabel: string;
  periodStart: string;
  periodEnd: string;
  staffName: string;
  employeeCode?: string | null;
  /** Full contractual monthly gross before absence deduction (optional display). */
  fullGross?: number;
  daysAbsent?: number;
  absentDeduction?: number;
  /** Gross after absence; PAYE/NSSF use this amount. */
  grossPay: number;
  paye: number;
  nssfEmployee: number;
  nssfEmployer: number;
  loanDeduction: number;
  netPay: number;
};

function payslipTableRows(d: PayslipDetail): [string, string][] {
  const rows: [string, string][] = [];
  if (d.fullGross != null && (d.daysAbsent ?? 0) > 0) {
    rows.push(["Full gross (contract)", String(d.fullGross)]);
    rows.push(["Days absent", String(d.daysAbsent)]);
    rows.push(["Absent deduction", String(-(d.absentDeduction ?? 0))]);
  }
  rows.push(
    ["Gross pay (taxable)", String(d.grossPay)],
    ["PAYE", String(d.paye)],
    ["NSSF (employee)", String(d.nssfEmployee)],
    ["NSSF (employer)", String(d.nssfEmployer)],
    ["Loan / advance", String(d.loanDeduction)],
    ["Net pay", String(d.netPay)]
  );
  return rows;
}

export function downloadPayslipPdf(d: PayslipDetail): void {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  let y = 18;
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text(d.organizationName || "—", 14, y);
  y += 7;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(80, 80, 80);
  doc.text(`Period: ${d.periodLabel} (${d.periodStart} → ${d.periodEnd})`, 14, y);
  y += 10;
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Payslip", 14, y);
  y += 10;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`Employee: ${d.staffName}`, 14, y);
  y += 6;
  if (d.employeeCode) {
    doc.text(`Code: ${d.employeeCode}`, 14, y);
    y += 6;
  }
  const rows = payslipTableRows(d);
  for (const [k, v] of rows) {
    doc.text(k, 14, y);
    doc.text(v, 120, y, { align: "right" });
    y += 7;
  }
  y += 6;
  doc.setFontSize(7);
  doc.setTextColor(130, 130, 130);
  doc.text(`Generated by ${APP_SHORT_NAME}`, 14, y);
  const safe = `${d.staffName}-${d.periodLabel}`.replace(/[^\w.-]+/g, "_").slice(0, 80);
  doc.save(`payslip-${safe}.pdf`);
}

export function downloadAllPayslipsPdf(payslips: PayslipDetail[]): void {
  if (payslips.length === 0) return;
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  payslips.forEach((d, idx) => {
    if (idx > 0) doc.addPage();
    let y = 18;
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text(d.organizationName || "—", 14, y);
    y += 7;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(80, 80, 80);
    doc.text(`Period: ${d.periodLabel} (${d.periodStart} → ${d.periodEnd})`, 14, y);
    y += 10;
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Payslip", 14, y);
    y += 10;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(`Employee: ${d.staffName}`, 14, y);
    y += 6;
    if (d.employeeCode) {
      doc.text(`Code: ${d.employeeCode}`, 14, y);
      y += 6;
    }
    const rows = payslipTableRows(d);
    for (const [k, v] of rows) {
      doc.text(k, 14, y);
      doc.text(v, 120, y, { align: "right" });
      y += 7;
    }
    y += 6;
    doc.setFontSize(7);
    doc.setTextColor(130, 130, 130);
    doc.text(`Generated by ${APP_SHORT_NAME}`, 14, y);
  });
  doc.save(`payslips-batch.pdf`);
}
