import { useCallback, useEffect, useMemo, useState } from "react";
import { Activity, RefreshCw } from "lucide-react";
import { useAuth } from "../../contexts/AuthContext";
import { supabase } from "../../lib/supabase";

const db = supabase as any;
type Log = { id:string; client_id:string|null; engagement_id:string|null; entity_type:string; action:string; summary:string; details:Record<string,string>; performed_by:string|null; occurred_at:string };
type Named = { id:string; name?:string; title?:string; full_name?:string; email?:string };
const friendly=(value:string)=>value.replace(/^practice_/,"").replaceAll("_"," ").replace(/\b\w/g,x=>x.toUpperCase());

export function PracticeActivityPage(){const{user}=useAuth();const orgId=user?.organization_id;const[logs,setLogs]=useState<Log[]>([]);const[clients,setClients]=useState<Named[]>([]);const[engagements,setEngagements]=useState<Named[]>([]);const[staff,setStaff]=useState<Named[]>([]);const[filter,setFilter]=useState("all");const[message,setMessage]=useState("");
const load=useCallback(async()=>{if(!orgId)return;const[l,c,e,s]=await Promise.all([db.from("practice_activity_log").select("*").eq("organization_id",orgId).order("occurred_at",{ascending:false}).limit(500),db.from("practice_clients").select("id,name").eq("organization_id",orgId),db.from("practice_engagements").select("id,title").eq("organization_id",orgId),db.from("staff").select("id,full_name,email").eq("organization_id",orgId)]);const error=l.error||c.error||e.error||s.error;if(error)setMessage(error.message);else{setLogs(l.data||[]);setClients(c.data||[]);setEngagements(e.data||[]);setStaff(s.data||[]);}},[orgId]);useEffect(()=>{void load();},[load]);
const rows=useMemo(()=>filter==="all"?logs:logs.filter(x=>x.entity_type===filter),[filter,logs]);const entityTypes=Array.from(new Set(logs.map(x=>x.entity_type)));const name=(list:Named[],id:string|null,key:"name"|"title"|"staff")=>{const item=list.find(x=>x.id===id);return key==="staff"?(item?.full_name||item?.email||"System"):(item?.[key]||"—");};
return <div className="space-y-6 p-4 sm:p-6 md:p-8"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><Activity className="h-7 w-7 text-brand-700"/><h1 className="text-3xl font-bold">Practice Activity</h1></div><p className="mt-1 text-sm text-slate-500">Auditable history across delivery, client requests, support and billing.</p></div><div className="flex gap-2"><select className="rounded-lg border px-3 py-2 text-sm" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All activity</option>{entityTypes.map(x=><option key={x} value={x}>{friendly(x)}</option>)}</select><button className="app-btn-secondary" onClick={()=>void load()}><RefreshCw className="h-4 w-4"/> Refresh</button></div></div>{message&&<div className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm">{message}</div>}<section className="rounded-xl border bg-white"><div className="divide-y">{rows.map(row=><div key={row.id} className="grid gap-2 p-4 md:grid-cols-[180px_1fr_220px]"><div><p className="text-xs text-slate-500">{new Date(row.occurred_at).toLocaleString()}</p><p className="mt-1 text-xs font-medium text-brand-700">{friendly(row.entity_type)}</p></div><div><p className="font-medium">{row.summary}</p><p className="text-sm text-slate-500">{friendly(row.action)}{row.details?.status?` · Status: ${friendly(row.details.status)}`:""}{row.details?.due_date?` · Due: ${row.details.due_date}`:""}</p><p className="mt-1 text-xs text-slate-400">{name(clients,row.client_id,"name")}{row.engagement_id?` · ${name(engagements,row.engagement_id,"title")}`:""}</p></div><p className="text-sm text-slate-500 md:text-right">{name(staff,row.performed_by,"staff")}</p></div>)}{!rows.length&&<p className="p-8 text-center text-sm text-slate-500">No matching activity yet.</p>}</div></section></div>}
