import { useCallback, useEffect, useState } from "react";
import { Building2, RefreshCw, UserPlus, Users } from "lucide-react";
import { useAuth } from "../../contexts/AuthContext";
import { supabase } from "../../lib/supabase";
import { ReadOnlyNotice } from "../common/ReadOnlyNotice";

const db = supabase as any;
const input = "w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-brand-500 focus:outline-none focus:ring-2 focus:ring-brand-100";
type Client = { id: string; name: string; legal_name: string | null; trading_name: string | null; client_type: string | null; industry: string | null; contact_name: string | null; email: string | null; phone: string | null; tax_id: string | null; registration_number: string | null; address: string | null; branches: string | null; modules_used: string[]; hosting_arrangement: string | null; subscription_plan: string | null; subscription_status: string; renewal_date: string | null; relationship_manager_id: string | null; risk_level: string; status: string; notes: string | null };
type Contact = { id: string; client_id: string; full_name: string; job_title: string | null; email: string | null; phone: string | null; is_primary: boolean; is_authorized_representative: boolean; can_approve_deliverables: boolean; can_view_billing: boolean };
type Staff = { id: string; full_name: string; email: string };
const blank = { name: "", legal_name: "", trading_name: "", client_type: "Business", industry: "", email: "", phone: "", tax_id: "", registration_number: "", address: "", branches: "", modules_used: "", hosting_arrangement: "Cloud", subscription_plan: "", renewal_date: "", relationship_manager_id: "", risk_level: "normal", notes: "" };

export function PracticeClientsPage({ readOnly = false }: { readOnly?: boolean }) {
  const { user } = useAuth(); const orgId = user?.organization_id;
  const [clients, setClients] = useState<Client[]>([]); const [contacts, setContacts] = useState<Contact[]>([]); const [staff, setStaff] = useState<Staff[]>([]);
  const [selectedId, setSelectedId] = useState(""); const [form, setForm] = useState<Record<string,string>>(blank); const [contact, setContact] = useState<Record<string,string>>({}); const [message, setMessage] = useState("");
  const load = useCallback(async () => { if (!orgId) return; const [c,s,k] = await Promise.all([db.from("practice_clients").select("*").eq("organization_id",orgId).order("name"),db.from("staff").select("id,full_name,email").eq("organization_id",orgId).eq("is_active",true).order("full_name"),db.from("practice_client_contacts").select("*").eq("organization_id",orgId).order("is_primary",{ascending:false}).order("full_name")]); const error=c.error||s.error||k.error; if(error)setMessage(error.message); else {setClients(c.data||[]);setStaff(s.data||[]);setContacts(k.data||[]);} },[orgId]);
  useEffect(()=>{void load();},[load]);
  const selectClient=(client:Client)=>{setSelectedId(client.id);setForm({name:client.name||"",legal_name:client.legal_name||"",trading_name:client.trading_name||"",client_type:client.client_type||"Business",industry:client.industry||"",email:client.email||"",phone:client.phone||"",tax_id:client.tax_id||"",registration_number:client.registration_number||"",address:client.address||"",branches:client.branches||"",modules_used:(client.modules_used||[]).join(", "),hosting_arrangement:client.hosting_arrangement||"",subscription_plan:client.subscription_plan||"",renewal_date:client.renewal_date||"",relationship_manager_id:client.relationship_manager_id||"",risk_level:client.risk_level||"normal",notes:client.notes||""});};
  const save=async()=>{if(!orgId||!form.name?.trim())return;const payload={organization_id:orgId,name:form.name.trim(),legal_name:form.legal_name||null,trading_name:form.trading_name||null,client_type:form.client_type||null,industry:form.industry||null,email:form.email||null,phone:form.phone||null,tax_id:form.tax_id||null,registration_number:form.registration_number||null,address:form.address||null,branches:form.branches||null,modules_used:(form.modules_used||"").split(",").map(x=>x.trim()).filter(Boolean),hosting_arrangement:form.hosting_arrangement||null,subscription_plan:form.subscription_plan||null,renewal_date:form.renewal_date||null,relationship_manager_id:form.relationship_manager_id||null,risk_level:form.risk_level||"normal",notes:form.notes||null,updated_at:new Date().toISOString()};const result=selectedId?await db.from("practice_clients").update(payload).eq("id",selectedId).eq("organization_id",orgId):await db.from("practice_clients").insert(payload);if(result.error)setMessage(result.error.message);else{setMessage(selectedId?"Client profile updated.":"Client profile created.");setSelectedId("");setForm(blank);await load();}};
  const addContact=async()=>{if(!orgId||!selectedId||!contact.full_name?.trim())return;const result=await db.from("practice_client_contacts").insert({organization_id:orgId,client_id:selectedId,full_name:contact.full_name.trim(),job_title:contact.job_title||null,email:contact.email||null,phone:contact.phone||null,is_primary:contact.is_primary==="true",is_authorized_representative:contact.authorized==="true",can_approve_deliverables:contact.approver==="true",can_view_billing:contact.billing==="true"});if(result.error)setMessage(result.error.message);else{setContact({});setMessage("Client contact added.");await load();}};
  const selected=clients.find(c=>c.id===selectedId);
  return <div className="space-y-6 p-4 sm:p-6 md:p-8">{readOnly&&<ReadOnlyNotice/>}<div className="flex flex-wrap justify-between gap-3"><div><div className="flex items-center gap-2"><Building2 className="h-7 w-7 text-brand-700"/><h1 className="text-3xl font-bold">Client Profiles</h1></div><p className="mt-1 text-sm text-slate-500">Commercial, operational and authorized-contact records for practice clients.</p></div><button className="app-btn-secondary" onClick={()=>void load()}><RefreshCw className="h-4 w-4"/> Refresh</button></div>{message&&<div className="rounded-lg border border-blue-200 bg-blue-50 p-3 text-sm">{message}</div>}
  <div className="grid items-start gap-4 xl:grid-cols-[320px_1fr]"><section className="overflow-hidden rounded-xl border bg-white"><div className="border-b p-3"><button className="app-btn-primary w-full" disabled={readOnly} onClick={()=>{setSelectedId("");setForm(blank);}}>New client</button></div>{clients.map(c=><button key={c.id} className={`block w-full border-b p-3 text-left ${selectedId===c.id?"bg-brand-50":"hover:bg-slate-50"}`} onClick={()=>selectClient(c)}><p className="font-medium">{c.name}</p><p className="text-xs text-slate-500">{c.industry||c.client_type||"Client"} · {c.status}</p></button>)}{!clients.length&&<p className="p-5 text-center text-sm text-slate-500">No clients.</p>}</section>
  <div className="space-y-4"><section className="rounded-xl border bg-white p-4"><h2 className="mb-4 font-semibold">{selectedId?"Edit client profile":"Create client profile"}</h2><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Field p="Display name *" k="name" f={form} s={setForm}/><Field p="Legal name" k="legal_name" f={form} s={setForm}/><Field p="Trading name" k="trading_name" f={form} s={setForm}/><Field p="Client type" k="client_type" f={form} s={setForm}/><Field p="Industry" k="industry" f={form} s={setForm}/><Field p="Email" k="email" f={form} s={setForm}/><Field p="Phone" k="phone" f={form} s={setForm}/><Field p="TIN" k="tax_id" f={form} s={setForm}/><Field p="Registration number" k="registration_number" f={form} s={setForm}/><Field p="Address / location" k="address" f={form} s={setForm}/><Field p="Branches" k="branches" f={form} s={setForm}/><Field p="BOAT modules (comma separated)" k="modules_used" f={form} s={setForm}/><Field p="Hosting arrangement" k="hosting_arrangement" f={form} s={setForm}/><Field p="Subscription plan" k="subscription_plan" f={form} s={setForm}/><input className={input} type="date" value={form.renewal_date||""} onChange={e=>setForm({...form,renewal_date:e.target.value})}/><select className={input} value={form.relationship_manager_id||""} onChange={e=>setForm({...form,relationship_manager_id:e.target.value})}><option value="">Relationship manager</option>{staff.map(x=><option key={x.id} value={x.id}>{x.full_name||x.email}</option>)}</select><select className={input} value={form.risk_level||"normal"} onChange={e=>setForm({...form,risk_level:e.target.value})}><option value="low">Low risk</option><option value="normal">Normal risk</option><option value="high">High risk</option><option value="restricted">Restricted</option></select><textarea className={`${input} md:col-span-2 xl:col-span-3`} placeholder="Client notes" value={form.notes||""} onChange={e=>setForm({...form,notes:e.target.value})}/></div><button className="app-btn-primary mt-4" disabled={readOnly||!form.name?.trim()} onClick={()=>void save()}>{selectedId?"Save profile":"Create client"}</button></section>
  {selected&&<section className="rounded-xl border bg-white p-4"><div className="mb-4 flex items-center gap-2"><Users className="h-5 w-5 text-brand-700"/><h2 className="font-semibold">Contacts for {selected.name}</h2></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Field p="Full name *" k="full_name" f={contact} s={setContact}/><Field p="Job title" k="job_title" f={contact} s={setContact}/><Field p="Email" k="email" f={contact} s={setContact}/><Field p="Phone" k="phone" f={contact} s={setContact}/><Check l="Primary contact" k="is_primary" f={contact} s={setContact}/><Check l="Authorized representative" k="authorized" f={contact} s={setContact}/><Check l="Can approve deliverables" k="approver" f={contact} s={setContact}/><Check l="Can view billing" k="billing" f={contact} s={setContact}/></div><button className="app-btn-secondary mt-3" disabled={readOnly||!contact.full_name?.trim()} onClick={()=>void addContact()}><UserPlus className="h-4 w-4"/> Add contact</button><div className="mt-4 grid gap-2 md:grid-cols-2">{contacts.filter(c=>c.client_id===selectedId).map(c=><div key={c.id} className="rounded-lg border p-3"><p className="font-medium">{c.full_name}{c.is_primary?" · Primary":""}</p><p className="text-xs text-slate-500">{c.job_title||"Contact"} · {c.email||c.phone||"No details"}</p><p className="mt-1 text-xs text-slate-500">{[c.is_authorized_representative&&"Authorized",c.can_approve_deliverables&&"Approver",c.can_view_billing&&"Billing"].filter(Boolean).join(" · ")||"General contact"}</p></div>)}</div></section>}</div></div></div>;
}
function Field({p,k,f,s}:{p:string;k:string;f:Record<string,string>;s:(v:Record<string,string>)=>void}){return <input className={input} placeholder={p} value={f[k]||""} onChange={e=>s({...f,[k]:e.target.value})}/>;}function Check({l,k,f,s}:{l:string;k:string;f:Record<string,string>;s:(v:Record<string,string>)=>void}){return <label className="flex items-center gap-2 rounded-lg border px-3 py-2 text-sm"><input type="checkbox" checked={f[k]==="true"} onChange={e=>s({...f,[k]:String(e.target.checked)})}/>{l}</label>;}
