import { useEffect, useMemo, useState } from "react";
import { useAuth } from "../../contexts/AuthContext";
import { supabase } from "../../lib/supabase";
import { filterByOrganizationId } from "../../lib/supabaseOrgFilter";
import { ReadOnlyNotice } from "../common/ReadOnlyNotice";
import { ManufacturingRoutingTemplatePicker } from "./ManufacturingRoutingTemplatePicker";

type WorkCenter = { id: string; name: string; code: string | null; capacity_per_hour: number; active: boolean };
type Bom = { id: string; product_name: string; version: string; status: string };
type Operation = { id: string; bom_id: string; sequence_no: number; operation_name: string; work_center_id: string | null; planned_minutes: number; instructions: string | null };

export function ManufacturingOperationsPage({ readOnly = false }: { readOnly?: boolean }) {
  const { user } = useAuth(); const orgId = user?.organization_id ?? null; const superAdmin = !!user?.isSuperAdmin;
  const [centers, setCenters] = useState<WorkCenter[]>([]); const [boms, setBoms] = useState<Bom[]>([]); const [operations, setOperations] = useState<Operation[]>([]); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const [centerName, setCenterName] = useState(""); const [centerCode, setCenterCode] = useState(""); const [capacity, setCapacity] = useState("1");
  const [bomId, setBomId] = useState(""); const [operationName, setOperationName] = useState(""); const [workCenterId, setWorkCenterId] = useState(""); const [minutes, setMinutes] = useState("0"); const [instructions, setInstructions] = useState("");
  const load = async () => { setError(""); const [c, b, o] = await Promise.all([
    filterByOrganizationId(supabase.from("manufacturing_work_centers").select("id,name,code,capacity_per_hour,active").order("name"), orgId, superAdmin),
    filterByOrganizationId(supabase.from("manufacturing_boms").select("id,product_name,version,status").in("status", ["Active", "Draft"]).order("product_name"), orgId, superAdmin),
    filterByOrganizationId(supabase.from("manufacturing_routing_operations").select("id,bom_id,sequence_no,operation_name,work_center_id,planned_minutes,instructions").order("sequence_no"), orgId, superAdmin),
  ]); if (c.error || b.error || o.error) { setError(c.error?.message || b.error?.message || o.error?.message || "Could not load operations."); return; } setCenters((c.data || []) as WorkCenter[]); setBoms((b.data || []) as Bom[]); setOperations((o.data || []) as Operation[]); };
  useEffect(() => { void load(); }, [orgId, superAdmin]);
  const addCenter = async () => { if (!centerName.trim() || readOnly) return; setSaving(true); const { error: saveError } = await supabase.from("manufacturing_work_centers").insert({ organization_id: orgId, name: centerName.trim(), code: centerCode.trim() || null, capacity_per_hour: Number(capacity || 1) }); setSaving(false); if (saveError) { setError(saveError.message); return; } setCenterName(""); setCenterCode(""); setCapacity("1"); await load(); };
  const addOperation = async () => { if (!bomId || !operationName.trim() || readOnly) return; setSaving(true); const sequenceNo = Math.max(0, ...operations.filter((operation) => operation.bom_id === bomId).map((operation) => operation.sequence_no)) + 1; const { error: saveError } = await supabase.from("manufacturing_routing_operations").insert({ organization_id: orgId, bom_id: bomId, sequence_no: sequenceNo, operation_name: operationName.trim(), work_center_id: workCenterId || null, planned_minutes: Number(minutes || 0), instructions: instructions.trim() || null }); setSaving(false); if (saveError) { setError(saveError.message); return; } setOperationName(""); setWorkCenterId(""); setMinutes("0"); setInstructions(""); await load(); };
  const selectedBom = boms.find((bom) => bom.id === bomId); const routing = useMemo(() => operations.filter((operation) => operation.bom_id === bomId), [operations, bomId]);
  return <div className="p-6 md:p-8 space-y-6">{readOnly && <ReadOnlyNotice />}<div><h1 className="text-2xl font-bold text-slate-900">Work centres & routings</h1><p className="mt-1 text-sm text-slate-600">Define the production stages that create job cards when a production order is released.</p></div>{error && <p className="rounded border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}
    <section className="rounded-xl border bg-white p-4"><h2 className="font-semibold text-slate-900">Work centres</h2><div className="mt-3 grid gap-2 md:grid-cols-4"><input value={centerName} onChange={(e) => setCenterName(e.target.value)} placeholder="e.g. Mixing line" className="rounded border px-3 py-2 text-sm"/><input value={centerCode} onChange={(e) => setCenterCode(e.target.value)} placeholder="Code (optional)" className="rounded border px-3 py-2 text-sm"/><input type="number" min="0.001" value={capacity} onChange={(e) => setCapacity(e.target.value)} placeholder="Capacity/hour" className="rounded border px-3 py-2 text-sm"/><button disabled={readOnly || saving} onClick={() => void addCenter()} className="app-btn-primary disabled:opacity-50">Add work centre</button></div><div className="mt-4 flex flex-wrap gap-2">{centers.map((center) => <span key={center.id} className="rounded-full border bg-slate-50 px-3 py-1 text-sm text-slate-700">{center.name}{center.code ? ` · ${center.code}` : ""} · {Number(center.capacity_per_hour).toFixed(2)}/hr</span>)}{!centers.length && <p className="text-sm text-slate-500">No work centres yet.</p>}</div></section>
    <section className="rounded-xl border bg-white p-4"><h2 className="font-semibold text-slate-900">Routing operations</h2><div className="mt-3 grid gap-2 md:grid-cols-2 lg:grid-cols-5"><select value={bomId} onChange={(e) => setBomId(e.target.value)} className="rounded border px-3 py-2 text-sm"><option value="">Select BOM...</option>{boms.map((bom) => <option key={bom.id} value={bom.id}>{bom.product_name} · {bom.version}</option>)}</select><input value={operationName} onChange={(e) => setOperationName(e.target.value)} placeholder="Operation, e.g. Blend" className="rounded border px-3 py-2 text-sm"/><select value={workCenterId} onChange={(e) => setWorkCenterId(e.target.value)} className="rounded border px-3 py-2 text-sm"><option value="">No work centre</option>{centers.filter((center) => center.active).map((center) => <option key={center.id} value={center.id}>{center.name}</option>)}</select><input type="number" min="0" value={minutes} onChange={(e) => setMinutes(e.target.value)} placeholder="Planned minutes" className="rounded border px-3 py-2 text-sm"/><button disabled={readOnly || saving || !bomId} onClick={() => void addOperation()} className="app-btn-primary disabled:opacity-50">Add step</button></div><textarea value={instructions} onChange={(e) => setInstructions(e.target.value)} placeholder="Work instructions (optional)" rows={2} className="mt-2 w-full rounded border px-3 py-2 text-sm"/>{bomId && <ManufacturingRoutingTemplatePicker key={bomId} bomId={bomId} organizationId={orgId} centers={centers.filter((center) => center.active)} disabled={readOnly || saving || routing.length > 0} onApplied={load} />}{selectedBom && <div className="mt-4"><p className="text-sm font-medium text-slate-800">{selectedBom.product_name} · {selectedBom.version}</p>{routing.length ? <ol className="mt-2 space-y-2">{routing.map((operation) => <li key={operation.id} className="rounded border bg-slate-50 px-3 py-2 text-sm"><strong>{operation.sequence_no}. {operation.operation_name}</strong><span className="ml-2 text-slate-600">{centers.find((center) => center.id === operation.work_center_id)?.name || "No work centre"} · {Number(operation.planned_minutes).toFixed(0)} min</span>{operation.instructions && <p className="mt-1 text-xs text-slate-600">{operation.instructions}</p>}</li>)}</ol> : <p className="mt-2 text-sm text-slate-500">No routing operations defined for this BOM.</p>}</div>}</section></div>;
}
