import { useCallback, useEffect, useMemo, useState } from "react";
import { useAuth } from "../../contexts/AuthContext";
import { supabase } from "../../lib/supabase";
import { PageNotes } from "../common/PageNotes";
import { fetchAllPages } from "../../lib/supabasePagination";

type RegisterRow = { stay_id:string; actual_check_in:string|null; actual_check_out:string|null; room_number:string|null; guest_first_name:string|null; guest_last_name:string|null; first_billing_date:string|null; last_billing_date:string|null; expected_nights:number; charged_nights:number; billed:number; paid:number };
const money=(amount:number)=>amount.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});

export function RoomBillingReportPage(){
  const {user}=useAuth(); const orgId=user?.organization_id;
  const [rows,setRows]=useState<RegisterRow[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);
  const [dateFrom,setDateFrom]=useState(""),[dateTo,setDateTo]=useState(""),[search,setSearch]=useState(""),[resultFilter,setResultFilter]=useState<"all"|"review"|"reconciled">("all");
  const load=useCallback(async()=>{setLoading(true);setError(null);try{if(!orgId)throw new Error("Missing organization on your staff profile.");const data=await fetchAllPages((from,to)=>(supabase as any).rpc("get_hotel_room_reconciliation_register").range(from,to));setRows(data as RegisterRow[])}catch(e){setError(e instanceof Error?e.message:"Failed to load room reconciliation.")}finally{setLoading(false)}},[orgId]);
  useEffect(()=>{void load()},[load]);
  const reconciliations=useMemo(()=>rows.map(r=>({...r,expectedNights:Number(r.expected_nights||0),chargedNights:Number(r.charged_nights||0),nightDifference:Number(r.charged_nights||0)-Number(r.expected_nights||0),billed:Number(r.billed||0),paid:Number(r.paid||0),balance:Number(r.billed||0)-Number(r.paid||0)})).filter(r=>r.billed!==0||r.paid!==0||r.nightDifference!==0).filter(r=>{const arrival=r.actual_check_in?.slice(0,10)||"",departure=r.actual_check_out?.slice(0,10)||arrival;if(dateFrom&&departure<dateFrom)return false;if(dateTo&&arrival>dateTo)return false;const q=search.trim().toLowerCase();if(q&&!`${r.guest_first_name||""} ${r.guest_last_name||""} ${r.room_number||""}`.toLowerCase().includes(q))return false;const review=r.nightDifference!==0||Math.abs(r.balance)>.01;return resultFilter==="all"||(resultFilter==="review"?review:!review)}),[rows,dateFrom,dateTo,search,resultFilter]);
  const exceptions=reconciliations.filter(r=>r.nightDifference!==0||Math.abs(r.balance)>.01).length,totalBilled=reconciliations.reduce((s,r)=>s+r.billed,0),totalPaid=reconciliations.reduce((s,r)=>s+r.paid,0);
  return <div className="p-6 md:p-8"><div className="mb-6 flex flex-wrap items-center gap-2"><h1 className="text-3xl font-bold text-slate-900">Room billing &amp; cash-in reconciliation</h1><PageNotes ariaLabel="Room reconciliation help"><p>Compare dated stays and charges with completed guest payments.</p></PageNotes></div>
    {error&&<div className="mb-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    <div className="mb-5 flex flex-wrap items-end gap-3 rounded-xl border bg-white p-4"><label className="text-xs font-medium text-slate-600">From<input type="date" value={dateFrom} onChange={e=>setDateFrom(e.target.value)} className="mt-1 block rounded-lg border px-3 py-2 text-sm"/></label><label className="text-xs font-medium text-slate-600">To<input type="date" value={dateTo} onChange={e=>setDateTo(e.target.value)} className="mt-1 block rounded-lg border px-3 py-2 text-sm"/></label><label className="min-w-52 flex-1 text-xs font-medium text-slate-600">Guest or room<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search guest or room" className="mt-1 block w-full rounded-lg border px-3 py-2 text-sm"/></label><label className="text-xs font-medium text-slate-600">Result<select value={resultFilter} onChange={e=>setResultFilter(e.target.value as typeof resultFilter)} className="mt-1 block rounded-lg border px-3 py-2 text-sm"><option value="all">All</option><option value="review">Needs review</option><option value="reconciled">Reconciled</option></select></label><button onClick={()=>{setDateFrom("");setDateTo("");setSearch("");setResultFilter("all")}} className="rounded-lg border px-3 py-2 text-sm">Clear</button></div>
    {loading?<p className="py-4 text-slate-500">Loading reconciliation…</p>:<><div className="mb-6 grid grid-cols-1 gap-4 sm:grid-cols-3"><Metric label="Total billed" value={money(totalBilled)}/><Metric label="Total paid" value={money(totalPaid)}/><Metric label="Stays requiring review" value={String(exceptions)} warn={exceptions>0}/></div><div className="app-card overflow-x-auto"><div className="border-b p-4"><h2 className="font-semibold">Combined reconciliation</h2><p className="text-xs text-slate-500">One dated row per stay. Filters apply to overlapping stay dates.</p></div><table className="w-full min-w-[1200px] text-sm"><thead className="bg-slate-50"><tr>{["Guest / room","Stay dates","Billing dates","Expected nights","Charged nights","Billed","Paid","Balance","Result"].map((h,i)=><th key={h} className={`p-3 ${i>2&&i<8?"text-right":"text-left"}`}>{h}</th>)}</tr></thead><tbody>{reconciliations.length===0?<tr><td colSpan={9} className="p-8 text-center text-slate-500">No reconciliation records match these filters.</td></tr>:reconciliations.map(r=>{const review=r.nightDifference!==0||Math.abs(r.balance)>.01,guest=`${r.guest_first_name||""} ${r.guest_last_name||""}`.trim()||"Guest";return <tr key={r.stay_id} className="border-t"><td className="p-3 font-medium">{guest} · Room {r.room_number||"—"}{r.actual_check_out?" · checked out":""}</td><td className="p-3 whitespace-nowrap">{r.actual_check_in?.slice(0,10)||"—"} → {r.actual_check_out?.slice(0,10)||"Current"}</td><td className="p-3 whitespace-nowrap">{r.first_billing_date||"—"}{r.last_billing_date&&r.last_billing_date!==r.first_billing_date?` → ${r.last_billing_date}`:""}</td><td className="p-3 text-right">{r.expectedNights}</td><td className={`p-3 text-right ${r.nightDifference?"font-semibold text-amber-700":""}`}>{r.chargedNights}{r.nightDifference?` (${r.nightDifference>0?"+":""}${r.nightDifference})`:""}</td><td className="p-3 text-right">{money(r.billed)}</td><td className="p-3 text-right">{money(r.paid)}</td><td className={`p-3 text-right font-semibold ${r.balance>.01?"text-amber-700":r.balance<-.01?"text-blue-700":"text-emerald-700"}`}>{money(r.balance)}</td><td className="p-3"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${review?"bg-amber-100 text-amber-800":"bg-emerald-100 text-emerald-800"}`}>{review?"Review":"Reconciled"}</span></td></tr>})}</tbody></table></div></>}
  </div>
}
function Metric({label,value,warn=false}:{label:string;value:string;warn?:boolean}){return <div className="app-card p-4"><p className="text-xs text-slate-500">{label}</p><p className={`text-2xl font-bold ${warn?"text-amber-700":""}`}>{value}</p></div>}
