import { useCallback, useEffect, useMemo, useState } from "react";
import { CheckCircle2, Download, Upload } from "lucide-react";
import { normalizeBulkHeader } from "@/lib/saccoBulkImport";
import { parseMigrationFile } from "@/lib/dataMigration";
import { supabase } from "@/lib/supabase";

type Check={check_key:string;completed:boolean;evidence:string|null};
const tasks=[
  ["reconcile_opening","Opening balances and imported budgets reconciled","Compare imported totals to signed school records."],
  ["uat_preparer","Budget preparer acceptance test","Create, edit and submit a sample annual budget."],
  ["uat_reviewer","Reviewer acceptance test","Review the sample and request or accept corrections."],
  ["uat_approver","Approver acceptance test","Approve, activate and revise the sample budget."],
  ["uat_readonly","Read-only access test","Confirm restricted users cannot change budget data."],
  ["backup_verified","Backup and restore verified","Record evidence of a successful backup and restore test."],
  ["staff_training","Bursar, headteacher and department heads trained","Record the session date and attendees."],
  ["responsibilities_signed","Approval responsibilities signed","Attach or reference the approved responsibility matrix."],
] as const;
const number=(v:string)=>{const n=Number(v.replaceAll(",",""));return Number.isFinite(n)?n:0};
const value=(row:Record<string,string>,keys:string[])=>{for(const key of keys){const v=row[normalizeBulkHeader(key)]?.trim();if(v)return v}return ""};

export function SchoolBudgetCompletionPanel({organizationId,userId,disabled,onImported}:{organizationId:string;userId?:string;disabled:boolean;onImported:()=>void}){
  const [checks,setChecks]=useState<Check[]>([]); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  const [review,setReview]=useState({day_of_month:"5",assigned_role:"bursar",next_review_date:"",backup_method:"supabase_managed"});
  const [draft,setDraft]=useState<{name:string;year:string;start:string;end:string;lines:Array<Record<string,unknown>>}|null>(null);
  const load=useCallback(async()=>{const[c,s]=await Promise.all([supabase.from("budget_rollout_checks").select("check_key,completed,evidence").eq("organization_id",organizationId),supabase.from("budget_review_settings").select("day_of_month,assigned_role,next_review_date,backup_method").eq("organization_id",organizationId).maybeSingle()]);setChecks((c.data as Check[])||[]);if(s.data)setReview({day_of_month:String(s.data.day_of_month),assigned_role:s.data.assigned_role,next_review_date:s.data.next_review_date,backup_method:s.data.backup_method})},[organizationId]);
  useEffect(()=>{void load()},[load]);
  const completed=useMemo(()=>tasks.filter(([key])=>checks.find(c=>c.check_key===key)?.completed).length,[checks]);
  const template=()=>{const csv="budget_name,financial_year,start_date,end_date,line_label,budget_type,term_1,term_2,term_3,annual_other,assumptions\nFY 2025 Historical,2025,2025-01-01,2025-12-31,Tuition fees,income,5000000,5000000,5000000,0,Imported from signed budget";const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="school_budget_import_template.csv";a.click();URL.revokeObjectURL(a.href)};
  const choose=async(file?:File)=>{if(!file)return;setMessage("");try{const parsed=await parseMigrationFile(file);const rows=parsed.rows;const first=rows[0];if(!first)throw new Error("The file has no data rows.");const lines=rows.map((r,i)=>({line_label:value(r,["line_label","vote","budget_line"]),budget_type:value(r,["budget_type","type"])||"operating_expense",term_1:number(value(r,["term_1","term1"])),term_2:number(value(r,["term_2","term2"])),term_3:number(value(r,["term_3","term3"])),annual_other:number(value(r,["annual_other","other"])),assumptions:value(r,["assumptions","notes"]),sort_order:i}));if(lines.some(l=>!l.line_label))throw new Error("Every row needs a line_label.");setDraft({name:value(first,["budget_name","name"]),year:value(first,["financial_year","year"]),start:value(first,["start_date"]),end:value(first,["end_date"]),lines});}catch(e){setMessage(e instanceof Error?e.message:"Could not read the file.")}};
  const apply=async()=>{if(!draft)return;setBusy(true);const{error}=await supabase.rpc("import_historical_school_budget",{p_name:draft.name,p_financial_year:Number(draft.year),p_start_date:draft.start,p_end_date:draft.end,p_lines:draft.lines,p_notes:"Historical CSV/Excel import; reconcile before approval."});setMessage(error?.message||`Imported ${draft.lines.length} budget lines as a draft.`);if(!error){setDraft(null);onImported()}setBusy(false)};
  const toggle=async(key:string,current:boolean)=>{const evidence=current?null:window.prompt("Evidence, date, attendees, or document reference:",checks.find(c=>c.check_key===key)?.evidence||"");if(!current&&evidence===null)return;await supabase.from("budget_rollout_checks").upsert({organization_id:organizationId,check_key:key,completed:!current,evidence,completed_by:!current?userId:null,completed_at:!current?new Date().toISOString():null,updated_at:new Date().toISOString()},{onConflict:"organization_id,check_key"});void load()};
  const saveReview=async()=>{const{error}=await supabase.from("budget_review_settings").upsert({organization_id:organizationId,day_of_month:Number(review.day_of_month),assigned_role:review.assigned_role,next_review_date:review.next_review_date,backup_method:review.backup_method,updated_by:userId,updated_at:new Date().toISOString()});setMessage(error?.message||"Monthly review and backup controls saved.");void load()};
  return <div className="rounded-xl border border-slate-200 bg-white p-4 space-y-5"><div><h2 className="font-semibold text-slate-900">Implementation completion centre</h2><p className="text-xs text-slate-600">Import history, schedule governance, and retain evidence for staff-led sign-off. {completed}/{tasks.length} controls complete.</p></div>
  <section className="rounded-lg bg-slate-50 p-3"><h3 className="text-sm font-semibold">Historical budget import</h3><div className="mt-2 flex flex-wrap gap-2"><button onClick={template} className="inline-flex items-center gap-2 rounded border px-3 py-2 text-xs"><Download className="h-4 w-4"/>Template</button><label className="inline-flex cursor-pointer items-center gap-2 rounded border px-3 py-2 text-xs"><Upload className="h-4 w-4"/>CSV / Excel<input type="file" accept=".csv,.xlsx,.xls" className="hidden" onChange={e=>{void choose(e.target.files?.[0]);e.currentTarget.value=""}}/></label>{draft&&<button disabled={disabled||busy} onClick={()=>void apply()} className="rounded bg-indigo-700 px-3 py-2 text-xs font-semibold text-white disabled:opacity-50">Import {draft.lines.length} lines — {draft.lines.reduce((s,l)=>s+Number(l.term_1)+Number(l.term_2)+Number(l.term_3)+Number(l.annual_other),0).toLocaleString()}</button>}</div>{draft&&<p className="mt-2 text-xs text-indigo-700">{draft.name} · FY {draft.year} · {draft.start} to {draft.end}. Imported as draft for reconciliation and approval.</p>}</section>
  <section><h3 className="text-sm font-semibold">Monthly review and backup readiness</h3><div className="mt-2 grid gap-2 md:grid-cols-5"><input type="number" min="1" max="28" value={review.day_of_month} onChange={e=>setReview(r=>({...r,day_of_month:e.target.value}))} aria-label="Review day" className="rounded border px-2 py-2 text-xs"/><select value={review.assigned_role} onChange={e=>setReview(r=>({...r,assigned_role:e.target.value}))} className="rounded border px-2 py-2 text-xs"><option value="bursar">Bursar</option><option value="accountant">Accountant</option><option value="headteacher">Headteacher</option></select><input type="date" value={review.next_review_date} onChange={e=>setReview(r=>({...r,next_review_date:e.target.value}))} className="rounded border px-2 py-2 text-xs"/><select value={review.backup_method} onChange={e=>setReview(r=>({...r,backup_method:e.target.value}))} className="rounded border px-2 py-2 text-xs"><option value="supabase_managed">Supabase managed backup</option><option value="desktop_local">Desktop local backup</option><option value="both">Both</option></select><button disabled={disabled} onClick={()=>void saveReview()} className="rounded bg-slate-900 px-3 py-2 text-xs font-semibold text-white disabled:opacity-50">Save controls</button></div></section>
  <section><h3 className="text-sm font-semibold">Acceptance, reconciliation and training sign-off</h3><div className="mt-2 grid gap-2 md:grid-cols-2">{tasks.map(([key,title,help])=>{const row=checks.find(c=>c.check_key===key);return <button key={key} disabled={disabled} onClick={()=>void toggle(key,Boolean(row?.completed))} className={`rounded-lg border p-3 text-left ${row?.completed?"border-emerald-200 bg-emerald-50":"border-slate-200"}`}><span className="flex gap-2 text-sm font-medium"><CheckCircle2 className={`h-4 w-4 ${row?.completed?"text-emerald-600":"text-slate-300"}`}/>{title}</span><span className="mt-1 block text-xs text-slate-500">{row?.evidence||help}</span></button>})}</div></section>{message&&<p className="text-sm font-medium text-indigo-700">{message}</p>}</div>;
}
