import { useCallback, useEffect, useMemo, useState } from "react";
import { Calculator } from "lucide-react";
import { supabase } from "@/lib/supabase";

type Line = { id:string; line_label:string; budget_type:string };
type Driver = { id:string; budget_line_id:string; driver_type:string; period_key:string; quantity:number; frequency:number; rate:number; collection_rate:number; calculated_amount:number; notes:string|null };
type Props = { budgetId:string; lines:Line[]; disabled?:boolean; onSaved:()=>void };
const driverOptions=[
  {value:"student_fees",label:"Expected students × fee × collection rate",quantity:"Expected students",frequency:"Fee occurrences"},
  {value:"feeding",label:"Students × feeding days × daily cost",quantity:"Students",frequency:"Feeding days"},
  {value:"staff_cost",label:"Employees × months × monthly pay",quantity:"Employees",frequency:"Months"},
  {value:"vehicles",label:"Vehicles × months × monthly running cost",quantity:"Vehicles",frequency:"Months"},
  {value:"quantity_rate",label:"Quantity × frequency × rate",quantity:"Quantity",frequency:"Frequency"},
];

export function SchoolBudgetDriversPanel({budgetId,lines,disabled,onSaved}:Props){
  const [drivers,setDrivers]=useState<Driver[]>([]); const [message,setMessage]=useState(""); const [saving,setSaving]=useState(false);
  const [form,setForm]=useState({budget_line_id:"",driver_type:"student_fees",period_key:"term_1",quantity:"",frequency:"1",rate:"",collection_rate:"100",notes:""});
  const load=useCallback(async()=>{const{data}=await supabase.from("budget_driver_assumptions").select("id,budget_line_id,driver_type,period_key,quantity,frequency,rate,collection_rate,calculated_amount,notes").eq("budget_id",budgetId).order("updated_at",{ascending:false});setDrivers((data as Driver[])||[])},[budgetId]);
  useEffect(()=>{void load()},[load]);
  const selectedDriver=driverOptions.find(d=>d.value===form.driver_type)!;
  const calculated=useMemo(()=>{const q=Number(form.quantity)||0,f=Number(form.frequency)||0,r=Number(form.rate)||0,c=form.driver_type==="student_fees"?(Number(form.collection_rate)||0)/100:1;return q*f*r*c},[form]);
  const save=async()=>{if(!form.budget_line_id||Number(form.quantity)<0||Number(form.frequency)<0||Number(form.rate)<0)return setMessage("Choose a budget line and enter valid driver values.");setSaving(true);const{data,error}=await supabase.rpc("save_budget_driver",{p_budget_line_id:form.budget_line_id,p_driver_type:form.driver_type,p_period_key:form.period_key,p_quantity:Number(form.quantity),p_frequency:Number(form.frequency),p_rate:Number(form.rate),p_collection_rate:Number(form.collection_rate),p_notes:form.notes.trim()||null});setMessage(error?.message||`Budget line updated to ${Number(data||0).toLocaleString()}.`);if(!error){await load();onSaved()}setSaving(false)};
  return <div className="rounded-xl border border-indigo-200 bg-indigo-50/40 p-4"><div className="flex items-center gap-2"><Calculator className="h-5 w-5 text-indigo-700"/><div><h3 className="font-semibold text-slate-900">Planning assumptions</h3><p className="text-xs text-slate-600">Calculate a term amount from school operating drivers and keep the calculation visible.</p></div></div>
    <div className="mt-4 grid gap-2 md:grid-cols-2 lg:grid-cols-4"><select value={form.budget_line_id} onChange={e=>setForm(f=>({...f,budget_line_id:e.target.value}))} className="rounded-lg border px-3 py-2 text-sm"><option value="">Budget line</option>{lines.map(l=><option key={l.id} value={l.id}>{l.line_label}</option>)}</select><select value={form.driver_type} onChange={e=>setForm(f=>({...f,driver_type:e.target.value}))} className="rounded-lg border px-3 py-2 text-sm">{driverOptions.map(d=><option key={d.value} value={d.value}>{d.label}</option>)}</select><select value={form.period_key} onChange={e=>setForm(f=>({...f,period_key:e.target.value}))} className="rounded-lg border px-3 py-2 text-sm"><option value="term_1">Term 1</option><option value="term_2">Term 2</option><option value="term_3">Term 3</option><option value="annual_other">Holiday / annual</option></select><input type="number" min="0" value={form.quantity} onChange={e=>setForm(f=>({...f,quantity:e.target.value}))} placeholder={selectedDriver.quantity} className="rounded-lg border px-3 py-2 text-sm"/><input type="number" min="0" value={form.frequency} onChange={e=>setForm(f=>({...f,frequency:e.target.value}))} placeholder={selectedDriver.frequency} className="rounded-lg border px-3 py-2 text-sm"/><input type="number" min="0" value={form.rate} onChange={e=>setForm(f=>({...f,rate:e.target.value}))} placeholder="Rate / unit cost" className="rounded-lg border px-3 py-2 text-sm"/>{form.driver_type==="student_fees"&&<input type="number" min="0" max="100" value={form.collection_rate} onChange={e=>setForm(f=>({...f,collection_rate:e.target.value}))} placeholder="Collection rate %" className="rounded-lg border px-3 py-2 text-sm"/>}<input value={form.notes} onChange={e=>setForm(f=>({...f,notes:e.target.value}))} placeholder="Assumption notes" className="rounded-lg border px-3 py-2 text-sm"/></div>
    <div className="mt-3 flex flex-wrap items-center gap-3"><span className="text-sm">Calculated: <b className="tabular-nums">{calculated.toLocaleString(undefined,{maximumFractionDigits:2})}</b></span><button disabled={disabled||saving} onClick={()=>void save()} className="rounded-lg bg-indigo-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{saving?"Saving…":"Apply to budget line"}</button>{message&&<span className="text-xs text-slate-600">{message}</span>}</div>
    {drivers.length>0&&<div className="mt-4 overflow-x-auto"><table className="w-full min-w-[650px] text-xs"><thead><tr className="text-left text-slate-500"><th className="py-2">Line</th><th>Driver</th><th>Period</th><th className="text-right">Calculation</th><th className="text-right">Amount</th></tr></thead><tbody>{drivers.map(d=><tr key={d.id} className="border-t border-indigo-100"><td className="py-2 font-medium">{lines.find(l=>l.id===d.budget_line_id)?.line_label||"Budget line"}</td><td>{driverOptions.find(x=>x.value===d.driver_type)?.label||d.driver_type}</td><td className="capitalize">{d.period_key.replace("_"," ")}</td><td className="text-right tabular-nums">{d.quantity} × {d.frequency} × {Number(d.rate).toLocaleString()}{d.driver_type==="student_fees"?` × ${d.collection_rate}%`:""}</td><td className="text-right font-semibold tabular-nums">{Number(d.calculated_amount).toLocaleString()}</td></tr>)}</tbody></table></div>}
  </div>;
}
