import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {createRequire} from "node:module";
import test from "node:test";
import ts from "typescript";

const require=createRequire(import.meta.url),root=new URL("../",import.meta.url);
async function compile(path,customRequire=require){const source=await readFile(new URL(path,root),"utf8"),output=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,module={exports:{}};new Function("exports","module","require",output)(module.exports,module,customRequire);return module.exports;}

test("subscription cohorts, hardware risk costs and government probability remain explicit",async()=>{const engine=await compile("src/lib/projectPortfolioEngine.ts"),base={enabled:true,annualFixedCosts:0,startYear:1,revenueDrivers:[],costDrivers:[],receivableDays:0,inventoryDays:0,payableDays:0,procurementLeadTimeDays:0};const rows=engine.calculateProjectPortfolio([{...base,id:"s",name:"Subscriptions",businessType:"subscription",startingUnits:100,annualGrowth:20,revenuePerUnit:10,directCostRate:0,subscriptionChurnRate:10},{...base,id:"h",name:"Hardware",businessType:"hardware",startingUnits:10,annualGrowth:0,revenuePerUnit:100,directCostRate:20,importDutyRate:10,warrantyRate:5,replacementRate:2},{...base,id:"g",name:"Government",businessType:"government",startingUnits:10,annualGrowth:0,revenuePerUnit:100,directCostRate:20,governmentContractProbability:50}],3);assert.deepEqual(rows.filter(row=>row.projectId==="s").map(row=>row.units),[100,210,333]);const hardware=rows.find(row=>row.projectId==="h");assert.equal(hardware.baseDirectCosts,200);assert.equal(hardware.edtechRiskCosts,170);assert.equal(hardware.directCosts,370);const government=rows.find(row=>row.projectId==="g");assert.equal(government.grossRevenue,1000);assert.equal(government.revenue,500);});

test("project working capital includes government delays and hardware lead time",async()=>{const engine=await compile("src/lib/projectPortfolioEngine.ts"),rows=engine.calculateProjectPortfolio([{id:"g",name:"Government",businessType:"government",enabled:true,startingUnits:365,revenuePerUnit:10,annualGrowth:0,directCostRate:50,annualFixedCosts:0,startYear:1,governmentContractProbability:100,governmentRetentionRate:10,governmentPaymentDelayDays:30,receivableDays:30,inventoryDays:0,payableDays:20,revenueDrivers:[],costDrivers:[]},{id:"h",name:"Hardware",businessType:"hardware",enabled:true,startingUnits:365,revenuePerUnit:10,annualGrowth:0,directCostRate:50,annualFixedCosts:0,startYear:1,inventoryDays:20,procurementLeadTimeDays:40,receivableDays:0,payableDays:0,revenueDrivers:[],costDrivers:[]}],1);const government=rows[0],hardware=rows[1];assert.equal(government.receivables,965);assert.equal(government.payables,100);assert.equal(hardware.inventory,300);});

test("asset schedule times purchases, depreciation, maintenance and allowances",async()=>{const {calculateCapitalAssetSchedule}=await compile("src/lib/capitalAssetSchedule.ts"),rows=calculateCapitalAssetSchedule([{id:"a",name:"Servers",assetClass:"Technology",purchaseYear:2,cost:1000,usefulLifeYears:4,residualValue:200,maintenanceRate:2,capitalAllowanceRate:25}],5);assert.deepEqual(rows.map(row=>row.purchases),[0,1000,0,0,0]);assert.deepEqual(rows.map(row=>row.depreciation),[0,200,200,200,200]);assert.equal(rows[1].maintenance,20);assert.equal(rows[1].capitalAllowance,250);assert.equal(rows[4].closingNetBookValue,200);});

test("model-to-budget bridge reconciles project detail to the annual forecast",async()=>{const {buildModelBudgetLines}=await compile("src/lib/modelBudgetBridge.ts"),statement={year:1,revenue:1000,costOfSales:400,operatingExpenses:300,depreciation:50,interest:20,tax:30},projects=[{projectId:"p1",name:"Subscriptions",year:1,revenue:1000,directCosts:400,fixedCosts:100}];const lines=buildModelBudgetLines(statement,projects,80);assert.equal(lines.filter(line=>line.kind==="income").reduce((sum,line)=>sum+line.amount,0),1000);assert.equal(lines.find(line=>line.key==="central-operating-expenses").amount,200);assert.equal(lines.filter(line=>line.kind==="expense").reduce((sum,line)=>sum+line.amount,0),800);assert.equal(lines.find(line=>line.kind==="asset").amount,80);});

test("version history migration creates immutable sequential snapshots",async()=>{const migration=await readFile(new URL("supabase/migrations/20260731120000_financial_model_version_history.sql",root),"utf8");assert.match(migration,/UNIQUE \(model_id, version_no\)/);assert.match(migration,/FOR UPDATE/);assert.match(migration,/MAX\(version_no\),0\)\+1/);assert.doesNotMatch(migration,/CREATE POLICY[^;]+FOR (UPDATE|DELETE)/i);});
