import { useEffect, useState } from "react";
import { BarChart3, ShieldCheck } from "lucide-react";
import { supabase } from "@/lib/supabase";

export function FinancialModelPortalPage({token}:{token:string}) {
  const [data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
  useEffect(()=>{void (supabase as any).rpc("get_financial_model_portal",{p_token:token}).then((result:any)=>{setLoading(false);if(result.error||!result.data)setError("This secure portal link is invalid, expired, or revoked.");else setData(result.data);});},[token]);
  if(loading)return <div className="grid min-h-screen place-items-center bg-slate-950 text-white">Loading secure model portal...</div>;
  if(error)return <div className="grid min-h-screen place-items-center bg-slate-950 p-6 text-center text-white"><div><ShieldCheck className="mx-auto mb-4 text-red-400" size={38}/><h1 className="text-2xl font-bold">Portal unavailable</h1><p className="mt-2 text-slate-300">{error}</p></div></div>;
  const snapshot=data.snapshot??{},model=snapshot.model_data??{},outputs=model.publishedOutputs??{},statements=outputs.statements??[],last=statements[statements.length-1]??{},brand=data.branding??{};const currency=snapshot.currency??"";const money=(value:number)=>`${currency} ${new Intl.NumberFormat("en",{notation:"compact",maximumFractionDigits:1}).format(Number(value)||0)}`;
  return <main className="min-h-screen bg-slate-50 text-slate-900"><header style={{backgroundColor:brand.primary_color||"#102b25"}} className="px-6 py-5 text-white"><div className="mx-auto flex max-w-6xl items-center justify-between"><div className="flex items-center gap-3"><BarChart3/><div><p className="text-xs font-bold uppercase tracking-widest text-emerald-200">{brand.display_name||"BOAT Financial Modelling Studio"}</p><h1 className="text-xl font-bold">{snapshot.name}</h1></div></div><span className="rounded-full bg-white/10 px-3 py-1 text-xs font-bold capitalize">{data.audience} portal</span></div></header><div className="mx-auto max-w-6xl p-6"><p className="text-sm text-slate-500">{snapshot.industry} · Approved financial model · Link expires {new Date(data.expires_at).toLocaleDateString()}</p><section className="mt-6 grid gap-4 md:grid-cols-4">{[["Funding required",model.inputs?.fundingRequired],[`Year ${last.year??"-"} revenue`,last.revenue],["EBITDA",last.ebitda],["Closing cash",last.closingCash]].map(([label,value])=><div key={String(label)} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase text-slate-400">{label}</p><p className="mt-2 text-2xl font-bold">{money(Number(value))}</p></div>)}</section><section className="mt-6 overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="p-5"><h2 className="text-xl font-bold">Financial projections</h2></div><table className="w-full min-w-[700px] text-sm"><thead className="bg-slate-50"><tr><th className="px-4 py-3 text-left">Metric</th>{statements.map((row:any)=><th key={row.year} className="px-4 py-3 text-right">Year {row.year}</th>)}</tr></thead><tbody>{[["Revenue","revenue"],["EBITDA","ebitda"],["Net profit","netProfit"],["Closing cash","closingCash"],["Debt","debt"],["DSCR","dscr"]].map(([label,key])=><tr key={key} className="border-t border-slate-100"><td className="px-4 py-3 font-semibold">{label}</td>{statements.map((row:any)=><td key={row.year} className="px-4 py-3 text-right font-semibold">{key==="dscr"?`${Number(row[key]).toFixed(2)}x`:money(row[key])}</td>)}</tr>)}</tbody></table></section><p className="mt-6 text-xs text-slate-500">Read-only approved model snapshot. Figures are management assumptions and require independent due diligence. {brand.report_footer}</p></div></main>;
}
