import { useEffect,useState } from "react";
import { History } from "lucide-react";
import { supabase } from "@/lib/supabase";

type Version={id:string;version_no:number;model_status:string;change_summary:string;created_at:string;created_by:string|null};

export function PhaseFiveVersionHistory({modelId,refreshKey}:{modelId:string|null;refreshKey:number}) {
  const [versions,setVersions]=useState<Version[]>([]),[unavailable,setUnavailable]=useState(false);
  useEffect(()=>{if(!modelId){setVersions([]);return;}let active=true;void (supabase as any).from("financial_model_versions").select("id,version_no,model_status,change_summary,created_at,created_by").eq("model_id",modelId).order("version_no",{ascending:false}).limit(20).then((result:any)=>{if(!active)return;if(result.error){setUnavailable(true);return;}setUnavailable(false);setVersions(result.data??[]);});return()=>{active=false;};},[modelId,refreshKey]);
  return <section className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center gap-3 border-b border-slate-100 p-5"><div className="grid h-9 w-9 place-items-center rounded-lg bg-slate-900 text-white"><History size={17}/></div><div><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Phase 5 · auditability</p><h3 className="text-lg font-bold">Immutable model versions</h3></div></div><div className="p-5">{unavailable?<p className="text-xs font-semibold text-amber-700">Version history becomes available after the financial-model version migration is applied.</p>:!modelId?<p className="text-xs text-slate-500">Save the model to start its version history.</p>:!versions.length?<p className="text-xs text-slate-500">The next explicit save will create version 1.</p>:<div className="space-y-2">{versions.map(version=><div key={version.id} className="flex flex-col justify-between gap-2 rounded-lg border border-slate-100 bg-slate-50 p-3 sm:flex-row sm:items-center"><div><p className="text-sm font-bold">Version {version.version_no} <span className="ml-1 text-xs font-semibold capitalize text-slate-500">· {version.model_status.replace("_"," ")}</span></p><p className="mt-1 text-xs text-slate-600">{version.change_summary}</p></div><time className="shrink-0 text-[11px] text-slate-400">{new Date(version.created_at).toLocaleString()}</time></div>)}</div>}</div></section>;
}
