import { useEffect, useState } from "react";
import { Check, Send, X } from "lucide-react";
import { supabase } from "@/lib/supabase";

type Review={id:string;requested_by:string;decided_by:string|null;status:"pending"|"approved"|"changes_requested"|"cancelled";request_note:string|null;decision_note:string|null;requested_at:string;decided_at:string|null};

export function PhaseThreeWorkflow({modelId,currentUserId,status,onStatus}:{modelId:string|null;currentUserId?:string;status:string;onStatus:(status:string)=>void}) {
  const [reviews,setReviews]=useState<Review[]>([]),[note,setNote]=useState(""),[loading,setLoading]=useState(false),[error,setError]=useState("");
  const load=async()=>{if(!modelId){setReviews([]);return;}const {data}=await (supabase as any).from("financial_model_reviews").select("id,requested_by,decided_by,status,request_note,decision_note,requested_at,decided_at").eq("model_id",modelId).order("requested_at",{ascending:false});setReviews(data??[]);};
  useEffect(()=>{void load();},[modelId]);
  const pending=reviews.find(review=>review.status==="pending");
  const submit=async()=>{if(!modelId){setError("Save the draft before submitting it for review.");return;}setLoading(true);setError("");const {error:rpcError}=await (supabase as any).rpc("submit_financial_model_review",{p_model_id:modelId,p_note:note});setLoading(false);if(rpcError){setError(rpcError.message);return;}setNote("");onStatus("submitted");await load();};
  const decide=async(decision:"approved"|"changes_requested")=>{if(!pending)return;setLoading(true);setError("");const {error:rpcError}=await (supabase as any).rpc("decide_financial_model_review",{p_review_id:pending.id,p_decision:decision,p_note:note});setLoading(false);if(rpcError){setError(rpcError.message);return;}setNote("");onStatus(decision);await load();};
  const canDecide=pending&&pending.requested_by!==currentUserId;
  return <section className="mt-6 overflow-hidden rounded-2xl border border-indigo-200 bg-white shadow-sm"><div className="flex flex-col justify-between gap-3 border-b border-indigo-100 bg-indigo-50/50 p-5 sm:flex-row sm:items-center"><div><p className="text-xs font-bold uppercase tracking-wider text-indigo-700">Phase 3 · approval workflow</p><h3 className="mt-1 text-xl font-bold">Independent model review</h3><p className="mt-1 text-sm text-slate-500">Submit the saved model for another organization member to approve or return with changes.</p></div><span className={`rounded-full px-3 py-1.5 text-xs font-bold capitalize ${status==="approved"?"bg-emerald-100 text-emerald-800":status==="changes_requested"?"bg-amber-100 text-amber-800":status==="submitted"?"bg-indigo-100 text-indigo-800":"bg-slate-100 text-slate-600"}`}>{status.replace("_"," ")}</span></div><div className="p-5"><label><span className="mb-1 block text-xs font-bold">Review note</span><textarea value={note} onChange={event=>setNote(event.target.value)} rows={3} placeholder={pending?"Enter approval comments or required changes":"Explain what the reviewer should focus on"} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-indigo-500"/></label>{error&&<p className="mt-2 text-xs font-semibold text-red-600">{error}</p>}<div className="mt-3 flex flex-wrap gap-2">{!pending&&status!=="approved"&&<button onClick={submit} disabled={loading} className="flex items-center gap-2 rounded-lg bg-indigo-700 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-60"><Send size={15}/> Submit for review</button>}{pending&&canDecide&&<><button onClick={()=>decide("approved")} disabled={loading} className="flex items-center gap-2 rounded-lg bg-emerald-700 px-4 py-2.5 text-sm font-bold text-white"><Check size={15}/> Approve</button><button onClick={()=>decide("changes_requested")} disabled={loading} className="flex items-center gap-2 rounded-lg bg-amber-600 px-4 py-2.5 text-sm font-bold text-white"><X size={15}/> Request changes</button></>}{pending&&!canDecide&&<p className="text-xs font-semibold text-indigo-700">Awaiting an independent reviewer. The submitter cannot decide this review.</p>}</div>{reviews.length>0&&<div className="mt-5 border-t border-slate-100 pt-4"><p className="mb-2 text-sm font-bold">Review history</p><div className="space-y-2">{reviews.map(review=><div key={review.id} className="rounded-lg border border-slate-100 bg-slate-50 p-3"><div className="flex justify-between gap-3"><span className="text-xs font-bold capitalize">{review.status.replace("_"," ")}</span><span className="text-[10px] text-slate-400">{new Date(review.requested_at).toLocaleString()}</span></div>{review.request_note&&<p className="mt-1 text-xs text-slate-600">Request: {review.request_note}</p>}{review.decision_note&&<p className="mt-1 text-xs text-slate-600">Decision: {review.decision_note}</p>}</div>)}</div></div>}</div></section>;
}
