import { useEffect, useState } from "react";
import { Copy, KeyRound, Link, Palette, Users, Webhook } from "lucide-react";
import { supabase } from "@/lib/supabase";

export function PhaseThreeEnterpriseControls({organizationId,modelId,status}:{organizationId?:string|null;modelId:string|null;status:string}) {
  const [members,setMembers]=useState<any[]>([]),[collaborators,setCollaborators]=useState<any[]>([]),[memberId,setMemberId]=useState(""),[role,setRole]=useState("viewer");
  const [brand,setBrand]=useState({display_name:"BOAT Financial Modelling Studio",logo_url:"",primary_color:"#047857",accent_color:"#6ee7b7",report_footer:""});
  const [portalAudience,setPortalAudience]=useState("investor"),[portalLink,setPortalLink]=useState(""),[apiName,setApiName]=useState("Investor integration"),[apiKey,setApiKey]=useState("");
  const [webhookName,setWebhookName]=useState("Approval webhook"),[webhookUrl,setWebhookUrl]=useState(""),[message,setMessage]=useState("");
  const load=async()=>{if(!organizationId)return;const [memberResult,brandResult,collaboratorResult]=await Promise.all([(supabase as any).from("organization_members").select("user_id,full_name,role").eq("organization_id",organizationId).eq("is_active",true),(supabase as any).from("financial_model_branding").select("display_name,logo_url,primary_color,accent_color,report_footer").eq("organization_id",organizationId).maybeSingle(),modelId?(supabase as any).from("financial_model_collaborators").select("user_id,role,created_at").eq("model_id",modelId):Promise.resolve({data:[]})]);setMembers(memberResult.data??[]);setCollaborators(collaboratorResult.data??[]);if(brandResult.data)setBrand({...brand,...brandResult.data});};
  useEffect(()=>{void load();},[organizationId,modelId]);
  const addCollaborator=async()=>{if(!organizationId||!modelId||!memberId)return;const {error}=await (supabase as any).from("financial_model_collaborators").upsert({organization_id:organizationId,model_id:modelId,user_id:memberId,role},{onConflict:"model_id,user_id"});setMessage(error?.message??"Collaborator access saved.");await load();};
  const saveBrand=async()=>{if(!organizationId)return;const {error}=await (supabase as any).from("financial_model_branding").upsert({organization_id:organizationId,...brand,updated_at:new Date().toISOString()});setMessage(error?.message??"White-label settings saved.");};
  const createPortal=async()=>{if(!modelId)return;const {data,error}=await (supabase as any).rpc("create_financial_model_portal_link",{p_model_id:modelId,p_audience:portalAudience,p_label:`${portalAudience} portal`,p_days:30});if(error){setMessage(error.message);return;}const url=`${window.location.origin}${window.location.pathname}?financial_model_token=${data.token}`;setPortalLink(url);};
  const createApiKey=async()=>{if(!organizationId)return;const {data,error}=await (supabase as any).rpc("create_financial_model_api_key",{p_organization_id:organizationId,p_name:apiName,p_scopes:["models:read","models:export"]});if(error){setMessage(error.message);return;}setApiKey(data.api_key);};
  const addWebhook=async()=>{if(!organizationId||!webhookUrl)return;const {error}=await (supabase as any).from("financial_model_webhooks").insert({organization_id:organizationId,name:webhookName,endpoint_url:webhookUrl,events:["model.submitted","model.approved","model.changes_requested"]});setMessage(error?.message??"Webhook endpoint registered.");};
  const input="w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm";
  return <section className="mt-6 overflow-hidden rounded-2xl border border-slate-300 bg-white shadow-sm"><div className="border-b border-slate-200 bg-slate-900 p-5 text-white"><p className="text-xs font-bold uppercase tracking-wider text-emerald-300">Phase 3 · enterprise edition</p><h3 className="mt-1 text-xl font-bold">Collaboration, portals and integrations</h3><p className="mt-1 text-sm text-slate-300">Control model-level roles, external approved snapshots, organization branding and integration credentials.</p></div>{message&&<div className="border-b border-slate-100 bg-blue-50 px-5 py-3 text-xs font-semibold text-blue-800">{message}</div>}<div className="grid gap-5 p-5 xl:grid-cols-2">
    <div className="rounded-xl border border-slate-200 p-4"><div className="mb-3 flex items-center gap-2"><Users size={17} className="text-emerald-700"/><h4 className="font-bold">Model collaborators</h4></div><div className="grid gap-2 sm:grid-cols-[1fr_130px_auto]"><select value={memberId} onChange={e=>setMemberId(e.target.value)} className={input}><option value="">Select organization member</option>{members.map(m=><option key={m.user_id} value={m.user_id}>{m.full_name||m.user_id}</option>)}</select><select value={role} onChange={e=>setRole(e.target.value)} className={input}><option>viewer</option><option>reviewer</option><option>editor</option><option>owner</option></select><button onClick={addCollaborator} disabled={!modelId} className="rounded-lg bg-slate-900 px-3 py-2 text-xs font-bold text-white disabled:opacity-40">Grant</button></div><div className="mt-3 flex flex-wrap gap-2">{collaborators.map(c=><span key={c.user_id} className="rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-bold">{members.find(m=>m.user_id===c.user_id)?.full_name||c.user_id.slice(0,8)} · {c.role}</span>)}</div></div>
    <div className="rounded-xl border border-slate-200 p-4"><div className="mb-3 flex items-center gap-2"><Link size={17} className="text-emerald-700"/><h4 className="font-bold">Bank and investor portal</h4></div><div className="flex gap-2"><select value={portalAudience} onChange={e=>setPortalAudience(e.target.value)} className={input}><option value="investor">Investor dashboard</option><option value="bank">Bank credit portal</option></select><button onClick={createPortal} disabled={!modelId||status!=="approved"} className="rounded-lg bg-emerald-700 px-3 py-2 text-xs font-bold text-white disabled:opacity-40">Create 30-day link</button></div>{status!=="approved"&&<p className="mt-2 text-[11px] font-semibold text-amber-700">External links require an approved model.</p>}{portalLink&&<div className="mt-3 flex gap-2"><input readOnly value={portalLink} className={input}/><button onClick={()=>navigator.clipboard.writeText(portalLink)} className="rounded-lg border border-slate-200 px-3"><Copy size={15}/></button></div>}</div>
    <div className="rounded-xl border border-slate-200 p-4"><div className="mb-3 flex items-center gap-2"><Palette size={17} className="text-emerald-700"/><h4 className="font-bold">White-label presentation</h4></div><div className="grid gap-2 sm:grid-cols-2"><input value={brand.display_name} onChange={e=>setBrand({...brand,display_name:e.target.value})} placeholder="Brand name" className={input}/><input value={brand.logo_url??""} onChange={e=>setBrand({...brand,logo_url:e.target.value})} placeholder="HTTPS logo URL" className={input}/><label className="flex items-center gap-2 text-xs font-bold"><input type="color" value={brand.primary_color} onChange={e=>setBrand({...brand,primary_color:e.target.value})}/> Primary colour</label><input value={brand.report_footer??""} onChange={e=>setBrand({...brand,report_footer:e.target.value})} placeholder="Report footer" className={input}/></div><button onClick={saveBrand} className="mt-3 rounded-lg bg-slate-900 px-3 py-2 text-xs font-bold text-white">Save branding</button></div>
    <div className="rounded-xl border border-slate-200 p-4"><div className="mb-3 flex items-center gap-2"><KeyRound size={17} className="text-emerald-700"/><h4 className="font-bold">API client</h4></div><div className="flex gap-2"><input value={apiName} onChange={e=>setApiName(e.target.value)} className={input}/><button onClick={createApiKey} className="rounded-lg bg-slate-900 px-3 py-2 text-xs font-bold text-white">Generate</button></div>{apiKey&&<div className="mt-3 rounded-lg border border-amber-200 bg-amber-50 p-3"><p className="text-[11px] font-bold text-amber-800">Copy now. This key is shown only once.</p><code className="mt-1 block break-all text-xs">{apiKey}</code></div>}</div>
    <div className="rounded-xl border border-slate-200 p-4 xl:col-span-2"><div className="mb-3 flex items-center gap-2"><Webhook size={17} className="text-emerald-700"/><h4 className="font-bold">Approval webhook integration</h4></div><div className="grid gap-2 sm:grid-cols-[220px_1fr_auto]"><input value={webhookName} onChange={e=>setWebhookName(e.target.value)} className={input}/><input value={webhookUrl} onChange={e=>setWebhookUrl(e.target.value)} placeholder="https://your-system.example/webhooks/boat" className={input}/><button onClick={addWebhook} className="rounded-lg bg-slate-900 px-3 py-2 text-xs font-bold text-white">Register</button></div></div>
  </div></section>;
}
