import { useState } from "react";
import { Check, Sparkles } from "lucide-react";
import { supabase } from "@/lib/supabase";
import type { FinancialModelInputs } from "@/lib/financialModellingEngine";
import type { StatementYear } from "@/lib/phase1FinancialEngine";
import type { ModelProject } from "@/lib/projectPortfolioEngine";

type Suggestion={id:string;category:string;title:string;rationale:string;target:keyof FinancialModelInputs|"review-only";recommendedValue:number|null;impact:string;confidence:"low"|"medium"|"high"};
type Review={summary:string;suggestions:Suggestion[]};

export function PhaseTwoAiAssistant({organizationId,company,industry,currency,inputs,statements,projects,onApply}:{organizationId?:string|null;company:string;industry:string;currency:string;inputs:FinancialModelInputs;statements:StatementYear[];projects:ModelProject[];onApply:(target:keyof FinancialModelInputs,value:number)=>void}) {
  const [review,setReview]=useState<Review|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(""),[applied,setApplied]=useState<string[]>([]);
  const generate=async()=>{if(!organizationId){setError("Save this model to an organization before requesting AI review.");return;}setLoading(true);setError("");const last=statements[statements.length-1];const {data,error:invokeError}=await supabase.functions.invoke("financial-model-ai",{body:{organization_id:organizationId,model_context:{company,industry,currency,inputs,projects:projects.map(p=>({name:p.name,businessType:p.businessType,enabled:p.enabled,startingUnits:p.startingUnits,annualGrowth:p.annualGrowth,directCostRate:p.directCostRate,fixedCosts:p.annualFixedCosts})),financials:statements.map(row=>({year:row.year,revenue:row.revenue,ebitda:row.ebitda,netProfit:row.netProfit,closingCash:row.closingCash,debt:row.debt,dscr:row.dscr,currentRatio:row.currentRatio})),finalYear:last?.year}}});setLoading(false);if(invokeError||data?.error){setError(data?.error??invokeError?.message??"AI review failed");return;}setReview(data.review);};
  return <section className="mt-6 overflow-hidden rounded-2xl border border-fuchsia-200 bg-white shadow-sm"><div className="flex flex-col justify-between gap-3 border-b border-fuchsia-100 bg-fuchsia-50/50 p-5 sm:flex-row sm:items-center"><div><p className="text-xs font-bold uppercase tracking-wider text-fuchsia-700">Phase 2 · confirmed AI assistance</p><h3 className="mt-1 text-xl font-bold">Financial modelling reviewer</h3><p className="mt-1 text-sm text-slate-500">AI suggestions never alter the model until you apply them individually.</p></div><button type="button" onClick={generate} disabled={loading} className="flex items-center justify-center gap-2 rounded-xl bg-fuchsia-700 px-4 py-3 text-sm font-bold text-white disabled:opacity-60"><Sparkles size={16}/>{loading?"Reviewing model...":"Generate review"}</button></div>{error&&<div className="m-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}{review&&<div className="p-5"><div className="rounded-xl border border-fuchsia-100 bg-fuchsia-50 p-4"><p className="text-sm font-bold text-fuchsia-950">AI review summary</p><p className="mt-1 text-sm leading-6 text-fuchsia-900">{review.summary}</p></div><div className="mt-4 grid gap-3 lg:grid-cols-2">{review.suggestions.map(item=>{const canApply=item.target!=="review-only"&&item.recommendedValue!=null;const isApplied=applied.includes(item.id);return <div key={item.id} className="rounded-xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div><span className="text-[10px] font-bold uppercase tracking-wide text-fuchsia-700">{item.category} · {item.confidence} confidence</span><p className="mt-1 font-bold">{item.title}</p></div>{canApply&&<button disabled={isApplied} onClick={()=>{onApply(item.target as keyof FinancialModelInputs,item.recommendedValue!);setApplied(current=>[...current,item.id]);}} className="shrink-0 rounded-lg bg-slate-900 px-3 py-2 text-xs font-bold text-white disabled:bg-emerald-700">{isApplied?<><Check className="mr-1 inline" size={12}/>Applied</>:"Apply"}</button>}</div><p className="mt-2 text-xs leading-5 text-slate-600">{item.rationale}</p>{item.recommendedValue!=null&&<p className="mt-2 text-xs font-bold text-slate-800">Suggested value: {item.recommendedValue.toLocaleString()} {item.target}</p>}<p className="mt-1 text-[11px] text-slate-500">Expected impact: {item.impact}</p></div>})}</div><p className="mt-4 text-[11px] font-semibold text-slate-500">AI output may be incomplete or incorrect. Confirm assumptions, tax treatment and financing terms with qualified advisers.</p></div>}</section>;
}
