import fs from "node:fs/promises";
import { Workbook, SpreadsheetFile } from "@oai/artifact-tool";
const outDir="C:/Projects/BOAT/outputs/019fecc4-9f94-7e01-b76c-991a6bb24544"; await fs.mkdir(outDir,{recursive:true});
const wb=Workbook.create();
const pages=[
 ["Menu","Home / menu"],["Cashbook Entry","New cashbook transaction"],["Cashbook Register","Cashbook register"],["Daily Cashbook","Daily cashbook summary"],
 ["Dashboard","Microfinance dashboard"],["Borrowers","Borrower register"],["Loan Products","Loan product setup"],["Applications","Applications & appraisal"],
 ["Approvals & Disb.","Approvals & disbursement"],["Collections","Repayment collections"],["Follow-ups","Collection follow-ups"],["Loan Servicing","Penalties, waivers & interest"],
 ["Portfolio Risk","Portfolio at risk"],["Provisioning","Classification & provisioning"],["Restructures","Loan restructuring"],["Write-offs","Write-offs & recoveries"],
 ["Integration","Integration & sync"],["Reports","Report centre"]
];
for(const [name] of pages) wb.worksheets.add(name);
const black="#111111", white="#FFFFFF", soft="#F7F7F7", gray="#E5E7EB", blue="#2563EB", red="#DC2626", green="#166534", amber="#B45309";
const money='"UGX "#,##0;[Red]("UGX "#,##0);-';
function setLink(cell,target,label){cell.values=[[label]];}
function border(range,style="thin"){range.format.borders={preset:"all",style,color:black};}
function sidebar(ws,active){
 ws.showGridLines=false; ws.getRange("A1:C2").merge(); ws.getRange("A1").values=[["BOAT\nMICROFINANCE"]];
 ws.getRange("A1:C2").format={fill:black,font:{bold:true,color:white,size:15},wrapText:true,horizontalAlignment:"center",verticalAlignment:"center"};
 ws.getRange("A3:C3").merge();ws.getRange("A3").values=[["WORKBOOK MENU"]];ws.getRange("A3:C3").format={fill:"#D9D9D9",font:{bold:true,color:black},horizontalAlignment:"center"};
 const nav=[
  ["item","Menu"],["group","CASHBOOK"],["item","Cashbook Entry"],["item","Cashbook Register"],["item","Daily Cashbook"],
  ["group","OVERVIEW"],["item","Dashboard"],["group","CLIENT & PRODUCT SETUP"],["item","Borrowers"],["item","Loan Products"],
  ["group","LENDING OPERATIONS"],["item","Applications"],["item","Approvals & Disb."],["item","Collections"],
  ["group","PORTFOLIO MANAGEMENT"],["item","Follow-ups"],["item","Loan Servicing"],["item","Portfolio Risk"],["item","Provisioning"],["item","Restructures"],["item","Write-offs"],
  ["group","ADMINISTRATION"],["item","Reports"],["item","Integration"]
 ];
 nav.forEach(([kind,name],i)=>{const r=4+i;ws.getRange(`A${r}:C${r}`).merge();if(kind==="item")setLink(ws.getRange(`A${r}`),name,name);else ws.getRange(`A${r}`).values=[[name]];ws.getRange(`A${r}:C${r}`).format=kind==="group"?{fill:"#D9D9D9",font:{bold:true,color:black,size:8},borders:{preset:"all",style:"thin",color:"#A3A3A3"},verticalAlignment:"center"}:{fill:name===active?black:white,font:{bold:name===active,color:name===active?white:blue,size:9},borders:{preset:"all",style:"thin",color:"#A3A3A3"},verticalAlignment:"center"};ws.getRange(`A${r}:C${r}`).format.rowHeight=kind==="group"?16:19;});
 ws.getRange("A29:C31").merge();ws.getRange("A29").values=[["Blue text = input/link\nBlack text = formula\nRed text = exception"]];ws.getRange("A29:C31").format={fill:soft,font:{color:"#404040",size:9},wrapText:true,verticalAlignment:"center",borders:{preset:"outside",style:"thin",color:black}};
 ws.getRange("A:A").format.columnWidth=8;ws.getRange("B:B").format.columnWidth=8;ws.getRange("C:C").format.columnWidth=8;
 ws.freezePanes.freezeRows(4);ws.freezePanes.freezeColumns(3);
}
function pageHead(ws,title,subtitle){
 ws.getRange("D1:S1").merge();ws.getRange("D1").values=[[title]];ws.getRange("D1:S1").format={font:{bold:true,color:black,size:18},verticalAlignment:"center",borders:{bottom:{style:"thick",color:black}}};ws.getRange("D1:S1").format.rowHeight=32;
 ws.getRange("D2:S2").merge();ws.getRange("D2").values=[[subtitle]];ws.getRange("D2:S2").format={font:{italic:true,color:"#525252",size:10},borders:{bottom:{style:"thin",color:black}}};
}
function section(ws,row,title){ws.getRange(`D${row}:S${row}`).merge();ws.getRange(`D${row}`).values=[[title]];ws.getRange(`D${row}:S${row}`).format={fill:soft,font:{bold:true,color:black},borders:{bottom:{style:"medium",color:black}}};}
function table(ws,row,headers,rows,name){
 const start=4,end=3+headers.length,last=Math.max(row+1,row+rows.length);const rg=ws.getRangeByIndexes(row-1,start-1,last-row+1,headers.length);rg.clear({applyTo:"all"});
 ws.getRangeByIndexes(row-1,start-1,1,headers.length).values=[headers];if(rows.length)ws.getRangeByIndexes(row,start-1,rows.length,headers.length).values=rows;
 const t=ws.tables.add(`D${row}:${String.fromCharCode(64+end)}${last}`,true,name);t.style="TableStyleLight1";
 const hr=ws.getRangeByIndexes(row-1,start-1,1,headers.length);hr.format={fill:white,font:{bold:true,color:black},wrapText:true,horizontalAlignment:"center",verticalAlignment:"center",borders:{preset:"all",style:"medium",color:black}};hr.format.rowHeight=30;
 border(ws.getRangeByIndexes(row,start-1,last-row,headers.length));return {last,endCol:String.fromCharCode(64+end)};
}
for(const [name,title] of pages){const ws=wb.worksheets.getItem(name);sidebar(ws,name);pageHead(ws,name==="Menu"?"BOAT MICROFINANCE — SINGLE VIEW":title,name==="Menu"?"Select a page on the left; the active worksheet opens in this right-hand workspace.":"BOAT Microfinance module | Currency: UGX");for(const c of "DEFGHIJKLMNOPQRS")ws.getRange(`${c}:${c}`).format.columnWidth=14;ws.getRange("D:D").format.columnWidth=18;ws.getRange("E:E").format.columnWidth=18;ws.getRange("F:F").format.columnWidth=22;}

// MENU / LANDING
let ws=wb.worksheets.getItem("Menu");section(ws,4,"WORKSPACE OVERVIEW");
const menuCards=[["D6:G6","D7:G9","Cashbook balance","='Daily Cashbook'!K7"],["H6:K6","H7:K9","Gross portfolio","=SUM('Portfolio Risk'!F7:F106)"],["L6:O6","L7:O9","PAR 30",'=IFERROR(SUMIF(\'Portfolio Risk\'!H7:H106,">=30",\'Portfolio Risk\'!F7:F106)/SUM(\'Portfolio Risk\'!F7:F106),0)'],["P6:S6","P7:S9","Open follow-ups",'=COUNTIF(\'Follow-ups\'!O7:O106,"open")+COUNTIF(\'Follow-ups\'!O7:O106,"promise_pending")']];
for(const [lr,vr,l,f] of menuCards){ws.getRange(lr).merge();ws.getRange(lr.split(":")[0]).values=[[l]];ws.getRange(vr).merge();ws.getRange(vr.split(":")[0]).formulas=[[f]];ws.getRange(lr).format={fill:soft,font:{bold:true,color:black},horizontalAlignment:"center",borders:{preset:"all",style:"thin",color:black}};ws.getRange(vr).format={font:{bold:true,color:black,size:16},horizontalAlignment:"center",verticalAlignment:"center",borders:{preset:"all",style:"medium",color:black}};}
ws.getRange("D7:K9").format.numberFormat=money;ws.getRange("L7:O9").format.numberFormat="0.0%";section(ws,11,"GET STARTED");
const tiles=[["D13:H15","Cashbook Entry","Record a receipt, disbursement, expense, transfer or adjustment."],["J13:N15","Dashboard","Review portfolio, collections and operational queues."],["P13:S15","Reports","Open operational and financial reporting views."]];for(const [rg,target,desc] of tiles){ws.getRange(rg).merge();setLink(ws.getRange(rg.split(":")[0]),target,`${target}\n${desc}`);ws.getRange(rg).format={fill:white,font:{bold:true,color:blue,size:11},wrapText:true,verticalAlignment:"center",horizontalAlignment:"center",borders:{preset:"all",style:"medium",color:black}};}

// CASHBOOK ENTRY — presentation-grade controlled form
ws=wb.worksheets.getItem("Cashbook Entry");section(ws,4,"NEW CASHBOOK TRANSACTION");
ws.getRange("D5:S5").merge();ws.getRange("D5").values=[["Complete the cream input cells. Loan and customer selections are sourced from the live registers; linked details and control checks update automatically."]];ws.getRange("D5:S5").format={font:{italic:true,color:"#525252",size:9},wrapText:true};
ws.getRange("D6:J6").merge();ws.getRange("D6").values=[["A. TRANSACTION DETAILS"]];ws.getRange("D6:J6").format={fill:soft,font:{bold:true},borders:{bottom:{style:"medium",color:black}}};
const txLabels=[["D8:F8","Transaction date *","G8:J8"],["D9:F9","Transaction type *","G9:J9"],["D10:F10","Voucher / receipt no. *","G10:J10"],["D11:F11","Payment channel *","G11:J11"],["D12:F12","Branch *","G12:J12"],["D13:F13","Cash / bank account *","G13:J13"],["D14:F14","External reference","G14:J14"],["D15:F15","Prepared by *","G15:J15"],["D16:F16","Approval status","G16:J16"]];
for(const [lr,label,ir] of txLabels){ws.getRange(lr).merge();ws.getRange(lr.split(":")[0]).values=[[label]];ws.getRange(ir).merge();ws.getRange(lr).format={fill:soft,font:{bold:true},borders:{preset:"all",style:"thin",color:black}};ws.getRange(ir).format={fill:"#FFFDF2",font:{color:blue},borders:{preset:"all",style:"thin",color:black}};}
ws.getRange("G8").values=[[new Date("2026-08-11")]];ws.getRange("G8:J8").format.numberFormat="yyyy-mm-dd";ws.getRange("G9").values=[["Loan repayment"]];ws.getRange("G11").values=[["mobile_money"]];ws.getRange("G12").values=[["Head Office"]];ws.getRange("G16").values=[["draft"]];
ws.getRange("G9:J9").dataValidation={rule:{type:"list",values:["Loan repayment","Loan disbursement","Fee income","Penalty income","Operating expense","Cash transfer","Recovery","Adjustment"]}};
ws.getRange("G11:J11").dataValidation={rule:{type:"list",values:["cash","bank","mobile_money","cheque","transfer"]}};
ws.getRange("G12:J12").dataValidation={rule:{type:"list",values:["Head Office","Central","Eastern","Northern","Western"]}};
ws.getRange("G13:J13").dataValidation={rule:{type:"list",values:["Cash on Hand","Main Bank Account","Mobile Money Float","Collections Account","Disbursement Account"]}};
ws.getRange("G16:J16").dataValidation={rule:{type:"list",values:["draft","ready_for_approval","approved","rejected"]}};

ws.getRange("L6:S6").merge();ws.getRange("L6").values=[["B. CUSTOMER & LOAN DETAILS"]];ws.getRange("L6:S6").format={fill:soft,font:{bold:true},borders:{bottom:{style:"medium",color:black}}};
const loanLabels=[["L8:N8","Loan number *","O8:S8"],["L9:N9","Customer number *","O9:S9"],["L10:N10","Customer name","O10:S10"],["L11:N11","Loan status","O11:S11"],["L12:N12","Outstanding principal","O12:S12"],["L13:N13","Days past due","O13:S13"],["L14:N14","Transaction narration *","O14:S16"]];
for(const [lr,label,ir] of loanLabels){ws.getRange(lr).merge();ws.getRange(lr.split(":")[0]).values=[[label]];ws.getRange(ir).merge();ws.getRange(lr).format={fill:soft,font:{bold:true},borders:{preset:"all",style:"thin",color:black}};ws.getRange(ir).format={fill:(label.includes("number")||label.includes("narration"))?"#FFFDF2":white,font:{color:(label.includes("number")||label.includes("narration"))?blue:black},wrapText:true,borders:{preset:"all",style:"thin",color:black}};}
ws.getRange("O8:S8").dataValidation={rule:{type:"list",formula1:"='Approvals & Disb.'!$D$7:$D$106"}};
ws.getRange("O9:S9").dataValidation={rule:{type:"list",formula1:"='Borrowers'!$D$7:$D$106"}};
ws.getRange("O10").formulas=[['=IFERROR(XLOOKUP(O9,\'Borrowers\'!$D$7:$D$106,\'Borrowers\'!$F$7:$F$106,""),"")']];
ws.getRange("O11").formulas=[['=IFERROR(XLOOKUP(O8,\'Portfolio Risk\'!$D$7:$D$106,\'Portfolio Risk\'!$L$7:$L$106,""),"")']];
ws.getRange("O12").formulas=[['=IFERROR(XLOOKUP(O8,\'Portfolio Risk\'!$D$7:$D$106,\'Portfolio Risk\'!$F$7:$F$106,0),0)']];
ws.getRange("O13").formulas=[['=IFERROR(XLOOKUP(O8,\'Portfolio Risk\'!$D$7:$D$106,\'Portfolio Risk\'!$H$7:$H$106,0),0)']];
ws.getRange("O12:S12").format.numberFormat=money;

section(ws,18,"C. AMOUNT & REPAYMENT ALLOCATION");
const amountLabels=[["D20:F20","Deposit / receipt amount","G20:J20"],["D21:F21","Withdrawal / payment amount","G21:J21"],["L20:N20","Principal component","O20:S20"],["L21:N21","Interest component","O21:S21"],["L22:N22","Fee component","O22:S22"],["L23:N23","Penalty component","O23:S23"],["L24:N24","Other component","O24:S24"]];
for(const [lr,label,ir] of amountLabels){ws.getRange(lr).merge();ws.getRange(lr.split(":")[0]).values=[[label]];ws.getRange(ir).merge();ws.getRange(lr).format={fill:soft,font:{bold:true},borders:{preset:"all",style:"thin",color:black}};ws.getRange(ir).format={fill:"#FFFDF2",font:{color:blue},numberFormat:money,borders:{preset:"all",style:"thin",color:black}};}
ws.getRange("D23:J24").merge();ws.getRange("D23").values=[["Repayment allocation follows BOAT order: penalties → fees → interest → principal. Components must equal the receipt amount for loan repayments."]];ws.getRange("D23:J24").format={fill:white,font:{italic:true,color:"#525252",size:9},wrapText:true,verticalAlignment:"center",borders:{preset:"outside",style:"thin",color:black}};

section(ws,26,"D. CONTROL CHECKS & POSTING PREVIEW");
ws.getRange("D28:H32").values=[["Control","Actual","Expected","Status", "Action"],["One-sided cash entry",null,null,null,"Enter either receipt or payment"],["Repayment allocation",null,null,null,"Allocate the full repayment"],["Customer / loan match",null,null,null,"Confirm selected records agree"],["Required fields",null,null,null,"Complete all starred fields"]];border(ws.getRange("D28:H32"));ws.getRange("D28:H28").format={font:{bold:true},borders:{preset:"all",style:"medium",color:black}};
ws.getRange("E29").formulas=[["=SUM(G20:J20)+SUM(G21:J21)"]];ws.getRange("F29").values=[[0]];ws.getRange("G29").formulas=[['=IF(OR(SUM(G20:J20)=0,SUM(G21:J21)=0),"OK","FIX")']];
ws.getRange("E30").formulas=[["=SUM(O20:O24)"]];ws.getRange("F30").formulas=[['=IF(G9="Loan repayment",SUM(G20:J20),0)']];ws.getRange("G30").formulas=[['=IF(ABS(E30-F30)<1,"OK","FIX")']];
ws.getRange("E31").formulas=[['=IF(OR(O8="",O9=""),0,--(IFERROR(XLOOKUP(O8,\'Approvals & Disb.\'!$D$7:$D$106,\'Approvals & Disb.\'!$F$7:$F$106,""),"")=O10))']];ws.getRange("F31").values=[[1]];ws.getRange("G31").formulas=[['=IF(E31=1,"OK","CHECK")']];
ws.getRange("E32").formulas=[['=COUNTBLANK(G8)+COUNTBLANK(G9)+COUNTBLANK(G10)+COUNTBLANK(G11)+COUNTBLANK(G12)+COUNTBLANK(G13)+COUNTBLANK(G15)+COUNTBLANK(O14)']];ws.getRange("F32").values=[[0]];ws.getRange("G32").formulas=[['=IF(E32=0,"OK","FIX")']];ws.getRange("E29:F30").format.numberFormat=money;
ws.getRange("J28:S28").merge();ws.getRange("J28").values=[["POSTING PREVIEW"]];ws.getRange("J28:S28").format={font:{bold:true},borders:{bottom:{style:"medium",color:black}}};
ws.getRange("J29:S31").values=[["Date","Voucher","Type","Account","Receipt","Payment","Loan","Customer","Reference","Status"],[null,null,null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null,null,null]];border(ws.getRange("J29:S31"));ws.getRange("J29:S29").format={font:{bold:true},borders:{preset:"all",style:"medium",color:black}};
const preview=['=IF(G8="","",G8)','=IF(G10="","",G10)','=IF(G9="","",G9)','=IF(G13="","",G13)','=IF(G20="","",G20)','=IF(G21="","",G21)','=IF(O8="","",O8)','=IF(O9="","",O9)','=IF(G14="","",G14)','=IF(G16="","",G16)'];for(let i=0;i<10;i++)ws.getRangeByIndexes(29,9+i,1,1).formulas=[[preview[i]]];ws.getRange("J30").format.numberFormat="yyyy-mm-dd";ws.getRange("N30:O30").format.numberFormat=money;
ws.getRange("J33:S34").merge();ws.getRange("J33").formulas=[['=IF(COUNTIF(G29:G32,"FIX")+COUNTIF(G29:G32,"CHECK")=0,"READY FOR APPROVAL","REVIEW HIGHLIGHTED CONTROLS")']];ws.getRange("J33:S34").format={fill:soft,font:{bold:true,size:13,color:black},horizontalAlignment:"center",verticalAlignment:"center",borders:{preset:"all",style:"medium",color:black}};

// CASHBOOK REGISTER
ws=wb.worksheets.getItem("Cashbook Register");section(ws,4,"CASHBOOK REGISTER");const cashRows=[[new Date("2026-08-10"),"CB-001","Loan repayment","Loan repayment","LN-2026-000001","BRW-2026-000001","Amina Nakitende","mobile_money",500000,0,null,"MM-1001","approved"],[new Date("2026-08-11"),"CB-002","Loan disbursement","Loan proceeds","LN-2026-000002","BRW-2026-000002","Moses Okello","bank",0,2500000,null,"BNK-1002","approved"]];table(ws,6,["Date","Voucher","Type","Narration","Loan No.","Borrower No.","Borrower","Channel","Deposit","Withdrawal","Running Balance","Reference","Status"],cashRows,"CashbookRegister");for(let r=7;r<=106;r++)ws.getRange(`N${r}`).formulas=[[r===7?`=L${r}-M${r}`:`=IF(D${r}="","",N${r-1}+L${r}-M${r})`]];ws.getRange("D7:D106").format.numberFormat="yyyy-mm-dd";ws.getRange("L7:N106").format.numberFormat=money;ws.getRange("D7:M106").format.font={color:blue};ws.getRange("P7:P106").format.font={color:blue};

// DAILY CASHBOOK
ws=wb.worksheets.getItem("Daily Cashbook");section(ws,4,"DAILY CASHBOOK BY CHANNEL");table(ws,6,["Date","Opening","Cash In","Bank In","Mobile In","Total In","Cash Out","Bank Out","Mobile Out","Total Out","Closing","Difference"],[[new Date("2026-08-10"),0,0,0,500000,null,0,0,0,null,null,null],[new Date("2026-08-11"),null,0,0,0,null,0,2500000,0,null,null,null]],"DailyCashbook");for(let r=7;r<=106;r++){ws.getRange(`E${r}`).formulas=[[r===7?"=0":`=IF(D${r}="","",N${r-1})`]];ws.getRange(`I${r}`).formulas=[[`=IF(D${r}="","",SUM(F${r}:H${r}))`]];ws.getRange(`M${r}`).formulas=[[`=IF(D${r}="","",SUM(J${r}:L${r}))`]];ws.getRange(`N${r}`).formulas=[[`=IF(D${r}="","",E${r}+I${r}-M${r})`]];ws.getRange(`O${r}`).formulas=[[`=IF(D${r}="","",N${r}-E${r}-I${r}+M${r})`]];}ws.getRange("D7:D106").format.numberFormat="yyyy-mm-dd";ws.getRange("E7:O106").format.numberFormat=money;ws.getRange("D7:H106").format.font={color:blue};ws.getRange("J7:L106").format.font={color:blue};

// Shared operational data
const loans=[["LN-2026-000001","BRW-2026-000001","Amina Nakitende","Business Growth",5000000,0.02,12,"monthly","declining",1250000,3900000,0,"active"],["LN-2026-000002","BRW-2026-000002","Moses Okello","School Fees",2500000,0.03,6,"monthly","flat",800000,1900000,18,"in_arrears"],["LN-2026-000003","BRW-2026-000003","Kawempe Traders Group","Group Enterprise",12000000,0.018,18,"monthly","declining",3000000,9800000,47,"in_arrears"],["LN-2026-000004","BRW-2026-000004","Sarah Namusoke","Agriculture",7000000,0.025,10,"monthly","declining",1400000,6500000,96,"non_performing"]];
ws=wb.worksheets.getItem("Borrowers");section(ws,4,"BORROWER REGISTER");table(ws,6,["Borrower No.","Type","Full Name","Gender","Phone","National ID","Income","Branch","Group/Centre","Risk","Status","Officer"],[["BRW-2026-000001","individual","Amina Nakitende","Female","0700000001","CM10000001",2200000,"Central","—","Low","active","Officer A"],["BRW-2026-000002","individual","Moses Okello","Male","0700000002","CM10000002",1500000,"Eastern","—","Medium","active","Officer B"],["BRW-2026-000003","group","Kawempe Traders Group","—","0700000003","REG-001",6000000,"Central","Kawempe Centre","Medium","active","Officer A"]],"Borrowers");ws.getRange("J7:J106").format.numberFormat=money;ws.getRange("D7:O106").format.font={color:blue};
ws=wb.worksheets.getItem("Loan Products");section(ws,4,"LOAN PRODUCT SETUP");table(ws,6,["Code","Product","Min Principal","Max Principal","Min Term","Max Term","Frequency","Method","Rate / Period","Installment","Guarantors","Collateral","Active"],[["BUS","Business Growth",500000,15000000,3,24,"monthly","declining",0.02,"equal_total",1,"No","Yes"],["SCH","School Fees",300000,5000000,3,12,"monthly","flat",0.03,"equal_total",0,"No","Yes"]],"Products");ws.getRange("F7:G106").format.numberFormat=money;ws.getRange("L7:L106").format.numberFormat="0.0%";ws.getRange("D7:P106").format.font={color:blue};
ws=wb.worksheets.getItem("Applications");section(ws,4,"APPLICATIONS & APPRAISAL");table(ws,6,["Application No.","Borrower No.","Product","Requested","Term","Purpose","Income","Expenses","Debt","Disposable","Installment","DSR","Status"],[["APP-2026-000001","BRW-2026-000001","Business Growth",5000000,12,"Stock expansion",2200000,900000,200000,null,null,null,"approved"],["APP-2026-000002","BRW-2026-000002","School Fees",2500000,6,"Tuition",1500000,700000,100000,null,null,null,"disbursed"]],"Applications");for(let r=7;r<=106;r++){ws.getRange(`M${r}`).formulas=[[`=IF(D${r}="","",J${r}-K${r}-L${r})`]];ws.getRange(`N${r}`).formulas=[[`=IF(D${r}="","",G${r}/H${r})`]];ws.getRange(`O${r}`).formulas=[[`=IFERROR(N${r}/M${r},0)`]];}ws.getRange("G7:G106").format.numberFormat=money;ws.getRange("J7:N106").format.numberFormat=money;ws.getRange("O7:O106").format.numberFormat="0.0%";ws.getRange("D7:L106").format.font={color:blue};ws.getRange("P7:P106").format.font={color:blue};
ws=wb.worksheets.getItem("Approvals & Disb.");section(ws,4,"APPROVAL & DISBURSEMENT");table(ws,6,["Loan No.","Application","Borrower","Decision","Approved","Rate","Term","Date","Method","Net Amount","Status"],loans.map((x,i)=>[x[0],`APP-2026-${String(i+1).padStart(6,"0")}`,x[2],"approved",x[4],x[5],x[6],new Date("2026-02-15"),i%2?"mobile_money":"bank",x[4],x[12]]),"Approvals");ws.getRange("H7:H106").format.numberFormat=money;ws.getRange("I7:I106").format.numberFormat="0.0%";ws.getRange("K7:K106").format.numberFormat="yyyy-mm-dd";ws.getRange("M7:M106").format.numberFormat=money;ws.getRange("D7:N106").format.font={color:blue};
ws=wb.worksheets.getItem("Collections");section(ws,4,"REPAYMENT COLLECTIONS");table(ws,6,["Receipt","Loan No.","Borrower","Date","Method","Amount","Penalty","Fee","Interest","Principal","Status","Reference"],[["RCT-0001",loans[0][0],loans[0][2],new Date("2026-07-15"),"mobile_money",500000,0,0,75000,425000,"posted","MM-1001"],["RCT-0002",loans[1][0],loans[1][2],new Date("2026-07-18"),"cash",300000,20000,0,60000,220000,"posted","CSH-1002"]],"Collections");ws.getRange("G7:G106").format.numberFormat="yyyy-mm-dd";ws.getRange("I7:M106").format.numberFormat=money;ws.getRange("D7:O106").format.font={color:blue};
ws=wb.worksheets.getItem("Portfolio Risk");section(ws,4,"PORTFOLIO AT RISK");table(ws,6,["Loan No.","Borrower","Outstanding Principal","Total Due","Days Past Due","Classification","Provision Rate","Required Provision","Status"],loans.map(x=>[x[0],x[2],x[4]-x[9],x[10],x[11],null,null,null,x[12]]),"PortfolioRisk");for(let r=7;r<=106;r++){ws.getRange(`I${r}`).formulas=[[`=IF(D${r}="","",IF(H${r}=0,"Current",IF(H${r}<=30,"Watch",IF(H${r}<=60,"Substandard",IF(H${r}<=90,"Doubtful","Loss")))))`]];ws.getRange(`J${r}`).formulas=[[`=IF(I${r}="Current",1%,IF(I${r}="Watch",5%,IF(I${r}="Substandard",25%,IF(I${r}="Doubtful",50%,100%))))`]];ws.getRange(`K${r}`).formulas=[[`=IF(D${r}="","",F${r}*J${r})`]];}ws.getRange("F7:G106").format.numberFormat=money;ws.getRange("J7:J106").format.numberFormat="0%";ws.getRange("K7:K106").format.numberFormat=money;ws.getRange("D7:H106").format.font={color:blue};ws.getRange("L7:L106").format.font={color:blue};
const generic={
 "Follow-ups":[["Loan No.","Borrower","Contact Date","Method","Amount Overdue","DPD","Response","Promise Amount","Promise Date","Next Follow-up","Next Action","Status"],[[loans[1][0],loans[1][2],new Date("2026-08-01"),"phone",1900000,18,"Pay after salary",500000,new Date("2026-08-15"),new Date("2026-08-16"),"Call borrower","promise_pending"]]],
 "Loan Servicing":[["Loan No.","Action","Date","Component","Amount","Paid","Waived","Interest Outstanding","Reason","Status"],[[loans[1][0],"penalty",new Date("2026-07-31"),"penalty",50000,20000,0,0,"Late installment","active"]]],
 "Provisioning":[["Loan No.","Date","Classification","Principal","Rate","Required Provision","Posted"],loans.map(x=>[x[0],new Date("2026-08-11"),x[11]>90?"Loss":x[11]>30?"Substandard":x[11]>0?"Watch":"Current",x[4]-x[9],x[11]>90?1:x[11]>30?.25:x[11]>0?.05:.01,(x[4]-x[9])*(x[11]>90?1:x[11]>30?.25:x[11]>0?.05:.01),"No"])],
 "Restructures":[["Loan No.","Borrower","Type","Principal","Old Term","New Term","Old Rate","New Rate","First Due","Reason","Status"],[[loans[2][0],loans[2][2],"term_extension",9000000,18,24,.018,.018,new Date("2026-09-01"),"Seasonal cash-flow pressure","approved"]]],
 "Write-offs":[["Loan No.","Borrower","Write-off Date","Principal","Interest","Fees","Penalties","Reason","Recovery Date","Recovery","Method","Status"],[["LN-2025-000099","Example Borrower",new Date("2026-06-30"),2000000,250000,50000,100000,"Board approved",new Date("2026-08-05"),300000,"mobile_money","partial_recovery"]]],
 "Integration":[["Import ID","Source","Entity","Batch","Started","Completed","Imported","Rejected","Conflicts","Status","Last Error"],[["IMP-001","Field App","borrowers","BATCH-20260810",new Date("2026-08-10T08:00:00Z"),new Date("2026-08-10T08:03:00Z"),145,2,1,"completed","2 invalid phones"]]],
 "Reports":[["Report","Purpose","Primary Page","Open"],[["Borrower register","Client master list","Borrowers",null],["Loan portfolio","Balances and risk","Portfolio Risk",null],["Collections report","Repayment activity","Collections",null],["Cashbook report","Cash movements","Cashbook Register",null]]]
};
for(const [name,[headers,rows]] of Object.entries(generic)){ws=wb.worksheets.getItem(name);section(ws,4,name.toUpperCase());table(ws,6,headers,rows,name.replaceAll(/[^A-Za-z0-9]/g,""));ws.getRange("D7:S106").format.font={color:blue};}
ws=wb.worksheets.getItem("Reports");["Borrowers","Portfolio Risk","Collections","Cashbook Register"].forEach((t,i)=>setLink(ws.getRange(`G${7+i}`),t,"OPEN ▶"));

// Dashboard last so formulas point to final right-hand ranges
ws=wb.worksheets.getItem("Dashboard");section(ws,4,"PORTFOLIO OVERVIEW");const cards=[["D6:G6","D7:G9","Borrowers","=COUNTA('Borrowers'!D7:D106)"],["H6:K6","H7:K9","Gross Portfolio","=SUM('Portfolio Risk'!F7:F106)"],["L6:O6","L7:O9","PAR 30",'=IFERROR(SUMIF(\'Portfolio Risk\'!H7:H106,">=30",\'Portfolio Risk\'!F7:F106)/SUM(\'Portfolio Risk\'!F7:F106),0)'],["P6:S6","P7:S9","Cashbook Balance","='Daily Cashbook'!N8"]];for(const [lr,vr,l,f] of cards){ws.getRange(lr).merge();ws.getRange(lr.split(":")[0]).values=[[l]];ws.getRange(vr).merge();ws.getRange(vr.split(":")[0]).formulas=[[f]];ws.getRange(lr).format={fill:soft,font:{bold:true},horizontalAlignment:"center",borders:{preset:"all",style:"thin",color:black}};ws.getRange(vr).format={font:{bold:true,size:16},horizontalAlignment:"center",verticalAlignment:"center",borders:{preset:"all",style:"medium",color:black}};}ws.getRange("H7:K9").format.numberFormat=money;ws.getRange("L7:O9").format.numberFormat="0.0%";ws.getRange("P7:S9").format.numberFormat=money;

const inspect=await wb.inspect({kind:"workbook,sheet,table",maxChars:8000,tableMaxRows:3,tableMaxCols:8});console.log(inspect.ndjson);const errs=await wb.inspect({kind:"match",searchTerm:"#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A",options:{useRegex:true,maxResults:300},summary:"formula scan"});console.log(errs.ndjson);
for(const [name] of pages){const png=await wb.render({sheetName:name,range:name==="Cashbook Entry"?"A1:S36":"A1:S31",scale:.8,format:"png"});await fs.writeFile(`${outDir}/qa_${name.replaceAll(/[^A-Za-z0-9]/g,"_")}.png`,new Uint8Array(await png.arrayBuffer()));}
const out=await SpreadsheetFile.exportXlsx(wb);await out.save(`${outDir}/BOAT_Microfinance_Module.xlsx`);
