import { useCallback, useEffect, useState } from "react";
import { Plus, Tag } from "lucide-react";
import { supabase } from "@/lib/supabase";

const db = supabase as any;
type Promotion = { id: string; code: string; discount_type: "percentage" | "fixed"; discount_value: number; minimum_order_amount: number; ends_at: string | null; usage_count: number; usage_limit: number | null; is_active: boolean };

export function MarketplacePromotionsPanel({ organizationId, merchantId }: { organizationId: string; merchantId: string }) {
  const [rows, setRows] = useState<Promotion[]>([]);
  const [draft, setDraft] = useState({ code: "", discount_type: "percentage", discount_value: "", minimum_order_amount: "", ends_at: "" });
  const [message, setMessage] = useState<string | null>(null);
  const load = useCallback(async () => { const r = await db.from("marketplace_promotion_codes").select("id,code,discount_type,discount_value,minimum_order_amount,ends_at,usage_count,usage_limit,is_active").eq("merchant_id", merchantId).order("created_at", { ascending: false }); if (r.error) setMessage(r.error.message); else setRows(r.data || []); }, [merchantId]);
  useEffect(() => { void load(); }, [load]);
  const create = async () => { if (!draft.code.trim() || Number(draft.discount_value) <= 0) { setMessage("Enter a code and discount value."); return; } const r = await db.from("marketplace_promotion_codes").insert({ organization_id: organizationId, merchant_id: merchantId, code: draft.code.trim().toUpperCase(), discount_type: draft.discount_type, discount_value: Number(draft.discount_value), minimum_order_amount: Number(draft.minimum_order_amount || 0), ends_at: draft.ends_at ? new Date(`${draft.ends_at}T23:59:59`).toISOString() : null }); if (r.error) setMessage(r.error.message); else { setDraft({ code: "", discount_type: "percentage", discount_value: "", minimum_order_amount: "", ends_at: "" }); setMessage("Promotion code created."); await load(); } };
  const toggle = async (row: Promotion) => { const r = await db.from("marketplace_promotion_codes").update({ is_active: !row.is_active }).eq("id", row.id); if (r.error) setMessage(r.error.message); else await load(); };
  return <section className="mt-6 border-t border-indigo-200 pt-5"><div className="flex items-center gap-2"><Tag className="h-5 w-5 text-indigo-700" /><div><h3 className="font-semibold text-slate-900">Promotions</h3><p className="mt-1 text-sm text-slate-600">Create shopper discount codes for this storefront.</p></div></div>{message && <p className="mt-3 text-sm text-slate-700">{message}</p>}<div className="mt-3 grid gap-2 md:grid-cols-5"><input value={draft.code} onChange={(e) => setDraft((v) => ({ ...v, code: e.target.value }))} placeholder="Code e.g. WELCOME10" className="rounded border border-slate-300 px-2 py-2 text-sm" /><select value={draft.discount_type} onChange={(e) => setDraft((v) => ({ ...v, discount_type: e.target.value }))} className="rounded border border-slate-300 px-2 py-2 text-sm"><option value="percentage">Percentage</option><option value="fixed">Fixed UGX</option></select><input type="number" min="0" value={draft.discount_value} onChange={(e) => setDraft((v) => ({ ...v, discount_value: e.target.value }))} placeholder="Discount" className="rounded border border-slate-300 px-2 py-2 text-sm" /><input type="number" min="0" value={draft.minimum_order_amount} onChange={(e) => setDraft((v) => ({ ...v, minimum_order_amount: e.target.value }))} placeholder="Minimum order" className="rounded border border-slate-300 px-2 py-2 text-sm" /><input type="date" value={draft.ends_at} onChange={(e) => setDraft((v) => ({ ...v, ends_at: e.target.value }))} className="rounded border border-slate-300 px-2 py-2 text-sm" /></div><button type="button" onClick={() => void create()} className="app-btn-secondary mt-3"><Plus className="h-4 w-4" /> Create promotion</button><div className="mt-3 divide-y rounded-lg border border-slate-200 bg-white">{rows.map((row) => <div key={row.id} className="flex flex-wrap items-center justify-between gap-3 p-3 text-sm"><span><strong>{row.code}</strong> · {row.discount_type === "percentage" ? `${row.discount_value}%` : `UGX ${Number(row.discount_value).toLocaleString()}`} · used {row.usage_count}{row.ends_at ? ` · ends ${new Date(row.ends_at).toLocaleDateString()}` : ""}</span><button type="button" onClick={() => void toggle(row)} className={row.is_active ? "text-rose-700" : "text-emerald-700"}>{row.is_active ? "Deactivate" : "Activate"}</button></div>)}{rows.length === 0 && <p className="p-3 text-sm text-slate-500">No promotion codes yet.</p>}</div></section>;
}
