import { Printer } from "lucide-react";
import { APP_SHORT_NAME } from "@/constants/branding";
import type { PayslipDetail } from "@/lib/payrollPayslipPdf";
import { downloadPayslipPdf } from "@/lib/payrollPayslipPdf";

type Props = {
  detail: PayslipDetail;
  printId?: string;
  /** When true, omit toolbar (e.g. standalone print page). */
  hideActions?: boolean;
};

export function PayrollPayslipPanel({ detail, printId = "payroll-payslip-print", hideActions }: Props) {
  const handlePrint = () => window.print();

  return (
    <div className="space-y-4">
      {!hideActions && (
        <div className="flex flex-wrap gap-2 print:hidden">
          <button
            type="button"
            onClick={handlePrint}
            className="inline-flex items-center gap-2 px-4 py-2 bg-slate-900 text-white rounded-lg text-sm font-medium hover:bg-slate-800"
          >
            <Printer className="w-4 h-4 shrink-0" aria-hidden />
            Print
          </button>
          <button
            type="button"
            onClick={() => downloadPayslipPdf(detail)}
            className="px-4 py-2 border border-slate-300 rounded-lg text-sm font-medium hover:bg-slate-50"
          >
            Download PDF
          </button>
        </div>
      )}
      <style>{`
        @page { size: A4; margin: 12mm; }
        @media print {
          body * { visibility: hidden; }
          #${printId}, #${printId} * { visibility: visible; }
          #${printId} {
            position: absolute;
            left: 0;
            top: 0;
            width: 100%;
            padding: 0;
            background: white;
          }
        }
      `}</style>
      <div id={printId} className="border-2 border-slate-800 rounded-sm bg-white p-6 max-w-md print:border-slate-900 print:shadow-none">
        <header className="border-b border-slate-200 pb-4 mb-4">
          <p className="text-lg font-bold text-slate-900">{detail.organizationName || "—"}</p>
          <p className="text-xs text-slate-600 mt-1">
            Period: {detail.periodLabel} ({detail.periodStart} → {detail.periodEnd})
          </p>
          <h2 className="text-xl font-semibold text-slate-900 mt-4">Payslip</h2>
        </header>
        <p className="text-sm text-slate-800">
          <span className="text-slate-600">Employee:</span> {detail.staffName}
        </p>
        {detail.employeeCode ? (
          <p className="text-sm text-slate-800 mt-1">
            <span className="text-slate-600">Code:</span> {detail.employeeCode}
          </p>
        ) : null}
        <dl className="mt-6 space-y-2 text-sm">
          {detail.fullGross != null && (detail.daysAbsent ?? 0) > 0 ? (
            <>
              <PayslipRow label="Full gross (contract)" value={detail.fullGross} />
              <PayslipRow label="Days absent" value={detail.daysAbsent ?? 0} />
              <PayslipRow label="Absent deduction" value={-(detail.absentDeduction ?? 0)} />
            </>
          ) : null}
          <PayslipRow label="Gross pay (taxable)" value={detail.grossPay} />
          <PayslipRow label="PAYE" value={detail.paye} />
          <PayslipRow label="NSSF (employee)" value={detail.nssfEmployee} />
          <PayslipRow label="NSSF (employer)" value={detail.nssfEmployer} />
          <PayslipRow label="Loan / advance" value={detail.loanDeduction} />
          <PayslipRow label="Net pay" value={detail.netPay} strong />
        </dl>
        <p className="text-[10px] text-slate-400 mt-8 pt-3 border-t border-slate-200">
          Generated by {APP_SHORT_NAME}
        </p>
      </div>
    </div>
  );
}

function PayslipRow({ label, value, strong }: { label: string; value: number; strong?: boolean }) {
  return (
    <div className="flex justify-between gap-4">
      <dt className="text-slate-600">{label}</dt>
      <dd className={strong ? "font-semibold text-slate-900" : "text-slate-900"}>
        {Number(value).toLocaleString()}
      </dd>
    </div>
  );
}
