import { useCallback, useEffect, useMemo, useState } from "react";
import { CheckCircle2, Download, FileText, Search, Send, WalletCards } from "lucide-react";
import * as XLSX from "xlsx";
import { supabase } from "@/lib/supabase";
import { useAuth } from "@/contexts/AuthContext";
import { getPayrollAccess } from "@/lib/payrollAccess";
import { logPayrollAudit } from "@/lib/payrollAudit";

type Period = { id: string; label: string; period_start: string; period_end: string };
type Run = { id: string; payroll_period_id: string; status: string; review_notes?: string | null };
type Line = { id: string; staff_id: string; gross_pay: number; paye: number; nssf_employee: number; nssf_employer: number; loan_deduction: number; net_pay: number; staff?: { full_name: string } | null };

function PageHeader({ title, description }: { title: string; description: string }) {
  return <><nav className="text-xs font-medium text-slate-500">School <span className="mx-1 text-slate-300">›</span> Payroll <span className="mx-1 text-slate-300">›</span> <span className="text-slate-700">{title}</span></nav><div><h1 className="text-2xl font-bold tracking-tight text-slate-900">{title}</h1><p className="mt-1 text-sm text-slate-600">{description}</p></div></>;
}

function usePayrollRuns() {
  const { user } = useAuth();
  const orgId = user?.organization_id;
  const [periods, setPeriods] = useState<Period[]>([]);
  const [runs, setRuns] = useState<Run[]>([]);
  const [selectedRunId, setSelectedRunId] = useState("");
  const [lines, setLines] = useState<Line[]>([]);
  const [loading, setLoading] = useState(true);
  const load = useCallback(async () => {
    if (!orgId) return setLoading(false);
    setLoading(true);
    const [p, r] = await Promise.all([
      supabase.from("payroll_periods").select("id,label,period_start,period_end").eq("organization_id", orgId).order("period_end", { ascending: false }),
      supabase.from("payroll_runs").select("id,payroll_period_id,status,review_notes").eq("organization_id", orgId),
    ]);
    setPeriods((p.data as Period[]) ?? []); setRuns((r.data as Run[]) ?? []);
    setSelectedRunId((current) => current || ((r.data as Run[] | null)?.[0]?.id ?? "")); setLoading(false);
  }, [orgId]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => {
    if (!selectedRunId) return setLines([]);
    void supabase.from("payroll_run_lines").select("id,staff_id,gross_pay,paye,nssf_employee,nssf_employer,loan_deduction,net_pay,staff:staff_id(full_name)").eq("payroll_run_id", selectedRunId).then(({ data }) => setLines((data as unknown as Line[]) ?? []));
  }, [selectedRunId]);
  const selectedRun = runs.find((run) => run.id === selectedRunId) ?? null;
  const selectedPeriod = periods.find((period) => period.id === selectedRun?.payroll_period_id) ?? null;
  return { orgId, user, periods, runs, selectedRunId, setSelectedRunId, selectedRun, selectedPeriod, lines, loading, reload: load };
}

function RunPicker({ state }: { state: ReturnType<typeof usePayrollRuns> }) {
  return <div className="rounded-xl border border-slate-200 bg-white p-3"><label className="block text-xs font-medium text-slate-600">Payroll period<select value={state.selectedRunId} onChange={(e) => state.setSelectedRunId(e.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="">Select payroll run</option>{state.periods.map((period) => { const run = state.runs.find((item) => item.payroll_period_id === period.id); return run ? <option key={run.id} value={run.id}>{period.label} · {run.status.replaceAll("_", " ")}</option> : null; })}</select></label></div>;
}

export function PayrollReviewPage({ readOnly }: { readOnly?: boolean }) {
  const state = usePayrollRuns();
  const access = useMemo(() => getPayrollAccess(state.user?.role, readOnly ?? false), [state.user?.role, readOnly]);
  const [notes, setNotes] = useState(""); const [err, setErr] = useState<string | null>(null);
  useEffect(() => setNotes(state.selectedRun?.review_notes ?? ""), [state.selectedRun]);
  const totals = state.lines.reduce((s, l) => ({ gross: s.gross + Number(l.gross_pay), net: s.net + Number(l.net_pay), deductions: s.deductions + Number(l.paye) + Number(l.nssf_employee) + Number(l.loan_deduction) }), { gross: 0, net: 0, deductions: 0 });
  const setStatus = async (status: string) => {
    if (!state.selectedRun || !state.orgId || !state.user?.id) return;
    const payload: Record<string, unknown> = { status, review_notes: notes || null };
    if (status === "under_review") { payload.submitted_at = new Date().toISOString(); payload.submitted_by = state.user?.id; }
    if (status === "approved") { payload.approved_at = new Date().toISOString(); payload.approved_by = state.user?.id; }
    const { error } = await supabase.from("payroll_runs").update(payload).eq("id", state.selectedRun.id); if (error) return setErr(error.message);
    await logPayrollAudit({ organizationId: state.orgId, payrollRunId: state.selectedRun.id, actorStaffId: state.user.id, action: `payroll_${status}`, details: { notes } }); await state.reload();
  };
  return <div className="mx-auto max-w-7xl space-y-5 p-6 lg:p-8"><PageHeader title="Review & Approve" description="Review calculated payroll, record exceptions and approve it before payment or posting."/><RunPicker state={state}/>{err && <p className="text-sm text-red-600">{err}</p>}{state.selectedRun && <><div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[["Employees",state.lines.length],["Gross payroll",totals.gross],["Deductions",totals.deductions],["Net pay",totals.net]].map(([label,value]) => <div key={String(label)} className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 text-xl font-bold tabular-nums">{Number(value).toLocaleString()}</p></div>)}</div><div className="rounded-xl border border-slate-200 bg-white p-4"><label className="text-sm font-medium text-slate-700">Review notes<textarea value={notes} onChange={(e) => setNotes(e.target.value)} className="mt-1 min-h-24 w-full rounded-lg border border-slate-300 p-3 text-sm" placeholder="Record exceptions, checks and approval comments"/></label><div className="mt-3 flex flex-wrap gap-2"><button disabled={!access.canPrepare || state.selectedRun.status !== "calculated"} onClick={() => void setStatus("under_review")} className="rounded-lg border border-blue-300 bg-blue-50 px-3 py-2 text-sm font-medium text-blue-800 disabled:opacity-40"><Send className="mr-1 inline h-4 w-4"/>Submit for review</button><button disabled={!access.canApproveForPayment || !["calculated","under_review"].includes(state.selectedRun.status)} onClick={() => void setStatus("approved")} className="rounded-lg bg-emerald-700 px-3 py-2 text-sm font-medium text-white disabled:opacity-40"><CheckCircle2 className="mr-1 inline h-4 w-4"/>Approve payroll</button></div></div><PayrollLinesTable lines={state.lines}/></>}</div>;
}

type Payment = { id: string; staff_id: string; amount: number; payment_method: string; status: string; payment_reference: string | null; failure_reason: string | null };
export function PayrollPaymentsPage({ readOnly }: { readOnly?: boolean }) {
  const state = usePayrollRuns(); const [payments, setPayments] = useState<Payment[]>([]); const [err, setErr] = useState<string | null>(null);
  const loadPayments = useCallback(async () => { if (!state.selectedRunId) return setPayments([]); const { data } = await supabase.from("payroll_payments").select("*").eq("payroll_run_id", state.selectedRunId); setPayments((data as Payment[]) ?? []); }, [state.selectedRunId]);
  useEffect(() => { void loadPayments(); }, [loadPayments]);
  const prepare = async () => { if (!state.selectedRun || !state.orgId) return; const profiles = await supabase.from("payroll_employee_profiles").select("staff_id,payment_method").eq("organization_id", state.orgId); const methods = new Map((profiles.data ?? []).map((p) => [p.staff_id, p.payment_method])); const rows = state.lines.map((l) => ({ organization_id: state.orgId, payroll_run_id: state.selectedRun!.id, staff_id: l.staff_id, amount: l.net_pay, payment_method: methods.get(l.staff_id) ?? "bank", status: "pending" })); const { error } = await supabase.from("payroll_payments").upsert(rows, { onConflict: "payroll_run_id,staff_id" }); if (error) setErr(error.message); else void loadPayments(); };
  const update = async (payment: Payment, patch: Partial<Payment>) => { if (readOnly) return; const { error } = await supabase.from("payroll_payments").update({ ...patch, paid_at: patch.status === "paid" ? new Date().toISOString() : undefined }).eq("id", payment.id); if (error) return setErr(error.message); if (patch.status === "paid" && state.selectedRun) { const { data } = await supabase.from("payroll_payments").select("status").eq("payroll_run_id", state.selectedRun.id); if ((data ?? []).length > 0 && (data ?? []).every((row) => row.status === "paid")) await supabase.from("payroll_runs").update({ status: "paid", paid_at: new Date().toISOString() }).eq("id", state.selectedRun.id); } void loadPayments(); };
  const exportSchedule = () => exportWorkbook(`payroll-payment-${state.selectedPeriod?.label ?? "schedule"}`, payments.map((p) => ({ Employee: state.lines.find((l) => l.staff_id === p.staff_id)?.staff?.full_name ?? p.staff_id, Amount: p.amount, Method: p.payment_method, Status: p.status, Reference: p.payment_reference ?? "" })));
  return <div className="mx-auto max-w-7xl space-y-5 p-6 lg:p-8"><PageHeader title="Payments" description="Prepare bank, mobile-money or cash schedules and track payment outcomes."/><RunPicker state={state}/>{err && <p className="text-sm text-red-600">{err}</p>}<div className="flex flex-wrap gap-2"><button disabled={readOnly || !state.selectedRun || !["approved","paid","posted"].includes(state.selectedRun.status)} onClick={() => void prepare()} className="rounded-lg bg-slate-900 px-3 py-2 text-sm font-medium text-white disabled:opacity-40"><WalletCards className="mr-1 inline h-4 w-4"/>Prepare payment schedule</button><button disabled={!payments.length} onClick={exportSchedule} className="rounded-lg border border-slate-300 px-3 py-2 text-sm"><Download className="mr-1 inline h-4 w-4"/>Export schedule</button></div><div className="overflow-x-auto rounded-xl border border-slate-200 bg-white"><table className="w-full min-w-[850px] text-sm"><thead className="bg-slate-50"><tr>{["Employee","Amount","Method","Status","Reference","Issue"].map((h)=><th key={h} className="p-3 text-left font-semibold text-slate-700">{h}</th>)}</tr></thead><tbody>{payments.map((p)=><tr key={p.id} className="border-t border-slate-100"><td className="p-3">{state.lines.find((l)=>l.staff_id===p.staff_id)?.staff?.full_name ?? p.staff_id}</td><td className="p-3 text-right tabular-nums">{Number(p.amount).toLocaleString()}</td><td className="p-3 capitalize">{p.payment_method.replace("_"," ")}</td><td className="p-3"><select disabled={readOnly} value={p.status} onChange={(e)=>void update(p,{status:e.target.value})} className="rounded border border-slate-300 px-2 py-1"><option>pending</option><option>processing</option><option>paid</option><option>failed</option><option>returned</option></select></td><td className="p-3"><input disabled={readOnly} defaultValue={p.payment_reference ?? ""} onBlur={(e)=>void update(p,{payment_reference:e.target.value})} className="w-36 rounded border border-slate-300 px-2 py-1"/></td><td className="p-3"><input disabled={readOnly} defaultValue={p.failure_reason ?? ""} onBlur={(e)=>void update(p,{failure_reason:e.target.value})} className="w-40 rounded border border-slate-300 px-2 py-1"/></td></tr>)}{!payments.length&&<tr><td colSpan={6} className="p-8 text-center text-slate-500">Prepare a schedule after payroll approval.</td></tr>}</tbody></table></div></div>;
}

type Remittance = { id: string; liability_type: string; amount_calculated: number; amount_paid: number; due_date: string | null; payment_reference: string | null };
export function PayrollStatutoryPage({ readOnly }: { readOnly?: boolean }) {
  const state = usePayrollRuns(); const [rows,setRows]=useState<Remittance[]>([]); const [err,setErr]=useState<string|null>(null);
  const loadRows=useCallback(async()=>{if(!state.selectedRunId)return setRows([]);const {data}=await supabase.from("payroll_statutory_remittances").select("*").eq("payroll_run_id",state.selectedRunId);setRows((data as Remittance[])??[]);},[state.selectedRunId]); useEffect(()=>{void loadRows();},[loadRows]);
  const prepare=async()=>{if(!state.selectedRun||!state.orgId)return;const sum=(key:"paye"|"nssf_employee"|"nssf_employer")=>state.lines.reduce((s,l)=>s+Number(l[key]||0),0);const payload=(["paye","nssf_employee","nssf_employer"] as const).map(type=>({organization_id:state.orgId,payroll_run_id:state.selectedRun!.id,liability_type:type,amount_calculated:sum(type),amount_paid:0}));const {error}=await supabase.from("payroll_statutory_remittances").upsert(payload,{onConflict:"payroll_run_id,liability_type"});if(error)setErr(error.message);else void loadRows();};
  const update=async(row:Remittance,patch:Partial<Remittance>)=>{if(readOnly)return;const {error}=await supabase.from("payroll_statutory_remittances").update(patch).eq("id",row.id);if(error)setErr(error.message);else void loadRows();};
  return <div className="mx-auto max-w-7xl space-y-5 p-6 lg:p-8"><PageHeader title="Statutory Deductions" description="Track PAYE, NSSF and other payroll liabilities from calculation through remittance."/><RunPicker state={state}/>{err&&<p className="text-sm text-red-600">{err}</p>}<button disabled={readOnly||!state.selectedRun} onClick={()=>void prepare()} className="rounded-lg bg-slate-900 px-3 py-2 text-sm font-medium text-white disabled:opacity-40">Prepare liabilities</button><div className="overflow-x-auto rounded-xl border border-slate-200 bg-white"><table className="w-full text-sm"><thead className="bg-slate-50"><tr>{["Liability","Calculated","Paid","Outstanding","Due date","Reference"].map(h=><th key={h} className="p-3 text-left font-semibold text-slate-700">{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t"><td className="p-3 font-medium uppercase">{r.liability_type.replace("_"," ")}</td><td className="p-3 text-right">{Number(r.amount_calculated).toLocaleString()}</td><td className="p-3"><input disabled={readOnly} type="number" defaultValue={r.amount_paid} onBlur={e=>void update(r,{amount_paid:Number(e.target.value)})} className="w-32 rounded border px-2 py-1 text-right"/></td><td className="p-3 text-right font-medium">{(Number(r.amount_calculated)-Number(r.amount_paid)).toLocaleString()}</td><td className="p-3"><input disabled={readOnly} type="date" defaultValue={r.due_date??""} onBlur={e=>void update(r,{due_date:e.target.value})} className="rounded border px-2 py-1"/></td><td className="p-3"><input disabled={readOnly} defaultValue={r.payment_reference??""} onBlur={e=>void update(r,{payment_reference:e.target.value})} className="rounded border px-2 py-1"/></td></tr>)}{!rows.length&&<tr><td colSpan={6} className="p-8 text-center text-slate-500">Select a calculated payroll and prepare liabilities.</td></tr>}</tbody></table></div></div>;
}

const reportDefinitions=["Employee Register","Salary Register","Payslips","Employee Earnings History","Payroll Summary","Department Payroll Cost","Teaching vs Non-teaching Cost","Payroll Variance","Allowances and Deductions Analysis","PAYE Schedule","NSSF Schedule","Local Service Tax Schedule","Bank Payment Schedule","Loan and Advance Balances","Payroll Journal","Payroll Control Account","Unpaid Salaries","Statutory Liability Reconciliation"];
export function PayrollReportsPage(){const state=usePayrollRuns();const [search,setSearch]=useState("");const visible=reportDefinitions.filter(r=>r.toLowerCase().includes(search.toLowerCase()));const exportReport=(name:string)=>exportWorkbook(name,state.lines.map(l=>({Employee:l.staff?.full_name??l.staff_id,Gross:l.gross_pay,PAYE:l.paye,"NSSF employee":l.nssf_employee,"NSSF employer":l.nssf_employer,Loan:l.loan_deduction,"Net pay":l.net_pay})));return <div className="mx-auto max-w-7xl space-y-5 p-6 lg:p-8"><PageHeader title="Payroll Reports" description="Review payroll costs, employee payments, statutory deductions and accounting outputs."/><RunPicker state={state}/><label className="relative block"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search payroll reports" className="w-full rounded-lg border border-slate-300 py-2 pl-9 pr-3 text-sm"/></label><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{visible.map(name=><button key={name} onClick={()=>exportReport(name)} className="flex items-center justify-between rounded-xl border border-slate-200 bg-white p-4 text-left hover:border-teal-300"><span><FileText className="mb-2 h-5 w-5 text-teal-700"/><strong className="block text-sm text-slate-900">{name}</strong><small className="text-slate-500">Export for {state.selectedPeriod?.label??"selected period"}</small></span><Download className="h-4 w-4 text-slate-400"/></button>)}</div></div>}

function PayrollLinesTable({lines}:{lines:Line[]}){return <div className="overflow-x-auto rounded-xl border border-slate-200 bg-white"><table className="w-full min-w-[800px] text-sm"><thead className="bg-slate-50"><tr>{["Employee","Gross","PAYE","NSSF employee","NSSF employer","Loan","Net pay"].map(h=><th key={h} className="p-3 text-left font-semibold text-slate-700">{h}</th>)}</tr></thead><tbody>{lines.map(l=><tr key={l.id} className="border-t"><td className="p-3">{l.staff?.full_name??l.staff_id}</td>{[l.gross_pay,l.paye,l.nssf_employee,l.nssf_employer,l.loan_deduction,l.net_pay].map((v,i)=><td key={i} className="p-3 text-right tabular-nums">{Number(v).toLocaleString()}</td>)}</tr>)}</tbody></table></div>}
function exportWorkbook(name:string,rows:Record<string,unknown>[]){const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),"Report");XLSX.writeFile(wb,`${name.replace(/[^a-z0-9]+/gi,"-").toLowerCase()}.xlsx`);}
