import { useEffect, useState } from "react";
import { FileText, Shield } from "lucide-react";
import { supabase } from "@/lib/supabase";

export function InsuranceCustomerPortal({ customerId }: { customerId: string }) {
  const [tab, setTab] = useState<"overview" | "quotes" | "policies">("overview");
  const [quotes, setQuotes] = useState<any[]>([]); const [policies, setPolicies] = useState<any[]>([]);
  useEffect(() => { void supabase.rpc("insurance_portal_mark_login"); void Promise.all([
    supabase.from("insurance_quotes").select("id,product_category,sum_insured,status,kyc_status,payment_status,insurance_quote_options(provider_name,cover_name,premium_amount,selected)").eq("customer_id", customerId).order("requested_at", { ascending: false }),
    supabase.from("insurance_policies").select("policy_number,product_name,insurer_name,premium_amount,start_date,expiry_date,status").eq("customer_id", customerId).order("expiry_date"),
  ]).then(([q,p]) => { setQuotes(q.data || []); setPolicies(p.data || []); }); }, [customerId]);
  return <main className="mx-auto max-w-4xl space-y-5 p-4 sm:p-8"><header><p className="text-sm font-semibold text-blue-700">BOAT Insurance</p><h1 className="text-2xl font-bold">My Insurance</h1><p className="text-sm text-slate-600">Get cover, compare your available quotations and manage your policies.</p></header><nav className="flex gap-2 border-b">{(["overview","quotes","policies"] as const).map((v) => <button key={v} onClick={() => setTab(v)} className={`border-b-2 px-3 py-2 text-sm font-semibold capitalize ${tab===v?"border-blue-700 text-blue-700":"border-transparent text-slate-600"}`}>{v === "quotes" ? "My Quotes" : v === "policies" ? "My Policies" : "Overview"}</button>)}</nav>{tab === "overview" && <div className="grid gap-4 sm:grid-cols-2"><Card icon={<FileText/>} title="Quotes awaiting action" value={String(quotes.filter(q=>q.status!=="accepted").length)}/><Card icon={<Shield/>} title="Active policies" value={String(policies.filter(p=>p.status==="active").length)}/></div>}{tab === "quotes" && <List rows={quotes} empty="You have no quote requests yet." render={(q) => <><strong>{q.product_category}</strong><span>{q.status} · KYC: {q.kyc_status} · Payment: {q.payment_status}</span>{q.insurance_quote_options?.filter((o:any)=>o.selected).map((o:any)=><span key={o.provider_name}>Selected: {o.provider_name} — {o.cover_name}</span>)}</>}/>} {tab === "policies" && <List rows={policies} empty="You have no issued policies yet." render={(p) => <><strong>{p.policy_number} — {p.product_name}</strong><span>{p.insurer_name} · {p.status} · Expires {p.expiry_date || "—"}</span></>}/>}</main>;
}
function Card({icon,title,value}:{icon:React.ReactNode;title:string;value:string}){return <div className="rounded-xl border bg-white p-5"><div className="flex gap-2 text-blue-700">{icon}<span className="text-sm font-semibold text-slate-700">{title}</span></div><p className="mt-3 text-3xl font-bold">{value}</p></div>}
function List({rows,empty,render}:{rows:any[];empty:string;render:(row:any)=>React.ReactNode}){return <section className="divide-y rounded-xl border bg-white">{rows.length?rows.map((r,i)=><div key={r.id||i} className="flex flex-col gap-1 p-4 text-sm">{render(r)}</div>):<p className="p-8 text-center text-sm text-slate-500">{empty}</p>}</section>}
