#Requires -Version 5.1
<#
  BOAT school server operator script.

  Actions:
    init    - create deploy/compose.env for the local Postgres + API stack
    start   - docker compose up -d --build
    stop    - docker compose down
    status  - show compose status and health endpoints
    migrate - apply supabase/migrations/*.sql through the Postgres container
    backup  - create a plain SQL pg_dump in .runtime/school-server-backups
    start/status use deploy/docker-compose.offline.yml when deploy/docker-images/*.tar is present.

  Examples:
    powershell -ExecutionPolicy Bypass -File .\scripts\school-server.ps1 -Action init -Mode lan
    powershell -ExecutionPolicy Bypass -File .\scripts\school-server.ps1 -Action init -Mode wan -CorsOrigin "https://school.example.com"
    powershell -ExecutionPolicy Bypass -File .\scripts\school-server.ps1 -Action start
    powershell -ExecutionPolicy Bypass -File .\scripts\school-server.ps1 -Action migrate
#>

param(
  [ValidateSet("init", "start", "stop", "status", "migrate", "backup", "restore")]
  [string]$Action = "status",

  [ValidateSet("lan", "wan")]
  [string]$Mode = "lan",

  [int]$ApiPort = 3001,
  [int]$PostgresPort = 5432,
  [string]$PostgresUser = "boat",
  [string]$PostgresDb = "boat",
  [string]$PostgresPassword = "",
  [string]$CorsOrigin = "",
  [switch]$AllowFirewall,
  [string]$RestoreFile = ""
)

$ErrorActionPreference = "Stop"

$RepoRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
$DeployDir = Join-Path $RepoRoot "deploy"
$ComposeFile = Join-Path $DeployDir "docker-compose.yml"
$ComposeEnv = Join-Path $DeployDir "compose.env"
$ComposeEnvExample = Join-Path $DeployDir "compose.env.example"
$OfflineComposeFile = Join-Path $DeployDir "docker-compose.offline.yml"
$DockerImagesDir = Join-Path $DeployDir "docker-images"
$RuntimeDir = Join-Path $RepoRoot ".runtime"
$BackupDir = Join-Path $RuntimeDir "school-server-backups"
$MigrationsDir = Join-Path $RepoRoot "supabase\migrations"

function Assert-Docker {
  $docker = Get-Command docker -ErrorAction SilentlyContinue
  if (-not $docker) {
    throw "docker not found on PATH. Install Docker Desktop or Docker Engine and try again."
  }
}

function Test-OfflineDockerImages {
  if (-not (Test-Path $DockerImagesDir)) {
    return $false
  }
  return $null -ne (Get-ChildItem -Path $DockerImagesDir -Filter "*.tar" -File -ErrorAction SilentlyContinue | Select-Object -First 1)
}

function Load-OfflineDockerImages {
  if (-not (Test-OfflineDockerImages)) {
    return
  }
  Assert-Docker
  foreach ($file in Get-ChildItem -Path $DockerImagesDir -Filter "*.tar" -File | Sort-Object Name) {
    Write-Host "Loading offline Docker image bundle: $($file.FullName)"
    & docker load -i $file.FullName
    if ($LASTEXITCODE -ne 0) {
      throw "docker load failed for $($file.FullName)"
    }
  }
}

function Get-ComposeFileArgs {
  $args = @("-f", $ComposeFile)
  if ((Test-OfflineDockerImages) -and (Test-Path $OfflineComposeFile)) {
    $args += @("-f", $OfflineComposeFile)
  }
  return $args
}

function Invoke-Compose {
  param([string[]]$Args)
  Assert-Docker
  Push-Location $RepoRoot
  try {
    $composeFiles = Get-ComposeFileArgs
    & docker compose @composeFiles --env-file $ComposeEnv @Args
    if ($LASTEXITCODE -ne 0) {
      throw "docker compose failed with exit code $LASTEXITCODE"
    }
  } finally {
    Pop-Location
  }
}

function New-RandomPassword {
  $bytes = New-Object byte[] 24
  $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
  try {
    $rng.GetBytes($bytes)
  } finally {
    $rng.Dispose()
  }
  return ([Convert]::ToBase64String($bytes) -replace "[+/=]", "").Substring(0, 24)
}

function Read-EnvFile {
  param([string]$Path)
  $map = [ordered]@{}
  if (-not (Test-Path $Path)) {
    return $map
  }
  foreach ($line in Get-Content -Path $Path) {
    $trimmed = $line.Trim()
    if ($trimmed -eq "" -or $trimmed.StartsWith("#")) {
      continue
    }
    $idx = $trimmed.IndexOf("=")
    if ($idx -le 0) {
      continue
    }
    $key = $trimmed.Substring(0, $idx).Trim()
    $value = $trimmed.Substring($idx + 1).Trim()
    $map[$key] = $value
  }
  return $map
}

function Write-EnvFile {
  param(
    [string]$Path,
    [System.Collections.IDictionary]$Values
  )
  $lines = @(
    "# BOAT school server local stack",
    "# Generated by scripts/school-server.ps1",
    "POSTGRES_USER=$($Values["POSTGRES_USER"])",
    "POSTGRES_PASSWORD=$($Values["POSTGRES_PASSWORD"])",
    "POSTGRES_DB=$($Values["POSTGRES_DB"])",
    "POSTGRES_PORT=$($Values["POSTGRES_PORT"])",
    "API_PORT=$($Values["API_PORT"])",
    "CORS_ORIGIN=$($Values["CORS_ORIGIN"])"
  )
  Set-Content -Path $Path -Value $lines -Encoding ASCII
}

function Get-LocalIPv4 {
  $addresses = @()
  try {
    $addresses = Get-NetIPAddress -AddressFamily IPv4 -ErrorAction Stop |
      Where-Object {
        $_.IPAddress -notlike "127.*" -and
        $_.IPAddress -notlike "169.254.*" -and
        $_.PrefixOrigin -ne "WellKnown"
      } |
      Select-Object -ExpandProperty IPAddress
  } catch {
    $addresses = @()
  }
  return @($addresses)
}

function Ensure-ComposeEnv {
  if (-not (Test-Path $DeployDir)) {
    throw "Missing deploy folder: $DeployDir"
  }
  if (-not (Test-Path $ComposeFile)) {
    throw "Missing Docker Compose file: $ComposeFile"
  }
  if (-not (Test-Path $ComposeEnv)) {
    if (-not (Test-Path $ComposeEnvExample)) {
      throw "Missing compose env example: $ComposeEnvExample"
    }
    Copy-Item $ComposeEnvExample $ComposeEnv
  }

  $envMap = Read-EnvFile $ComposeEnv
  if (-not $envMap.Contains("POSTGRES_USER")) { $envMap["POSTGRES_USER"] = $PostgresUser }
  if (-not $envMap.Contains("POSTGRES_DB")) { $envMap["POSTGRES_DB"] = $PostgresDb }
  if (-not $envMap.Contains("POSTGRES_PORT")) { $envMap["POSTGRES_PORT"] = "$PostgresPort" }
  if (-not $envMap.Contains("API_PORT")) { $envMap["API_PORT"] = "$ApiPort" }
  if (-not $envMap.Contains("POSTGRES_PASSWORD")) { $envMap["POSTGRES_PASSWORD"] = "change-me-in-production" }
  if (-not $envMap.Contains("CORS_ORIGIN")) { $envMap["CORS_ORIGIN"] = "" }

  if ($PostgresUser) { $envMap["POSTGRES_USER"] = $PostgresUser }
  if ($PostgresDb) { $envMap["POSTGRES_DB"] = $PostgresDb }
  $envMap["POSTGRES_PORT"] = "$PostgresPort"
  $envMap["API_PORT"] = "$ApiPort"

  if ($PostgresPassword.Trim()) {
    $envMap["POSTGRES_PASSWORD"] = $PostgresPassword.Trim()
  } elseif ($envMap["POSTGRES_PASSWORD"] -eq "change-me-in-production" -or -not $envMap["POSTGRES_PASSWORD"]) {
    $envMap["POSTGRES_PASSWORD"] = New-RandomPassword
  }

  if ($Mode -eq "wan") {
    if (-not $CorsOrigin.Trim()) {
      throw "WAN mode requires -CorsOrigin, for example https://school.example.com"
    }
    $envMap["CORS_ORIGIN"] = $CorsOrigin.Trim()
  } elseif ($CorsOrigin.Trim()) {
    $envMap["CORS_ORIGIN"] = $CorsOrigin.Trim()
  } else {
    $envMap["CORS_ORIGIN"] = "*"
  }

  Write-EnvFile $ComposeEnv $envMap
  return $envMap
}

function Add-FirewallRule {
  param([int]$Port)
  $ruleName = "BOAT School API $Port"
  $existing = Get-NetFirewallRule -DisplayName $ruleName -ErrorAction SilentlyContinue
  if ($existing) {
    Write-Host "Firewall rule already exists: $ruleName"
    return
  }
  New-NetFirewallRule `
    -DisplayName $ruleName `
    -Direction Inbound `
    -Action Allow `
    -Protocol TCP `
    -LocalPort $Port `
    -Profile Private |
    Out-Null
  Write-Host "Added Windows Firewall rule: $ruleName (Private profile)"
}

function Show-ConnectionInfo {
  param([System.Collections.IDictionary]$EnvMap)
  $apiPortValue = [int]$EnvMap["API_PORT"]
  $ips = Get-LocalIPv4

  Write-Host ""
  Write-Host "BOAT school API URLs:"
  Write-Host "  Local: http://127.0.0.1:$apiPortValue"
  foreach ($ip in $ips) {
    Write-Host "  LAN:   http://$ip`:$apiPortValue"
  }
  if ($ips.Count -eq 0) {
    Write-Host "  LAN:   No non-loopback IPv4 address found. Check the server PC network connection."
  }
  Write-Host ""
  Write-Host "Set client BOAT Desktop school API mode to the LAN URL for this server PC."
}

function Invoke-HealthCheck {
  param([int]$Port)
  foreach ($path in @("health", "ready")) {
    $url = "http://127.0.0.1:$Port/$path"
    try {
      $res = Invoke-WebRequest -UseBasicParsing -Uri $url -TimeoutSec 8
      Write-Host "$url -> HTTP $($res.StatusCode)"
    } catch {
      Write-Host "$url -> $($_.Exception.Message)" -ForegroundColor Yellow
    }
  }
}

function Invoke-Migrations {
  $envMap = Ensure-ComposeEnv
  Invoke-Compose -Args @("up", "-d", "postgres")
  $files = @(Get-ChildItem $MigrationsDir -Filter "*.sql" | Sort-Object Name)
  if ($files.Count -eq 0) {
    throw "No SQL migrations found in $MigrationsDir"
  }

  Write-Host "Applying $($files.Count) migration file(s) through the postgres container..."
  foreach ($file in $files) {
    Write-Host "  -> $($file.Name)"
    Get-Content -Path $file.FullName -Raw |
      docker compose -f $ComposeFile --env-file $ComposeEnv exec -T postgres `
        psql -v ON_ERROR_STOP=1 -U $envMap["POSTGRES_USER"] -d $envMap["POSTGRES_DB"]
    if ($LASTEXITCODE -ne 0) {
      throw "Migration failed: $($file.Name)"
    }
  }
  Write-Host "Migrations complete."
}

function Invoke-Backup {
  $envMap = Ensure-ComposeEnv
  if (-not (Test-Path $BackupDir)) {
    New-Item -ItemType Directory -Path $BackupDir | Out-Null
  }
  $stamp = Get-Date -Format "yyyyMMdd-HHmmss"
  $backupFile = Join-Path $BackupDir "boat-school-$stamp.sql"

  Write-Host "Creating backup: $backupFile"
  Push-Location $RepoRoot
  try {
    docker compose -f $ComposeFile --env-file $ComposeEnv exec -T postgres `
      pg_dump -U $envMap["POSTGRES_USER"] -d $envMap["POSTGRES_DB"] --clean --if-exists |
      Set-Content -Path $backupFile -Encoding UTF8
    if ($LASTEXITCODE -ne 0) {
      throw "pg_dump failed with exit code $LASTEXITCODE"
    }
  } finally {
    Pop-Location
  }
  Write-Host "Backup complete: $backupFile"
}

function Invoke-Restore {
  param([string]$Path)
  if (-not $Path.Trim()) {
    throw "Restore requires -RestoreFile C:\path\to\backup.sql"
  }
  if (-not (Test-Path $Path)) {
    throw "Restore file not found: $Path"
  }
  $envMap = Ensure-ComposeEnv
  Load-OfflineDockerImages
  Invoke-Compose -Args @("up", "-d", "postgres")
  Write-Host "Restoring database from: $Path"
  Get-Content -Path $Path -Raw |
    docker compose -f $ComposeFile --env-file $ComposeEnv exec -T postgres `
      psql -v ON_ERROR_STOP=1 -U $envMap["POSTGRES_USER"] -d $envMap["POSTGRES_DB"]
  if ($LASTEXITCODE -ne 0) {
    throw "Restore failed with exit code $LASTEXITCODE"
  }
  Write-Host "Restore complete."
}

switch ($Action) {
  "init" {
    $envMap = Ensure-ComposeEnv
    if ($AllowFirewall) {
      Add-FirewallRule -Port ([int]$envMap["API_PORT"])
    }
    Write-Host "Created/updated $ComposeEnv"
    Write-Host "Mode: $Mode"
    Show-ConnectionInfo -EnvMap $envMap
  }
  "start" {
    $envMap = Ensure-ComposeEnv
    Load-OfflineDockerImages
    Invoke-Compose -Args @("up", "-d", "--build")
    Show-ConnectionInfo -EnvMap $envMap
    Invoke-HealthCheck -Port ([int]$envMap["API_PORT"])
  }
  "stop" {
    Ensure-ComposeEnv | Out-Null
    Invoke-Compose -Args @("down")
  }
  "status" {
    $envMap = Ensure-ComposeEnv
    Invoke-Compose -Args @("ps")
    Invoke-HealthCheck -Port ([int]$envMap["API_PORT"])
    Show-ConnectionInfo -EnvMap $envMap
  }
  "migrate" {
    Load-OfflineDockerImages
    Invoke-Migrations
  }
  "backup" {
    Invoke-Backup
  }
  "restore" {
    Invoke-Restore -Path $RestoreFile
  }
}
