-- Phase 3 advanced professional-practice controls.

CREATE TABLE IF NOT EXISTS public.practice_working_papers (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,client_id uuid NOT NULL REFERENCES public.practice_clients(id) ON DELETE CASCADE,engagement_id uuid NOT NULL REFERENCES public.practice_engagements(id) ON DELETE CASCADE,
 reference_code text NOT NULL,title text NOT NULL,category text NOT NULL DEFAULT 'Working paper',objective text,conclusion text,file_name text,storage_path text,
 prepared_by uuid REFERENCES public.staff(id) ON DELETE SET NULL,reviewer_id uuid REFERENCES public.staff(id) ON DELETE SET NULL,status text NOT NULL DEFAULT 'draft' CHECK(status IN('draft','prepared','under_review','reviewed','approved','locked')),
 prepared_at timestamptz,reviewed_at timestamptz,approved_at timestamptz,locked_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(engagement_id,reference_code)
);
CREATE TABLE IF NOT EXISTS public.practice_kyc_checks (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,client_id uuid NOT NULL REFERENCES public.practice_clients(id) ON DELETE CASCADE,
 check_type text NOT NULL,result text NOT NULL DEFAULT 'pending' CHECK(result IN('pending','clear','review_required','failed','expired')),risk_rating text NOT NULL DEFAULT 'normal',evidence_notes text,checked_by uuid REFERENCES public.staff(id) ON DELETE SET NULL,checked_at timestamptz,expires_at date,created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.practice_conflict_checks (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,client_id uuid NOT NULL REFERENCES public.practice_clients(id) ON DELETE CASCADE,engagement_id uuid REFERENCES public.practice_engagements(id) ON DELETE CASCADE,
 search_terms text NOT NULL,result text NOT NULL DEFAULT 'pending' CHECK(result IN('pending','clear','potential_conflict','conflict','waived')),findings text,waiver_reason text,checked_by uuid REFERENCES public.staff(id) ON DELETE SET NULL,checked_at timestamptz,created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.practice_e_signatures (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,client_id uuid NOT NULL REFERENCES public.practice_clients(id) ON DELETE CASCADE,proposal_id uuid REFERENCES public.practice_proposals(id) ON DELETE SET NULL,engagement_id uuid REFERENCES public.practice_engagements(id) ON DELETE SET NULL,signoff_id uuid REFERENCES public.practice_client_signoffs(id) ON DELETE SET NULL,
 document_title text NOT NULL,document_hash text,signer_name text NOT NULL,signer_email text,signature_method text NOT NULL DEFAULT 'typed_consent',consent_text text NOT NULL,signed_at timestamptz NOT NULL DEFAULT now(),created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.practice_wip_schedules (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,engagement_id uuid NOT NULL REFERENCES public.practice_engagements(id) ON DELETE CASCADE,period_end date NOT NULL,
 completion_percent numeric(8,2) NOT NULL DEFAULT 0 CHECK(completion_percent BETWEEN 0 AND 100),earned_revenue numeric(18,2) NOT NULL DEFAULT 0,amount_billed numeric(18,2) NOT NULL DEFAULT 0,unbilled_revenue numeric(18,2) NOT NULL DEFAULT 0,deferred_revenue numeric(18,2) NOT NULL DEFAULT 0,write_down numeric(18,2) NOT NULL DEFAULT 0,
 recognition_method text NOT NULL DEFAULT 'percentage_of_completion',notes text,prepared_by uuid REFERENCES public.staff(id) ON DELETE SET NULL,approved_by uuid REFERENCES public.staff(id) ON DELETE SET NULL,status text NOT NULL DEFAULT 'draft' CHECK(status IN('draft','submitted','approved','posted')),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(engagement_id,period_end)
);
CREATE TABLE IF NOT EXISTS public.practice_document_classifications (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,document_id uuid REFERENCES public.practice_documents(id) ON DELETE CASCADE,engagement_id uuid REFERENCES public.practice_engagements(id) ON DELETE SET NULL,suggested_category text NOT NULL,confidence numeric(5,2) NOT NULL DEFAULT 0,extracted_tags text[] NOT NULL DEFAULT '{}',classification_source text NOT NULL DEFAULT 'rules',review_status text NOT NULL DEFAULT 'suggested' CHECK(review_status IN('suggested','accepted','corrected','rejected')),reviewed_by uuid REFERENCES public.staff(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.practice_engagement_summaries (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,engagement_id uuid NOT NULL REFERENCES public.practice_engagements(id) ON DELETE CASCADE,summary_type text NOT NULL DEFAULT 'management',content text NOT NULL,generation_source text NOT NULL DEFAULT 'structured_draft',status text NOT NULL DEFAULT 'draft' CHECK(status IN('draft','reviewed','published')),generated_by uuid REFERENCES public.staff(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_working_papers_engagement ON public.practice_working_papers(engagement_id,reference_code);CREATE INDEX IF NOT EXISTS idx_kyc_expiry ON public.practice_kyc_checks(organization_id,result,expires_at);CREATE INDEX IF NOT EXISTS idx_conflicts_client ON public.practice_conflict_checks(client_id,result);CREATE INDEX IF NOT EXISTS idx_wip_period ON public.practice_wip_schedules(organization_id,period_end,status);CREATE INDEX IF NOT EXISTS idx_summaries_engagement ON public.practice_engagement_summaries(engagement_id,created_at DESC);
ALTER TABLE public.practice_working_papers ENABLE ROW LEVEL SECURITY;ALTER TABLE public.practice_kyc_checks ENABLE ROW LEVEL SECURITY;ALTER TABLE public.practice_conflict_checks ENABLE ROW LEVEL SECURITY;ALTER TABLE public.practice_e_signatures ENABLE ROW LEVEL SECURITY;ALTER TABLE public.practice_wip_schedules ENABLE ROW LEVEL SECURITY;ALTER TABLE public.practice_document_classifications ENABLE ROW LEVEL SECURITY;ALTER TABLE public.practice_engagement_summaries ENABLE ROW LEVEL SECURITY;
DO $$ DECLARE table_name text;BEGIN FOREACH table_name IN ARRAY ARRAY['practice_working_papers','practice_kyc_checks','practice_conflict_checks','practice_e_signatures','practice_wip_schedules','practice_document_classifications','practice_engagement_summaries'] LOOP EXECUTE format('CREATE POLICY %I ON public.%I FOR ALL TO authenticated USING(public.is_platform_admin() OR organization_id=(SELECT s.organization_id FROM public.staff s WHERE s.id=auth.uid())) WITH CHECK(public.is_platform_admin() OR organization_id=(SELECT s.organization_id FROM public.staff s WHERE s.id=auth.uid()))',table_name||'_same_org',table_name);EXECUTE format('GRANT SELECT,INSERT,UPDATE,DELETE ON public.%I TO authenticated',table_name);END LOOP;END $$;
INSERT INTO storage.buckets(id,name,public)VALUES('practice-working-papers','practice-working-papers',false)ON CONFLICT(id)DO NOTHING;CREATE POLICY practice_working_papers_storage_org ON storage.objects FOR ALL TO authenticated USING(bucket_id='practice-working-papers' AND (public.is_platform_admin() OR (storage.foldername(name))[1]=(SELECT s.organization_id::text FROM public.staff s WHERE s.id=auth.uid())))WITH CHECK(bucket_id='practice-working-papers' AND (public.is_platform_admin() OR (storage.foldername(name))[1]=(SELECT s.organization_id::text FROM public.staff s WHERE s.id=auth.uid())));

-- Additional profession packs extend the Phase 1 operational templates.
INSERT INTO public.practice_workflow_templates(organization_id,name,description,service_type)
SELECT o.id,v.name,v.description,v.service_type FROM public.organizations o CROSS JOIN(VALUES
('External audit','Planning, fieldwork, review, completion and reporting.','Audit'),('Tax compliance','Information collection, computation, review, filing and payment follow-up.','Tax'),('Legal matter','Intake, conflict clearance, matter work, review and closure.','Legal'),('Engineering consultancy','Brief, design, review, site work, certification and close-out.','Engineering'))v(name,description,service_type) ON CONFLICT(organization_id,name)DO NOTHING;
INSERT INTO public.practice_workflow_template_tasks(organization_id,template_id,title,sequence_no,due_offset_days,estimated_hours,responsible_role,requires_review)
SELECT t.organization_id,t.id,v.title,v.seq,v.days,v.hours,v.role,v.review FROM public.practice_workflow_templates t JOIN(VALUES
('External audit','Complete planning and risk assessment',1,0,8,'manager',true),('External audit','Perform fieldwork and obtain evidence',2,7,30,'auditor',true),('External audit','Clear review points',3,21,10,'auditor',true),('External audit','Complete reporting and sign-off',4,28,8,'manager',true),
('Tax compliance','Request tax information',1,0,2,'tax',false),('Tax compliance','Prepare tax computation',2,7,8,'tax',true),('Tax compliance','Obtain client approval and file',3,12,4,'manager',true),
('Legal matter','Complete intake and conflict check',1,0,3,'manager',true),('Legal matter','Perform matter work',2,5,15,'consultant',true),('Legal matter','Client review and closure',3,20,5,'manager',true),
('Engineering consultancy','Confirm brief and scope',1,0,5,'manager',true),('Engineering consultancy','Complete design or field work',2,7,24,'engineer',true),('Engineering consultancy','Review, certify and close out',3,25,8,'manager',true))v(template_name,title,seq,days,hours,role,review)ON t.name=v.template_name ON CONFLICT(template_id,sequence_no)DO NOTHING;
