-- Phase 3 integration records for calendar and client communications.
CREATE TABLE IF NOT EXISTS public.practice_calendar_events(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,client_id uuid REFERENCES public.practice_clients(id) ON DELETE CASCADE,engagement_id uuid REFERENCES public.practice_engagements(id) ON DELETE CASCADE,task_id uuid REFERENCES public.practice_tasks(id) ON DELETE SET NULL,
 title text NOT NULL,description text,location text,start_at timestamptz NOT NULL,end_at timestamptz NOT NULL,attendee_email text,event_type text NOT NULL DEFAULT 'meeting',created_by uuid REFERENCES public.staff(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.practice_communication_log(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,client_id uuid NOT NULL REFERENCES public.practice_clients(id) ON DELETE CASCADE,engagement_id uuid REFERENCES public.practice_engagements(id) ON DELETE SET NULL,contact_id uuid REFERENCES public.practice_client_contacts(id) ON DELETE SET NULL,
 channel text NOT NULL CHECK(channel IN('email','phone','meeting','portal','other')),subject text NOT NULL,summary text,direction text NOT NULL DEFAULT 'outbound' CHECK(direction IN('inbound','outbound')),occurred_at timestamptz NOT NULL DEFAULT now(),recorded_by uuid REFERENCES public.staff(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_practice_calendar_range ON public.practice_calendar_events(organization_id,start_at);CREATE INDEX IF NOT EXISTS idx_practice_communications_client ON public.practice_communication_log(client_id,occurred_at DESC);
ALTER TABLE public.practice_calendar_events ENABLE ROW LEVEL SECURITY;ALTER TABLE public.practice_communication_log ENABLE ROW LEVEL SECURITY;
DO $$ DECLARE table_name text;BEGIN FOREACH table_name IN ARRAY ARRAY['practice_calendar_events','practice_communication_log'] LOOP EXECUTE format('CREATE POLICY %I ON public.%I FOR ALL TO authenticated USING(public.is_platform_admin() OR organization_id=(SELECT s.organization_id FROM public.staff s WHERE s.id=auth.uid())) WITH CHECK(public.is_platform_admin() OR organization_id=(SELECT s.organization_id FROM public.staff s WHERE s.id=auth.uid()))',table_name||'_same_org',table_name);EXECUTE format('GRANT SELECT,INSERT,UPDATE,DELETE ON public.%I TO authenticated',table_name);END LOOP;END $$;

CREATE OR REPLACE FUNCTION public.practice_client_portal_decide_signoff(p_signoff_id uuid,p_decision text,p_notes text DEFAULT NULL,p_signer_name text DEFAULT NULL,p_signer_email text DEFAULT NULL) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE v_client uuid;v_engagement uuid;v_title text;BEGIN SELECT client_id,engagement_id,title INTO v_client,v_engagement,v_title FROM public.practice_client_signoffs WHERE id=p_signoff_id;IF NOT public.practice_portal_can_access(v_client) THEN RAISE EXCEPTION 'Access denied';END IF;IF p_decision NOT IN('approved','rejected') THEN RAISE EXCEPTION 'Invalid decision';END IF;UPDATE public.practice_client_signoffs SET status=p_decision,client_notes=p_notes,decided_at=now(),updated_at=now() WHERE id=p_signoff_id;IF p_decision='approved' AND p_signer_name IS NOT NULL THEN INSERT INTO public.practice_e_signatures(organization_id,client_id,engagement_id,signoff_id,document_title,signer_name,signer_email,consent_text) SELECT organization_id,v_client,v_engagement,p_signoff_id,v_title,p_signer_name,p_signer_email,'I confirm that I reviewed and approve this item electronically.' FROM public.practice_client_signoffs WHERE id=p_signoff_id;END IF;END $$;
GRANT EXECUTE ON FUNCTION public.practice_client_portal_decide_signoff(uuid,text,text,text,text) TO authenticated;
